replace containsRegexp with string_contains

diff --git a/core/bin/lclean b/core/bin/lclean
--- a/core/bin/lclean
+++ b/core/bin/lclean
@@ -157,7 +157,10 @@ VHOSTLIST=( "$@" )
 
 for host in "${VHOSTLIST[@]}"; do
    # TODO: change to validate against hostname regex
-   checkSpaces "$host"
+   if string_contains " " "$host"; then
+      echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+      exit 1
+   fi
 done
 
 
diff --git a/core/bin/lcrash b/core/bin/lcrash
--- a/core/bin/lcrash
+++ b/core/bin/lcrash
@@ -146,7 +146,7 @@ eval set -- "$GETOPT_OPTS"
 while true; do
    case $1 in
       -d)
-         LAB_DIRECTORY=$(makeAbsolutePath "$2")
+         LAB_DIRECTORY=$(readlink --canonicalize-missing "$2")
          shift
          ;;
       --help)
@@ -185,7 +185,10 @@ done
 VHOSTLIST=( "$@" )
 
 for host in "${VHOSTLIST[@]}"; do
-   checkSpaces "$host"
+   if string_contains " " "$host"; then
+      echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+      exit 1
+   fi
 done
 
 
@@ -199,8 +202,8 @@ if [ ! -d "$LAB_DIRECTORY" ]; then
 fi
 
 # Check whether path to the lab directory contains spaces
-if containsRegexp LAB_DIRECTORY " "; then
-   echo 1>&2 "$SCRIPTNAME: $LAB_DIRECTORY: Path contains spaces"
+if string_contains " " "$LAB_DIRECTORY"; then
+   echo 1>&2 "$SCRIPTNAME: $LAB_DIRECTORY: Path contains whitespace"
    exit 1
 fi
 
diff --git a/core/bin/lhalt b/core/bin/lhalt
--- a/core/bin/lhalt
+++ b/core/bin/lhalt
@@ -180,7 +180,10 @@ done
 VHOSTLIST=( "$@" )
 
 for host in "${VHOSTLIST[@]}"; do
-   checkSpaces "$host"
+   if string_contains " " "$host"; then
+      echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+      exit 1
+   fi
 done
 
 
diff --git a/core/bin/lstart b/core/bin/lstart
--- a/core/bin/lstart
+++ b/core/bin/lstart
@@ -329,7 +329,10 @@ done
 VHOSTLIST=( "$@" )
 
 for host in "${VHOSTLIST[@]}"; do
-   checkSpaces "$host"
+   if string_contains " " "$host"; then
+      echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+      exit 1
+   fi
 done
 
 
@@ -343,8 +346,8 @@ if [ ! -d "$LAB_DIRECTORY" ]; then
 fi
 
 # Check whether path to the lab directory contains spaces
-if containsRegexp LAB_DIRECTORY " "; then
-   echo 1>&2 "$SCRIPTNAME: $LAB_DIRECTORY: Path contains spaces"
+if string_contains " " "$LAB_DIRECTORY"; then
+   echo 1>&2 "$SCRIPTNAME: $LAB_DIRECTORY: Path contains whitespace"
    exit 1
 fi
 
diff --git a/core/bin/script_utils b/core/bin/script_utils
--- a/core/bin/script_utils
+++ b/core/bin/script_utils
@@ -28,16 +28,13 @@
 # force language to avoid localization errors
 export LANG=C
 
-# Read Netkit configuration
-# There must be multiple ShellCheck directives to mask warnings
-
-# shellcheck source=../netkit.conf
+# Read Netkit configuration in order of file localisation (per system, per
+# install, per user).
+# shellcheck disable=SC1091
 [ -f /etc/netkit.conf ] && . "/etc/netkit.conf"
-
 # shellcheck source=../netkit.conf
 [ -f "$NETKIT_HOME/netkit.conf" ] && . "$NETKIT_HOME/netkit.conf"
-
-# shellcheck source=../netkit.conf
+# shellcheck disable=SC1091
 [ -f "$HOME/.netkit/netkit.conf" ] && . "$HOME/.netkit/netkit.conf"
 
 # Assign default values to undefined parameters
@@ -87,16 +84,6 @@ varReplace() {
 }
 
 
-# This function checks whether its argument contains spaces
-checkSpaces() {
-   STRING=$1
-   if containsRegexp STRING " "; then
-      echo 1>&2 "$SCRIPTNAME: Argument '$STRING' contains spaces. They are not allowed"
-      exit 1
-   fi
-}
-
-
 ###############################################################################
 # Check if string is a valid IPv4 dotted-quad address.
 # Usage:
@@ -116,16 +103,27 @@ is_inet_addr() {
 }
 
 
-# This function searches for a regexp inside a variable value. Arguments are:
-# the name of the environment variable (the *name*, not its value!) and the
-# regular expression to be searched for.
-containsRegexp() {
-   local VARIABLE_NAME VARIABLE_VALUE REGEXP
-   VARIABLE_NAME=$1
-   REGEXP=$2
-   eval VARIABLE_VALUE='$'"${VARIABLE_NAME}"
-   echo "$VARIABLE_VALUE" | grep -q "$REGEXP" >/dev/null
-   return $?
+###############################################################################
+# Check if a string contains a sub-string.
+# Usage:
+#   string_contains QUERY STRING
+# Globals:
+#   None
+# Arguments:
+#   $1 - string to search for
+#   $2 - string to search
+# Returns:
+#   0 if string contains query, non-zero if not
+# Example:
+#   None
+###############################################################################
+string_contains() {
+   local query=$1
+   local string=$2
+
+   [[ "$string" == *"$query"* ]] && return 0
+
+   return 1
 }
 
 
@@ -284,25 +282,23 @@ show_version() {
 
 # This function creates a directory and sets global permissions for it.
 # If the directory already exists, an error is issued.
-ensureDir() {
-   if [ ! -e "$1" ]; then
-      mkdir "$1"
-      chmod 777 "$1"
-   elif [ ! -d "$1" ]; then
-      echo 1>&2 "File $1 exists: unable to create directory $1. Sorry..."
+netkit_dir_check() {
+   local dir=$1
+   if [ ! -e "$dir" ]; then
+      mkdir "$dir"
+      chmod 777 "$dir"
+   elif [ ! -d "$dir" ]; then
+      echo 1>&2 "File '$1' exists: unable to create directory '$1'"
       exit 1
    fi
 }
 
 
+# Ensure critical directories exist
+netkit_dir_check "$HOME/.netkit"
+netkit_dir_check "$HUB_SOCKET_DIR"
+netkit_dir_check "$MCONSOLE_DIR"
 
-
-# Ensure personal Netkit dir exists
-ensureDir $HOME/.netkit
-# Ensure hub socket dir exists
-ensureDir $HUB_SOCKET_DIR
-# Ensure mconsole dir exists
-ensureDir $MCONSOLE_DIR
 
 USERID=$(id -un)
 
@@ -420,19 +416,15 @@ startHub() {
 
 
 # This function starts all the hubs inside a given list
-runHubs() {
-   local hub_name BASE_HUB_NAME ACTUAL_HUB_NAME TAP_ADDRESS GUEST_ADDRESS
+run_hubs() {
+   local hub_specifications=( "$@" )
 
-   hubs=( "$@" )
+   for hub_specification in "${hub_specifications[@]}"; do
+      IFS=, read -r hub_name tap_address <<< "$hub_specification"
 
-   for hub_name in "${hubs[@]}"; do
-      BASE_HUB_NAME=$(varReplace hub_name ".*_" "")
-
-      if [ "${BASE_HUB_NAME#tap${HUB_SOCKET_EXTENSION},}" != "$BASE_HUB_NAME" ]; then
-         IFS=, read -r ACTUAL_HUB_NAME TAP_ADDRESS GUEST_ADDRESS <<< "$hub_name"
-         startInetHub "$ACTUAL_HUB_NAME" "$TAP_ADDRESS"
+      if [ "$hub_name" = "tap" ]; then
+         startInetHub "$hub_name" "$tap_address"
       else
-         # This is a normal hub
          startHub "$hub_name"
       fi
    done
@@ -442,37 +434,32 @@ runHubs() {
 # This function takes as argument a list of sockets used by virtual hubs, stops
 # those that are not used by any virtual machine and deletes the corresponding
 # sockets.
-cleanHubs() {
-   local FULL_HUB_NAME BASE_HUB_NAME
-   while [ $# -gt 0 ]; do
-      FULL_HUB_NAME=$1
-      BASE_HUB_NAME="$(varReplace FULL_HUB_NAME ".*_" "")"
-      if [ "${BASE_HUB_NAME#tap${HUB_SOCKET_EXTENSION},}" != "$BASE_HUB_NAME" ]; then
-         # This is an Internet connected hub
-         FULL_HUB_NAME=$(echo $FULL_HUB_NAME | awk -v FS="," '{print $1}')
-      fi
-      
+clean_hubs() {
+   local hub_specifications=( "$@" )
+
+   for hub_specification in "${hub_specifications[@]}"; do
+      IFS=, read -r hub_name tap_address <<< "$hub_specification"
+
+      hub_socket="$HUB_SOCKET_DIR/${HUB_SOCKET_PREFIX}_${USERID}_$hub_name$HUB_SOCKET_EXTENSION"
+
       # Avoid attempting to kill hubs for which the socket file does not exist
       # any more. Such situation may occur if user accidentally deleted it
       # (in which case the hub can safely be killed by using vclean), or if
       # a virtual machine has two (or more) network interfaces attached to the
       # same hub (in which case the script attempts to kill it twice).
-      if [ ! -e "$FULL_HUB_NAME" ]; then
-         shift
-         continue
-      fi
-      
-      if file_in_use $FULL_HUB_NAME; then
-         SWITCH_PROCESS=$(ps -wwwwwweo pid,command --sort=pid | grep "uml_switch.*$FULL_HUB_NAME" | grep -v "grep uml_switch" | awk '{print $1}' | head -n 1)
-         if [ $(lsof -p $SWITCH_PROCESS 2>/dev/null | grep -c $FULL_HUB_NAME) -le 1 ]; then
+      [ ! -e "$hub_socket" ] && continue
+
+      if file_in_use "$hub_socket"; then
+         # We get the oldest process to limit output to a single PID
+         hub_pid=$(pgrep --oldest --euid="$USERID" --full "^$NETKIT_HOME/bin/uml_switch.*$hub_socket")
+         if [ "$(lsof -a -U -p "$hub_pid" -Fn | grep -c "^n$hub_socket")" -le 1 ]; then
             # No more virtual machines are using the switch connected to this socket
-            kill $SWITCH_PROCESS > /dev/null 2>&1 && rm -f $FULL_HUB_NAME
+            kill "$hub_pid" && rm -f "$hub_socket"
          fi
       else
-         # There are no switches connected to this socket: just remove it
-         rm -f $FULL_HUB_NAME
+         # There are no switches connected to this socket - remove it
+         rm -f "$hub_socket"
       fi
-      shift
    done
 }
 
diff --git a/core/bin/vconf b/core/bin/vconf
--- a/core/bin/vconf
+++ b/core/bin/vconf
@@ -163,12 +163,12 @@ while true; do
          DOMAIN=$2
          shift
 
-         if containsRegexp DOMAIN "_"; then
+         if string_contains "_" "$DOMAIN"; then
             echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - underscores are not allowed"
             usage 1
          fi
 
-         if containsRegexp DOMAIN "," || containsRegexp DOMAIN "\\."; then
+         if string_contains "," "$DOMAIN" || string_contains "." "$DOMAIN"; then
             # If not a tap specification, but its name contains a comma
             if [ "${DOMAIN#tap,}" = "$DOMAIN" ]; then
                echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - commas and periods are only valid for tap interface specification"
@@ -176,7 +176,10 @@ while true; do
             fi
          fi
 
-         checkSpaces "$DOMAIN"
+         if string_contains " " "$DOMAIN"; then
+            echo 1>&2 "$SCRIPTNAME: $DOMAIN: Collision domain name cannot contain whitespace"
+            exit 1
+         fi
 
          # Construct array of ethN=DOMAIN
          network_interfaces+=( "$interface=$DOMAIN" )
@@ -223,7 +226,10 @@ fi
 
 # Parse virtual machine name
 VM_ID=$1
-checkSpaces "$VM_ID"
+if string_contains " " "$VM_ID"; then
+   echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+   exit 1
+fi
 shift
 
 
@@ -258,9 +264,7 @@ setup_interfaces() {
    first_iteration=true
    for interface_specification in "${interface_specifications[@]}"; do
       device=${interface_specification%%=*}
-
-      # If hub_name is blank, the network interface will be removed.
-      hub_name=${interface_specification#*=}
+      hub_specification=${interface_specification#*=}
 
       # Check if interface has already been configured
       if [[ " $used_devices " == *" $device "* ]]; then
@@ -272,9 +276,9 @@ setup_interfaces() {
       used_devices="$used_devices $device"
 
       # Check if tap interface (regular hubs cannot be named with commas)
-      if [[ "$hub_name" == tap,* ]]; then
+      if [[ "$hub_specification" == tap,* ]]; then
          # Format: tap,tap_address,guest_address
-         IFS=, read -r hub_name tap_address guest_address <<< "$hub_name"
+         IFS=, read -r hub_name tap_address guest_address <<< "$hub_specification"
 
          if ! is_inet_addr "$tap_address"; then
             echo 1>&2 "$SCRIPTNAME: $tap_address: Invalid tap address"
@@ -288,14 +292,15 @@ setup_interfaces() {
       else
          # This is a normal (i.e., not 'tap') collision domain
          unset tap_address guest_address
+         hub_name=$hub_specification
       fi
       
       hub_socket="$HUB_SOCKET_DIR/${HUB_SOCKET_PREFIX}_${USERID}_$hub_name$HUB_SOCKET_EXTENSION"
 
       if [ -n "$tap_address" ]; then
-         HUBLIST+=( "$hub_socket,$tap_address,$guest_address" )
+         HUBLIST+=( "$hub_name,$tap_address" )
       elif [ -n "$hub_name" ]; then
-         HUBLIST+=( "$hub_socket" )
+         HUBLIST+=( "$hub_name" )
       fi
 
       if $first_iteration; then
@@ -379,7 +384,7 @@ if [ ${#network_interfaces[@]} -gt 0 ]; then
 fi
 
 ##### Start network hubs
-runHubs "${HUBLIST[@]}"
+run_hubs "${HUBLIST[@]}"
 
 ##### Attach/remove network interfaces
 invoke_mconsole "${MCONSOLE_CMD[@]}"
diff --git a/core/bin/vcrash b/core/bin/vcrash
--- a/core/bin/vcrash
+++ b/core/bin/vcrash
@@ -167,7 +167,10 @@ while true; do
          USER=$2
          [ "$USER" = "-" ] && unset USER
          # TODO: change to username regex
-         checkSpaces "$USER"
+         if string_contains " " "$USER"; then
+            echo 1>&2 "$SCRIPTNAME: Username cannot contain whitespace"
+            exit 1
+         fi
          shift
          ;;
       --version)
@@ -197,7 +200,10 @@ fi
 vm_ids=( "$@" )
 
 for host in "${vm_ids[@]}"; do
-   checkSpaces "$host"
+   if string_contains " " "$host"; then
+      echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+      exit 1
+   fi
 done
 
 
diff --git a/core/bin/vdump b/core/bin/vdump
--- a/core/bin/vdump
+++ b/core/bin/vdump
@@ -132,7 +132,10 @@ elif [ $# -gt 1 ]; then
 fi
 
 hub_name=$1
-checkSpaces "$hub_name"
+if string_contains " " "$hub_name"; then
+   echo 1>&2 "$SCRIPTNAME: Collision domain name cannot contain whitespace"
+   exit 1
+fi
 shift
 
 
diff --git a/core/bin/vhalt b/core/bin/vhalt
--- a/core/bin/vhalt
+++ b/core/bin/vhalt
@@ -157,7 +157,10 @@ done
 vm_hostnames=( "$@" )
 
 for host in "${vm_hostnames[@]}"; do
-   checkSpaces "$host"
+   if string_contains " " "$host"; then
+      echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+      exit 1
+   fi
 done
 
 
diff --git a/core/bin/vlist b/core/bin/vlist
--- a/core/bin/vlist
+++ b/core/bin/vlist
@@ -240,7 +240,10 @@ done
 vm_ids=( "$@" )
 
 for host in "${vm_ids[@]}"; do
-   checkSpaces "$host"
+   if string_contains " " "$host"; then
+      echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+      exit 1
+   fi
 done
 
 
diff --git a/core/bin/vstart b/core/bin/vstart
--- a/core/bin/vstart
+++ b/core/bin/vstart
@@ -260,12 +260,12 @@ while true; do
          OPT="$1"
          DOMAIN="$2"
 
-         if containsRegexp DOMAIN "_"; then
+         if string_contains "_" "$DOMAIN"; then
             echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - underscores are not allowed"
             usage 1
          fi
 
-         if containsRegexp DOMAIN "," || containsRegexp DOMAIN "\\."; then
+         if string_contains "," "$DOMAIN" || string_contains "." "$DOMAIN"; then
             # If not a tap specification, but its name contains a comma
             if [ "${DOMAIN#tap,}" = "$DOMAIN" ]; then
                echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - commas and periods are only valid for tap interface specification"
@@ -275,7 +275,10 @@ while true; do
 
          # TODO: double-check checkSpaces and maybe change ETH_INTERFACES to
          # array.
-         checkSpaces "$DOMAIN"
+         if string_contains " " "$DOMAIN"; then
+            echo 1>&2 "$SCRIPTNAME: $DOMAIN: Collision domain name cannot contain whitespace"
+            exit 1
+         fi
          ETH_INTERFACES="$ETH_INTERFACES ${OPT#--}=$DOMAIN"
          shift
          ;;
@@ -285,7 +288,7 @@ while true; do
       -f|--filesystem)
          VM_FS=$2
 
-         if containsRegexp CURRENT_ARGUMENT ","; then
+         if string_contains "," "$VM_FS"; then
             echo 1>&2 "$SCRIPTNAME: $VM_FS: Invalid filesystem - commas are not allowed"
             usage 1
          fi
@@ -321,7 +324,7 @@ while true; do
       -m|--model-fs)
          VM_MODEL_FS=$2
 
-         if containsRegexp VM_MODEL_FS ","; then
+         if string_contains "," "$VM_MODEL_FS"; then
             echo 1>&2 "$SCRIPTNAME: $VM_MODEL_FS: Invalid filesystem - commas are not allowed"
             usage 1
          fi
@@ -394,7 +397,10 @@ fi
 
 # Parse virtual machine name
 VM_NAME=$1
-checkSpaces "$VM_NAME"
+if string_contains " " "$VM_NAME"; then
+   echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+   exit 1
+fi
 shift
 
 
@@ -417,7 +423,7 @@ if [ -n "$REMOVE_FS" ] && [ -n "$USE_MODEL_FS" ]; then
 fi
 
 # Check whether the path to the current directory contains spaces
-if containsRegexp PWD " "; then
+if string_contains " " "$PWD"; then
    echo 1>&2 "$SCRIPTNAME: Current working directory path contains spaces"
    usage 1
 fi
@@ -496,7 +502,7 @@ setup_interfaces() {
    first_iteration=true
    while [ $# -gt 0 ]; do
       device=${1%%=*}
-      hub_name=${1#*=}
+      hub_specification=${1#*=}
 
       # Check if interface has already been configured
       if [[ " $used_devices " == *" $device "* ]]; then
@@ -508,9 +514,9 @@ setup_interfaces() {
       used_devices="$used_devices $device"
 
       # Check if tap interface (regular hubs cannot be named with commas)
-      if [[ "$hub_name" == tap,* ]]; then
+      if [[ "$hub_specification" == tap,* ]]; then
          # Format: tap,tap_address,guest_address
-         IFS=, read -r hub_name tap_address guest_address <<< "$hub_name"
+         IFS=, read -r hub_name tap_address guest_address <<< "$hub_specification"
 
          if ! is_inet_addr "$tap_address"; then
             echo 1>&2 "$SCRIPTNAME: $tap_address: Invalid tap address"
@@ -524,6 +530,7 @@ setup_interfaces() {
       else
          # This is a normal (i.e., not 'tap') collision domain
          unset tap_address guest_address
+         hub_name=$hub_specification
       fi
       
       hub_socket="$HUB_SOCKET_DIR/${HUB_SOCKET_PREFIX}_${USERID}_$hub_name$HUB_SOCKET_EXTENSION"
@@ -531,7 +538,7 @@ setup_interfaces() {
       KERNELCMD="$KERNELCMD $device=daemon,,,$hub_socket"
       
       if [ -n "$tap_address" ]; then
-         HUBLIST+=( "$hub_socket,$tap_address,$guest_address" )
+         HUBLIST+=( "$hub_name,$tap_address" )
 
          KERNELCMD="$KERNELCMD autoconf_$device=$guest_address"
 
@@ -542,7 +549,7 @@ setup_interfaces() {
             enabled_default_route=1
          fi
       else
-         HUBLIST+=( "$hub_socket" )
+         HUBLIST+=( "$hub_name" )
       fi
 
       if $first_iteration; then
@@ -734,13 +741,8 @@ elif [ "$VM_CON0" = "tmux" ]; then
 fi
 
 
-# TODO: remove evil eval
 # Actually start network hubs
-eval runHubs "${HUBLIST[@]}"
-
-# TODO: why export?
-# Prepare the cleanHubs function for execution after a virtual machine stops
-export cleanHubs
+run_hubs "${HUBLIST[@]}"
 
 
 ###############################################################################
@@ -821,7 +823,7 @@ run_kernel_command() {
 
    run_command "$JUST_PRINT" "${KERNELCMD[*]}" "${KERNELCMD[@]}"
 
-   cleanHubs "${HUBLIST[@]}"
+   clean_hubs "${HUBLIST[@]}"
 }
 
 
