standardise variable naming

diff --git a/core/bin/lcommon b/core/bin/lcommon
--- a/core/bin/lcommon
+++ b/core/bin/lcommon
@@ -26,10 +26,10 @@
 ###############################################################################
 # Print a string with bold formatting.
 # Usage:
-#   bold_print $1
+#   bold_print MESSAGE
 # Globals:
-#   r- COLOR_BOLD
-#   r- COLOR_NORMAL
+#   r- color_bold
+#   r- color_normal
 # Arguments:
 #   $1 - string to print
 # Returns:
@@ -38,7 +38,7 @@
 #   None
 ###############################################################################
 bold_print() {
-   printf "%b%s%b\n" "$COLOR_BOLD" "$1" "$COLOR_NORMAL"
+   printf "%b%s%b\n" "$color_bold" "$1" "$color_normal"
 }
 
 
@@ -58,10 +58,10 @@ bold_print() {
 #   if array_contains "a" "${bar[@]}"; then echo "Found!"; fi
 ###############################################################################
 array_contains() {
-   query=$1
-   shift
+   local query=$1
+   local array=( "${@:2}" )
 
-   array=( "$@" )
+   local item
 
    for item in "${array[@]}"; do
       [ "$query" = "$item" ] && return 0
@@ -88,6 +88,8 @@ array_contains() {
 ###############################################################################
 build_vhostlist() {
    local lab_directory=$1
+
+   local dir vhost vhosts vhostlist_bak
 
    # Build list of virtual machines that are part of the lab
    for dir in "$lab_directory"/*/; do
@@ -175,6 +177,8 @@ generate_info_str() {
    if [ ${#collated_lab_info_values[@]} -gt 1 ]; then
       for value in "${!collated_lab_info_values[@]}"; do
          lab_info_str+="$separator$value (${collated_lab_info_values[$value]})"
+
+         # Comma-separate subsequent interfaces
          separator=", "
       done
    elif [ ${#collated_lab_info_values[@]} -eq 1 ]; then
@@ -194,11 +198,12 @@ generate_info_str() {
 # Get the value of a parameter set in a lab's lab.conf file and write to
 # standard output.
 # Usage:
-#   get_lab_variable DIRECTORY
+#   get_lab_variable VARIABLE DIR
 # Globals:
 #   None
 # Arguments:
-#   $1 - lab directory
+#   $1 - lab variable name
+#   $2 - lab directory
 # Returns:
 #   None
 # Example:
@@ -220,9 +225,9 @@ get_lab_variable() {
 # Usage:
 #   lab_welcome [DIRECTORY]...
 # Globals:
-#   r- COLOR_BOLD
-#   r- COLOR_HIGHLIGHT
-#   r- COLOR_NORMAL
+#   r- color_blue
+#   r- color_bold
+#   r- color_normal
 #   r- SCRIPTNAME
 # Arguments:
 #  ... - list of lab directories
@@ -234,7 +239,9 @@ get_lab_variable() {
 lab_welcome() {
    local lab_directories=( "$@" )
 
-   local dir lab lab_directories_str
+   local lab_directories_str
+   local dir lab
+
    declare -A lab_versions lab_authors lab_emails lab_webs lab_descriptions
 
    printf -v lab_directories_str '%s, ' "${lab_directories[@]}"
@@ -267,13 +274,14 @@ lab_welcome() {
    done
 
    # Convert the multi-lab arrays to flat, comma-separated lists and print
-   echo "${COLOR_BOLD}Lab directory(ies)$COLOR_NORMAL: $COLOR_HIGHLIGHT$lab_directories_str$COLOR_NORMAL"
-   echo "${COLOR_BOLD}Version(s)$COLOR_NORMAL:         $COLOR_HIGHLIGHT$(generate_info_str lab_versions)$COLOR_NORMAL"
-   echo "${COLOR_BOLD}Author(s)$COLOR_NORMAL:          $COLOR_HIGHLIGHT$(generate_info_str lab_authors)$COLOR_NORMAL"
-   echo "${COLOR_BOLD}Email(s)$COLOR_NORMAL:           $COLOR_HIGHLIGHT$(generate_info_str lab_emails)$COLOR_NORMAL"
-   echo "${COLOR_BOLD}URL(s)$COLOR_NORMAL:             $COLOR_HIGHLIGHT$(generate_info_str lab_webs)$COLOR_NORMAL"
-   echo "${COLOR_BOLD}Description(s)$COLOR_NORMAL:"
-   echo "$COLOR_HIGHLIGHT$(generate_info_str lab_descriptions)$COLOR_NORMAL"
+   # TODO: echo -e (or similar) for this and all other output
+   echo "${color_bold}Lab directory(ies)$color_normal: $color_blue$lab_directories_str$color_normal"
+   echo "${color_bold}Version(s)$color_normal:         $color_blue$(generate_info_str lab_versions)$color_normal"
+   echo "${color_bold}Author(s)$color_normal:          $color_blue$(generate_info_str lab_authors)$color_normal"
+   echo "${color_bold}Email(s)$color_normal:           $color_blue$(generate_info_str lab_emails)$color_normal"
+   echo "${color_bold}URL(s)$color_normal:             $color_blue$(generate_info_str lab_webs)$color_normal"
+   echo "${color_bold}Description(s)$color_normal:"
+   echo "$color_blue$(generate_info_str lab_descriptions)$color_normal"
 }
 
 
@@ -294,17 +302,19 @@ lab_welcome() {
 lab_clean() {
    local lab_directory=$1
 
+   local vhost
+
    build_vhostlist "$lab_directory"
 
    bold_print "Cleaning up lab inside '$lab_directory'..."
 
    for vhost in "${VHOSTLIST[@]}"; do
       # Remove files from the lab directory
-      rm "${VERBOSE:+"--verbose"}" -r "${MCONSOLE_DIR:?}/$vhost"
-      rm "${VERBOSE:+"--verbose"}" "$lab_directory/$vhost."{"ready","disk","log","testdone"}
+      rm ${VERBOSE:+"--verbose"} -r "${MCONSOLE_DIR:?}/$vhost"
+      rm ${VERBOSE:+"--verbose"} "$lab_directory/$vhost."{"ready","disk","log","testdone"}
    done
 
-   rm "${VERBOSE:+"--verbose"}" "$lab_directory/readyfor.test"
+   rm ${VERBOSE:+"--verbose"} "$lab_directory/readyfor.test"
 }
 
 
@@ -327,19 +337,19 @@ lab_clean() {
 lab_crash() {
    local lab_directory=$1
    local keep_fs=$2
-   local kill_mode=$2
+   local kill_mode=$3
 
-   local VCRASH_OPTIONS
+   local vcrash_args vhost
 
    build_vhostlist "$lab_directory"
 
-   [ -z "$VERBOSE" ]   && VCRASH_OPTIONS+=( "-q" )
-   [ -z "$keep_fs" ]   && VCRASH_OPTIONS+=( "-r" )
-   [ -n "$kill_mode" ] && VCRASH_OPTIONS+=( "-k" )
+   [ -z "$VERBOSE" ]   && vcrash_args+=( "-q" )
+   [ -z "$keep_fs" ]   && vcrash_args+=( "-r" )
+   [ -n "$kill_mode" ] && vcrash_args+=( "-k" )
    
-   for VM in "${VHOSTLIST[@]}"; do
-      [ -z "$VERBOSE" ] && bold_print "Crashing '$VM'..."
-      vcrash "${VCRASH_OPTIONS[@]}" "$VM" && rm -f "$lab_directory/$VM.ready"
+   for vhost in "${VHOSTLIST[@]}"; do
+      [ -n "$VERBOSE" ] && bold_print "Crashing '$vhost'..."
+      vcrash "${vcrash_args[@]}" "$vhost" && rm -f "$lab_directory/$vhost.ready"
    done
    
    bold_print "Removing readyfor.test..."
@@ -350,16 +360,14 @@ lab_crash() {
 ###############################################################################
 # Start a single virtual machine within a lab.
 # Usage:
-#   single_lab_vm_start FAST_MODE TEST_MODE MAKEFILE DIR MACHINE [VSTART_OPT]...
+#   single_lab_vm_start FAST_MODE DIR MACHINE [PASSTHROUGH]...
 # Globals:
 #   r- GRACE_TIME
 #   r- VERBOSE
 # Arguments:
 #   $1 - set to 1 for fast mode, empty string otherwise
-#   $2 - set to 1 for test mode, empty string otherwise
-#   $3 - used internally when lstart is invoked with Make
-#   $4 - lab directory
-#   $5 - machine to start up
+#   $2 - lab directory
+#   $3 - machine to start up
 #  ... - options to passthrough to vstart (appended on)
 # Returns:
 #   None
@@ -368,25 +376,15 @@ lab_crash() {
 ###############################################################################
 single_lab_vm_start() {
    local fast_mode=$1
-   local test_mode=$2
-   local makefile=$3
-   local lab_directory=$4
-   local VM=$5
-   local passthrough_opts=( "${@:6}" )
+   local lab_directory=$2
+   local vm=$3
+   local passthrough_args=( "${@:4}" )
+
+   local configuration option value
 
    # Add host lab and working directory, and place filesystem inside the lab
    # directory.
-   local VSTART_OPTIONS=( "--hostlab" "$lab_directory" "--hostwd" "$PWD" "--filesystem" "$lab_directory/$VM.disk" )
-
-   if [ -n "$test_mode" ]; then
-      VSTART_OPTIONS+=( "--test" )
-
-      if [ -z "$makefile" ]; then
-         # If invoked via Make, there should already be these options
-         # passed through
-         VSTART_OPTIONS+=( "--con0" "none" "--con1" "none" )
-      fi
-   fi
+   local vstart_args=( "--hostlab" "$lab_directory" "--hostwd" "$PWD" "--filesystem" "$lab_directory/$vm.disk" )
 
    # Generate vstart argument list
    if [ -e "$lab_directory/lab.conf" ]; then
@@ -403,40 +401,40 @@ single_lab_vm_start() {
          [[ "$option" =~ ^([0-9]|[1-9][0-9]+)$ ]] && option="eth$option"
 
          if [ "${#option}" -eq 1 ]; then
-            VSTART_OPTIONS+=( "-$option" )
+            vstart_args+=( "-$option" )
          else
-            VSTART_OPTIONS+=( "--$option" )
+            vstart_args+=( "--$option" )
          fi
 
          # NOTE: if vstart is ever changed to have an option with an optional
          # argument (denoted with '::' in the option string), an exception when
          # appending the argument must be made (an '=' is required for long
          # options, no delimiter for short ones).
-         [ -n "$value" ] && VSTART_OPTIONS+=( "$value" )
-      done < <(grep "^[[:blank:]]*$VM\[.*\][[:blank:]]*=" "$lab_directory/lab.conf")
+         [ -n "$value" ] && vstart_args+=( "$value" )
+      done < <(grep "^[[:blank:]]*$vm\[.*\][[:blank:]]*=" "$lab_directory/lab.conf")
    fi
    
    # Remove .ready file, if existing
-   [ -e "$lab_directory/$VM.ready" ] && rm -f "$lab_directory/$VM.ready"
+   [ -e "$lab_directory/$vm.ready" ] && rm -f "$lab_directory/$vm.ready"
 
    if [ -z "$VERBOSE" ]; then
-      bold_print "Starting '$VM'..."
+      bold_print "Starting '$vm'..."
    else
-      bold_print "Starting '$VM' with options '${VSTART_OPTIONS[*]} ${passthrough_opts[*]}'... "
+      bold_print "Starting '$vm' with options '${vstart_args[*]} ${passthrough_args[*]}'... "
    fi
 
-   if ! vstart "${VSTART_OPTIONS[@]}" "${passthrough_opts[@]}" "$VM"; then
-      echo 2>&1 "Error while starting virtual machine '$VM'"
+   if ! vstart "${vstart_args[@]}" "${passthrough_args[@]}" "$vm"; then
+      echo 2>&1 "Error while starting virtual machine '$vm'"
       exit 1
    fi
 
    # Wait for virtual host startup script to create .ready file
    if [ -z "$fast_mode" ]; then
-      while [ ! -e "$lab_directory/$VM.ready" ]; do
+      while [ ! -e "$lab_directory/$vm.ready" ]; do
          sleep 1
       done
 
-      rm -f "$lab_directory/$VM.ready"
+      rm -f "$lab_directory/$vm.ready"
    fi
    
    # Wait for a specified amount of time before returning
@@ -466,22 +464,24 @@ lab_start() {
    local test_mode=$2
    local makefile=$3
    local lab_directory=$4
-   local passthrough_opts=( "${@:5}" )
+   local passthrough_args=( "${@:5}" )
 
-   local BASE_VSTART_OPTIONS
+   local vhost
 
    build_vhostlist "$lab_directory"
 
-   [ -z "$VERBOSE" ] && BASE_VSTART_OPTIONS+=( "-q" )
-   BASE_VSTART_OPTIONS+=( "${passthrough_opts[@]}" )
-   
-   if [ "${#VHOSTLIST[@]}" -gt 0 ]; then
-      for VM in "${VHOSTLIST[@]}"; do
-         single_lab_vm_start "$fast_mode" "$test_mode" "$makefile" "$lab_directory" "$VM"
-      done
-   else
+   if [ "${#VHOSTLIST[@]}" -eq 0 ]; then
       echo 1>&2 "Warning: there are no virtual machines to be started."
+      return
    fi
+
+   # We prepend so passthrough_args can override 
+   [ -z "$VERBOSE" ] && passthrough_args=( "-q" "${passthrough_args[@]}" )
+
+   # TODO: global rename of vhost to vm? Or vice-versa
+   for vhost in "${VHOSTLIST[@]}"; do
+      single_lab_vm_start "$fast_mode" "$lab_directory" "$vhost" "${passthrough_args[@]}"
+   done
    
    # The readyfor.test file should not be created if we have been invoked
    # with the --makefile option (=launch a single machine and exit).
@@ -508,7 +508,11 @@ lab_start() {
 lab_start_parallel() {
    local test_mode=$1
    local lab_directory=$2
-   local passthrough_opts=( "${@:3}" )
+   local passthrough_args=( "${@:3}" )
+
+   local lstart_args arg
+   local lstart_cmd escaped_lstart_cmd
+   local tab makefile_contents
 
    build_vhostlist "$lab_directory"
    
@@ -517,37 +521,34 @@ lab_start_parallel() {
       return
    fi
    
-   # Pass "passthrough" options on to further invocations of this script
-   [ -n "$VERBOSE" ] && PASSTHROUGH_STUFF+=( "-v" )
-   for CURRENT_OPTION in "${passthrough_opts[@]}"; do
-      PASSTHROUGH_STUFF+=( "-o" "$CURRENT_OPTION" )
+   # Pass "passthrough" options on to the second invocation of lstart/ltest
+   [ -n "$VERBOSE" ] && lstart_args+=( "-v" )
+
+   for arg in "${passthrough_args[@]}"; do
+      lstart_args+=( "-o" "$arg" )
    done
 
    # Pass testmode along subsequent invocations of this script
    if [ -n "$test_mode" ]; then
-      COMMAND_NAME="ltest"
-
-      # The default console is "none" for ltest. By prepending to passthrough
-      # options, we allow the user to override this with further conX options.
-      PASSTHROUGH_STUFF=( "-o" "--con0=none" "-o" "--con1=none" "${PASSTHROUGH_STUFF[@]}" )
+      program_name="ltest"
    else
-      COMMAND_NAME="lstart"
+      program_name="lstart"
    fi
    
-   # The make utility expects an empty argument when infinitely many jobs
+   # The make utility expects an empty argument to -j when infinitely many jobs
    # should be used.
-   [ "$MAX_SIMULTANEOUS_VMS" -eq 0 ] && MAX_SIMULTANEOUS_VMS=""
+   [ "$MAX_SIMULTANEOUS_VMS" -eq 0 ] && unset MAX_SIMULTANEOUS_VMS
 
 
-   cmd=( "$COMMAND_NAME" "-d" "$lab_directory" "--makefile" "${PASSTHROUGH_STUFF[@]}" )
+   lstart_cmd=( "$program_name" "-d" "$lab_directory" "--makefile" "${lstart_args[@]}" )
 
    # We expand this array with the Q operator when writing to the Makefile.
    # This ensures escaping sufficient for reuse in a shell command.
-   escaped_cmd=${cmd[*]@Q}
+   escaped_lstart_cmd=${lstart_cmd[*]@Q}
 
    # Make requires all dollar signs (whether quoted or not) to be escaped with
    # a second dollar sign.
-   escaped_cmd=${escaped_cmd//$/\$$}
+   escaped_lstart_cmd=${escaped_lstart_cmd//$/\$$}
 
    # Labs are started in parallel with GNU Make, which automatically handles
    # lab.dep (which is formatted as Makefile targets).
@@ -570,7 +571,7 @@ lab_start_parallel() {
 SHELL := /bin/bash
 
 %: dummy-prerequisite-to-force-remaking
-${tab}[ '\$*' != "lab.dep" ] && $escaped_cmd '\$*'
+${tab}[ '\$*' != "lab.dep" ] && $escaped_lstart_cmd '\$*'
 
 dummy-prerequisite-to-force-remaking:
 ${tab}# Dummy line. Unuseful, yet necessary
@@ -580,7 +581,7 @@ EOF
 
    # Read the Makefile from stdin without implicit rules, and hide the output. It
    # it parallelised to the MAX_SIMULTANEOUS_VMS configuration option.
-   make -irsC "$lab_directory" -f - -j "$MAX_SIMULTANEOUS_VMS" "${VHOSTLIST[@]}" <<< "$makefile_contents"
+   make -irsC "$lab_directory" -f - -j ${MAX_SIMULTANEOUS_VMS:+"$MAX_SIMULTANEOUS_VMS"} "${VHOSTLIST[@]}" <<< "$makefile_contents"
 
    
    # Signal that every machine is ready for testing once booted.
@@ -605,6 +606,11 @@ EOF
 generate_dot_graph() {
    local lab_confs=( "$@" )
 
+   local configuration vm option value
+   local hub_name hub_names
+
+   declare -A device_ids options
+
    # Global map parameters
    cat << EOF
 graph netkit_jh_graph {
@@ -613,8 +619,6 @@ graph netkit_jh_graph {
    resolution=400.0;
    splines="line";
 EOF
-
-   declare -A device_ids options
 
    while IFS= read -r configuration; do
       # The [][] is ][ inside a bracket expression to match an opening or
@@ -649,7 +653,7 @@ EOF
    ];'
 EOF
 
-         domains+=( "$value" )
+         hub_names+=( "$value" )
 
          # Device IDs cannot have whitespace, so a space-separated list is
          # safe.
@@ -679,9 +683,9 @@ EOF
    done
 
    # Remove bounding box from collision domain labels (just text)
-   for domain in "${domains[@]}"; do
+   for hub_name in "${hub_names[@]}"; do
       cat << EOF
-   "$domain" [
+   "$hub_name" [
       shape=plaintext,
       width=0,
       height=0,
@@ -700,14 +704,15 @@ lab_map() {
    local map_file=$1
    local lab_confs=( "${@:2}" )
 
-   GRAPH_GENERATOR=$(which neato)
-   if [ -z "$GRAPH_GENERATOR" ]; then
-      echo 1>&2 "Error: the GraphViz library does not appear to be installed."
-      echo 1>&2 "Please install the GraphViz library."
-      return 1
+   # TODO: check for its existence in setup scripts
+   local graph_generator="neato"
+
+   if ! command -v "$graph_generator" > /dev/null 2>&1; then
+      echo 1>&2 "$SCRIPTNAME: $graph_generator: Graphviz graph generator not found"
+      exit 1
    fi
 
-   generate_dot_graph "${lab_confs[@]}" | "$GRAPH_GENERATOR" -Tpng -o"$map_file"
+   generate_dot_graph "${lab_confs[@]}" | "$graph_generator" -Tpng -o"$map_file"
 }
 
 
@@ -724,6 +729,9 @@ hostname_regex="([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,62}[a-zA-Z0-9])"
 
 
 # ANSI color escape sequences
-COLOR_HIGHLIGHT='\033[34;1m'
-COLOR_NORMAL='\033[0m'
-COLOR_BOLD='\033[1m'
+color_normal='\033[0m'
+color_bold='\033[1m'
+color_red='\033[31;1m'
+color_green='\033[32;1m'
+color_yellow='\033[33;1m'
+color_blue='\033[34;1m'
diff --git a/core/bin/lstart b/core/bin/lstart
--- a/core/bin/lstart
+++ b/core/bin/lstart
@@ -293,7 +293,7 @@ while true; do
          usage 0
          ;;
       -l|--list)
-         LISTVM=1
+         list_vm=1
          ;;
       --makefile)
          # This is a hidden option which is used by lstart/ltest itself when
@@ -305,17 +305,20 @@ while true; do
          shift
          ;;
       -p)
-         # Argument is optional - it will be an empty string if omitted.
-         OPT_ARG=$2
+         parallelisation=$2
          shift
 
-         case $OPT_ARG in
-            ""|*[!0-9]*)
+         # Argument is optional - it will be an empty string if omitted.
+         case $parallelisation in
+            "")
+               # No argument implies MAX_SIMULTAENEOUS_VMS will be the 
+               ;;
+            *[!0-9]*)
                echo 1>&2 "$SCRIPTNAME: Argument to option '-p' must be a positive integer or 0"
                usage 1
                ;;
             *)
-               MAX_SIMULTANEOUS_VMS=$OPT_ARG
+               MAX_SIMULTANEOUS_VMS=$parallelisation
                ;;
          esac
 
@@ -323,7 +326,7 @@ while true; do
          force_parallel_mode=1
          ;;
       -R|--rebuild-signature)
-         CREATE_SIGNATURE=1
+         rebuild_signature=1
          ;;
       -S|--script-mode)
          script_mode=1
@@ -341,12 +344,10 @@ while true; do
          VERBOSE=1
          ;;
       --verify)
-         OPT_ARG=$2
-         shift
-
-         case $OPT_ARG in
+         case $2 in
             user|builtin|both)
-               VERIFY=$OPT_ARG
+               test_type=$2
+               shift
                ;;
             *)
                echo 1>&2 "$SCRIPTNAME: Invalid argument to option '--verify'"
@@ -359,16 +360,14 @@ while true; do
          exit 0
          ;;
       -w|--wait)
-         OPT_ARG=$2
-         shift
-
-         case $OPT_ARG in
+         case $2 in
             ""|*[!0-9]*)
                echo 1>&2 "$SCRIPTNAME: Argument to option '-w' must be a positive integer or 0"
                usage 1
                ;;
             *)
-               GRACE_TIME=$OPT_ARG
+               GRACE_TIME=$2
+               shift
                ;;
          esac
          ;;
@@ -422,6 +421,10 @@ fi
 # Check if the script has been invoked for testing
 if [ "$SCRIPTNAME" = "ltest" ]; then
    test_mode=1
+
+   # Default console is "none" for ltest. By prepending, we allow other
+   # passthrough options to override this.
+   passthrough_opts=( "--con0" "none" "--con1" "none" "${passthrough_opts[@]}" )
 
    # Hide .disk files when running tests
    passthrough_opts+=( "-D" )
@@ -494,13 +497,6 @@ else
 fi
 
 
-# TODO: put in lcommon
-COLOR_YELLOW='\033[33;1m'
-COLOR_RED='\033[31;1m'
-COLOR_GREEN='\033[32;1m'
-COLOR_NORMAL='\033[0m'
-
-
 if [ -z "$script_mode" ]; then
    echo
    bold_print "The lab has been started."
@@ -510,17 +506,16 @@ else
 fi
 
 # Return the status of the lab test
-EXIT_VALUE=0
+exit_code=0
 
 if [ -n "$test_mode" ]; then
    # Wait for the test to finish
-   MACHINES_COUNT=${#VHOSTLIST[@]}
+   vhost_count=${#VHOSTLIST[@]}
 
-   testdone_count=0
-   until [ "$testdone_count" -ge "$MACHINES_COUNT" ]; do
+   tests_completed=0
+   while [ "$tests_completed" -lt "$vhost_count" ]; do
       testdone_files=( "$lab_directory"/*.testdone )
-      testdone_count=${#testdone_files[@]}
-
+      tests_completed=${#testdone_files[@]}
       sleep 1
    done
 
@@ -531,74 +526,67 @@ if [ -n "$test_mode" ]; then
       echo -n "Stopping lab... "
    fi
 
-   lab_crash "$lab_directory" > /dev/null
+   lab_crash "$lab_directory" "" "" > /dev/null
    lab_clean "$lab_directory" > /dev/null
 
    # Check whether we need to build a test signature or to verify the test
    # outcome.
-   if [ ! -d "$lab_directory/_test/signature" ] || [ -n "$CREATE_SIGNATURE" ]; then
+   if [ ! -d "$lab_directory/_test/signature" ] || [ -n "$rebuild_signature" ]; then
       # (Re)create the test signature
-      rm -rf "$lab_directory/_test/signature" > /dev/null
+      rm -rf "$lab_directory/_test/signature"
       mv "$lab_directory/_test/results" "$lab_directory/_test/signature"
 
       if [ -z "$script_mode" ]; then
          bold_print "Test signature created."
       else
-         printf "test completed.\t\t[ %bSIGN%b ]" "$COLOR_YELLOW" "$COLOR_NORMAL"
+         printf "test completed.\t\t[ %bSIGN%b ]\n" "$color_yellow" "$color_normal"
       fi
    else
       # Verify the test outcome against the signature
-      case $VERIFY in
+      case $test_type in
          user)
-            diff -qEbB "$lab_directory/_test/signature/"*.user --to-file "$lab_directory/_test/results" > /dev/null
-            EXIT_VALUE=$?
+            diff -qEbB "$lab_directory/_test/signature/"*.user    --to-file "$lab_directory/_test/results" > /dev/null
+            exit_code=$?
             ;;
          builtin)
             diff -qEbB "$lab_directory/_test/signature/"*.default --to-file "$lab_directory/_test/results" > /dev/null
-            EXIT_VALUE=$?
+            exit_code=$?
             ;;
          both)
-            diff -qEbBr "$lab_directory/_test/signature" --to-file "$lab_directory/_test/results" > /dev/null
-            EXIT_VALUE=$?
+            diff -qEbBr "$lab_directory/_test/signature"          --to-file "$lab_directory/_test/results" > /dev/null
+            exit_code=$?
             ;;
          *)
-            # VERIFY has not been set
-            EXIT_VALUE=0
-            for CURRENT_VHOST in "${VHOSTLIST[@]}"; do
-               if [ -f "$lab_directory/_test/signature/$CURRENT_VHOST.user" ]; then
-                  diff -qEbB "$lab_directory/_test/signature/$CURRENT_VHOST.user" --to-file "$lab_directory/_test/results" > /dev/null
-                  EXIT_VALUE=$((EXIT_VALUE + $?))
-               else
-                  if [ -f "$lab_directory/_test/signature/$CURRENT_VHOST.default" ]; then
-                     diff -qEbB "$lab_directory/_test/signature/$CURRENT_VHOST.default" --to-file "$lab_directory/_test/results" > /dev/null
-                     EXIT_VALUE=$((EXIT_VALUE + $?))
-                  fi
+            # test_type has not been set
+            for vhost in "${VHOSTLIST[@]}"; do
+               if [ -f "$lab_directory/_test/signature/$vhost.user" ]; then
+                  diff -qEbB "$lab_directory/_test/signature/$vhost.user" --to-file "$lab_directory/_test/results" > /dev/null
+                  exit_code=$((exit_code + $?))
+               elif [ -f "$lab_directory/_test/signature/$vhost.default" ]; then
+                  diff -qEbB "$lab_directory/_test/signature/$vhost.default" --to-file "$lab_directory/_test/results" > /dev/null
+                  exit_code=$((exit_code + $?))
                fi
             done
             ;;
       esac
 
       if [ -z "$script_mode" ]; then
-         if [ "$EXIT_VALUE" -eq 0 ]; then
+         if [ "$exit_code" -eq 0 ]; then
             bold_print "Test succeeded."
          else
             bold_print "Test FAILED!"
          fi
       else
-         if [ "$EXIT_VALUE" -eq 0 ]; then
-            printf "test completed.\t\t[ %b OK %b ]" "$COLOR_GREEN" "$COLOR_NORMAL"
+         if [ "$exit_code" -eq 0 ]; then
+            printf "test completed.\t\t[ %b OK %b ]\n" "$color_green" "$color_normal"
          else
-            printf "test completed.\t\t[ %bFAIL%b ]" "$COLOR_RED" "$COLOR_NORMAL"
+            printf "test completed.\t\t[ %bFAIL%b ]\n" "$color_red" "$color_normal"
          fi
       fi
    fi
 fi
 
 # Show a list of running virtual machines, if asked to
-if [ -n "$LISTVM" ]; then
-   echo
-   vlist
-fi
+[ -n "$list_vm" ] && vlist
 
-[ -z "$script_mode" ] && echo
-exit $EXIT_VALUE
+exit $exit_code
diff --git a/core/bin/script_utils b/core/bin/script_utils
--- a/core/bin/script_utils
+++ b/core/bin/script_utils
@@ -244,11 +244,11 @@ show_version() {
 run_command() {
    local dry_run=$1
    local printed_cmd=$2
-   local cmd=( "${@:3}" )
+   local run_cmd=( "${@:3}" )
 
    # If the command to print has not been explicitly given, we print the one
    # being executed.
-   [ -z "$printed_cmd" ] && printed_cmd=${cmd[*]}
+   [ -z "$printed_cmd" ] && printed_cmd=${run_cmd[*]}
 
    if [ -n "$dry_run" ] && [ -z "$BE_QUIET" ]; then
       echo "Not running ==> $printed_cmd"
@@ -256,7 +256,7 @@ run_command() {
    fi
 
    [ -z "$BE_QUIET" ] && echo "Running ==> $printed_cmd"
-   "${cmd[@]}"
+   "${run_cmd[@]}"
 }
 
 
@@ -382,6 +382,9 @@ start_hub() {
 #   run_hubs [HUB[,ADDR]]...
 # Globals:
 #   r- HUB_LOG
+#   r- HUB_SOCKET_DIR
+#   r- HUB_SOCKET_EXTENSION
+#   r- HUB_SOCKET_PREFIX
 #   r- JUST_PRINT
 #   r- NETKIT_HOME
 #   r- USER_ID
@@ -395,6 +398,8 @@ start_hub() {
 ###############################################################################
 run_hubs() {
    local hub_specifications=( "$@" )
+
+   local hub_specification hub_name tap_address hub_socket
 
    for hub_specification in "${hub_specifications[@]}"; do
       IFS=, read -r hub_name tap_address <<< "$hub_specification"
@@ -410,14 +415,35 @@ run_hubs() {
 }
 
 
-# This function takes as argument a list of sockets used by virtual hubs, stops
-# those that are not used by any virtual machine and deletes the corresponding
-# sockets.
+###############################################################################
+# Stop and remove all unused virtual hubs.
+# Usage:
+#   run_hubs [HUB[,ADDR]]...
+# Globals:
+#   r- HUB_LOG
+#   r- HUB_SOCKET_DIR
+#   r- HUB_SOCKET_EXTENSION
+#   r- HUB_SOCKET_PREFIX
+#   r- JUST_PRINT
+#   r- NETKIT_HOME
+#   r- USER_ID
+# Arguments:
+#  ... - list of hub names optionally paired with an IP address (address goes
+#        unused but exists as an option if reusing a list used as input to
+#        run_hubs).
+# Returns:
+#   None
+# Example:
+#   None
+###############################################################################
 clean_hubs() {
    local hub_specifications=( "$@" )
 
+   local hub_specification hub_name hub_socket
+   local hub_pid
+
    for hub_specification in "${hub_specifications[@]}"; do
-      IFS=, read -r hub_name tap_address <<< "$hub_specification"
+      IFS=, read -r hub_name _ <<< "$hub_specification"
 
       hub_socket="$HUB_SOCKET_DIR/${HUB_SOCKET_PREFIX}_${USER_ID}_$hub_name$HUB_SOCKET_EXTENSION"
 
@@ -446,7 +472,7 @@ clean_hubs() {
 ###############################################################################
 # Remove the filesystem of a virtual machine.
 # Usage:
-#   remove_fs FILE
+#   rm_filesystem FILE
 # Globals:
 #   None
 # Arguments:
@@ -456,7 +482,7 @@ clean_hubs() {
 # Example:
 #   None
 ###############################################################################
-remove_fs() {
+rm_filesystem() {
    rm --verbose "$1"
 }
 
@@ -476,9 +502,9 @@ remove_fs() {
 #   None
 ###############################################################################
 get_machine_state() {
-   user=$1
-   name=$2
-   get_vm_pid_by_name "$user" "$name" > /dev/null
+   local target_user=$1
+   local vm=$2
+   get_vm_pid_by_name "$target_user" "$vm" > /dev/null
 }
 
 
@@ -497,16 +523,19 @@ get_machine_state() {
 #   None
 ###############################################################################
 get_vm_pid_by_name() {
-   user=$1
-   name=$2
+   local target_user=$1
+   local name=$2
 
-   [ -n "$user" ] && pgrep_euid="--euid"
+   local full_command_regex
+   local pid pgid full_command
+   local first_iteration argument umid
+
 
    # Quick filter for pgrep. It is not 100% accurate, returning multiple
    # instances if there is a machine called "foo" and "foo bar". We hence do
    # further processing - this filter just removes processes which definitely
    # are not matches.
-   full_command_regex="^$NETKIT_HOME/kernel/netkit-kernel.*[[:blank:]]umid=${name}(\$|[[:blank:]])"
+   full_command_regex="^$NETKIT_HOME/kernel/netkit-kernel.*[[:blank:]]umid=$name(\$|[[:blank:]])"
 
    # The process hierarchy looks like this:
    #
@@ -531,7 +560,7 @@ get_vm_pid_by_name() {
 
    # Iterate over the PIDs of running Netkit instances with name matches.
    # TODO: Sort out quoting of arguments
-   for pid in $(pgrep ${pgrep_euid:+"$pgrep_euid"} ${user:+"$user"} --full "$full_command_regex"); do
+   for pid in $(pgrep ${target_user:+"--euid=$target_user"} --full "$full_command_regex"); do
       # Get the process group ID (PGID)
       pgid=$(ps --no-headers --format pgid --pid "$pid")
 
@@ -584,23 +613,24 @@ get_vm_pid_by_name() {
 #   for pid in $(get_vm_all_pids_by_name "" "foobar"); do echo $pid; done
 ###############################################################################
 get_vm_all_pids_by_name() {
-   local vm_pids
+   local target_user=$1
+   local name=$2
 
-   user=$1
-   name=$2
+   local full_command_regex
+   local pid full_command
+   local first_iteration argument umid pids
 
-   [ -n "$user" ] && pgrep_euid="--euid"
 
    # Quick filter for pgrep. It is not 100% accurate, returning multiple
    # instances if there is a machine called "foo" and "foo bar". We hence do
    # further processing - this filter just removes processes which definitely
    # are not matches.
-   full_command_regex="^$NETKIT_HOME/kernel/netkit-kernel.*[[:blank:]]umid=${name}(\$|[[:blank:]])"
+   full_command_regex="^$NETKIT_HOME/kernel/netkit-kernel.*[[:blank:]]umid=$name(\$|[[:blank:]])"
 
    # See get_vm_pid_by_name for a process hierarchy explanation.
 
    # Iterate over the PIDs of running Netkit instances with name matches.
-   for pid in $(pgrep ${pgrep_euid:+"$pgrep_euid"} ${user:+"$user"} --full "$full_command_regex"); do
+   for pid in $(pgrep ${target_user:+"--euid=$target_user"} --full "$full_command_regex"); do
       # Full command used to invoke the process
       full_command=$(xargs -0 printf "%s\n" < "/proc/$pid/cmdline")
 
@@ -616,7 +646,7 @@ get_vm_all_pids_by_name() {
             umid=${argument#*=}
 
             if [ "$umid" = "$name" ]; then
-               vm_pids+=( "$pid" )
+               pids+=( "$pid" )
             fi
 
             break
@@ -624,9 +654,9 @@ get_vm_all_pids_by_name() {
       done <<< "$full_command"
    done
 
-   echo "${vm_pids[*]}"
+   echo "${pids[*]}"
 
-   [ "${#vm_pids[@]}" -gt 0 ] && return 0 || return 1
+   [ "${#pids[@]}" -gt 0 ] && return 0 || return 1
 }
 
 
@@ -636,6 +666,7 @@ get_vm_all_pids_by_name() {
 # Usage:
 #   get_vm_info_by_pid PID
 # Globals:
+#   r- MCONSOLE_DIR
 #   rw vm_info
 #   rw vm_uml_sockets
 # Arguments:
@@ -646,11 +677,12 @@ get_vm_all_pids_by_name() {
 #   None
 ###############################################################################
 get_vm_info_by_pid() {
-   local argument first_iteration key n pid uml_socket value
+   local pid=$1
 
-   pid=$1
+   local first_iteration argument value
+   local device device_id
 
-   # Unset the globals incase the
+   # Unset the globals
    unset vm_info
    unset vm_uml_sockets
 
@@ -674,6 +706,7 @@ get_vm_info_by_pid() {
    # present in a Linux filepath. This will still break if a newline is present
    # in the command, but if a user is doing that then they are just asking for
    # an error somewhere down the line to be honest.
+   # TODO: https://unix.stackexchange.com/a/658549
    vm_info["full_command"]=$(xargs -0 printf "%s\n" < "/proc/$pid/cmdline")
 
    first_iteration=true
@@ -684,26 +717,24 @@ get_vm_info_by_pid() {
          continue
       fi
 
-      # As per the manual, UML options are key=value pairs.
-      # ${argument#*=} removes the key= prefix from argument (the single #
-      # permits usage of further equals signs in the argument).
+      # UML options are key=value pairs. ${argument#*=} removes the key= prefix
+      # from argument (the single # permits usage of further equals signs in
+      # the argument).
+      value=${argument#*=}
 
       # Edge-cases that can only be matched with regular expressions (or with
       # extglob enabled, which cannot be done.)
       if [[ "$argument" =~ ^eth([0-9]|[1-9][0-9]+)=.*$ ]]; then
-         key=${argument%%=*}
-         value=${argument#*=}
-
          # Interface number
-         n=${key#eth}
+         device=${argument%%=*}
+         device_id=${device#eth}
 
-         # UML socket filepath (assuming transport mode is daemon)
-         uml_socket=${value#daemon,,,*}
-
-         # Array of UML sockets indexed by the interface number.
-         # Disable SC2034 check (unused variable) - it is used eslewhere.
+         # Array of UML socket filepaths indexed by the interface number.
+         # NOTE: we assume transport mode is 'daemon'
+         # Disable SC2034 check (unused variable) - it is used eslewhere as a
+         # global.
          # shellcheck disable=SC2034
-         vm_uml_sockets[$n]=$uml_socket
+         vm_uml_sockets[$device_id]=${value#daemon,,,}
          continue
       fi
 
@@ -711,7 +742,6 @@ get_vm_info_by_pid() {
       # matching:
       case $argument in
          con0=* )
-            value=${argument#*=}
             case $value in
                xterm)      vm_info["con0"]=$value;;
                fd:0,fd:1)  vm_info["con0"]="this";;
@@ -721,7 +751,6 @@ get_vm_info_by_pid() {
             esac
             ;;
          con1=*)
-            value=${argument#*=}
             case $value in
                xterm)      vm_info["con1"]=$value;;
                fd:0,fd:1)  vm_info["con1"]="this";;
@@ -730,18 +759,16 @@ get_vm_info_by_pid() {
                null)       vm_info["con1"]="none";;
             esac
             ;;
-         exec=*)     vm_info["boot_cmd"]=${argument#*=};;
-         hosthome=*) vm_info["hosthome"]=${argument#*=};;
-         hostlab=*)  vm_info["hostlab"]=${argument#*=};;
-         hostwd=*)   vm_info["hostwd"]=${argument#*=};;
+         exec=*)     vm_info["boot_cmd"]=$value;;
+         hosthome=*) vm_info["hosthome"]=$value;;
+         hostlab=*)  vm_info["hostlab"]=$value;;
+         hostwd=*)   vm_info["hostwd"]=$value;;
          # Memory is NOT adjusted by the skew here
-         mem=*)      vm_info["mem"]=${argument#*=};;
-         modules=*)  vm_info["modules"]=${argument#*=};;
-         name=*)     vm_info["name"]=${argument#*=};;
-         title=*)    vm_info["title"]=${argument#*=};;
+         mem=*)      vm_info["mem"]=$value;;
+         modules=*)  vm_info["modules"]=$value;;
+         name=*)     vm_info["name"]=$value;;
+         title=*)    vm_info["title"]=$value;;
          udb0=*)
-            value=${argument#*=}
-
             # The udb0 value is disk,fs or fs
             vm_info["disk"]=${value%%,*}
             vm_info["fs"]=${value#*,}
@@ -750,13 +777,13 @@ get_vm_info_by_pid() {
             # shared filesystem is used.
             [ "${vm_info["disk"]}" = "${vm_info["fs"]}" ] && unset vm_info["disk"]
             ;;
-         umid=*)     vm_info["umid"]=${argument#*=};;
-         *)          vm_info["other"]="${vm_info["$other"]} $argument"
+         umid=*)     vm_info["umid"]=$value;;
+         *)          vm_info["other"]="${vm_info[$other]} $argument"
       esac
-   done <<< "${vm_info["full_command"]}"
+   done <<< "${vm_info[full_command]}"
 
    # The UML console socket filepath
-   vm_info["mconsole"]="$MCONSOLE_DIR/${vm_info["umid"]}/mconsole"
+   vm_info["mconsole"]="$MCONSOLE_DIR/${vm_info[umid]}/mconsole"
 }
 
 
@@ -777,10 +804,12 @@ get_vm_info_by_pid() {
 #   None
 ###############################################################################
 get_vm_info_by_name() {
-   user=$1
-   vm=$2
+   local target_user=$1
+   local vm=$2
 
-   if ! pid=$(get_vm_pid_by_name "$user" "$vm"); then
+   local pid
+
+   if ! pid=$(get_vm_pid_by_name "$target_user" "$vm"); then
       return 1
    fi
 
@@ -789,15 +818,29 @@ get_vm_info_by_name() {
 }
 
 
-# This function creates a directory and sets global permissions for it.
-# If the directory already exists, an error is issued.
+###############################################################################
+# Create a directory with 777 permissions. If a file with the same path already
+# exists, an error is thrown.
+# Usage:
+#   netkit_dir_check DIR
+# Globals:
+#   None
+# Arguments:
+#   $1 - directory filepath
+# Returns:
+#   None. Function exits with non-zero code on failure.
+# Example:
+#   None
+###############################################################################
 netkit_dir_check() {
    local dir=$1
+
    if [ ! -e "$dir" ]; then
       mkdir "$dir"
+      # TODO: fix the sus directory permissions
       chmod 777 "$dir"
    elif [ ! -d "$dir" ]; then
-      echo 1>&2 "File '$1' exists: unable to create directory '$1'"
+      echo 1>&2 "File '$dir' exists: unable to create directory '$dir'"
       exit 1
    fi
 }
@@ -848,10 +891,11 @@ export LANG=C
 [ -n "$NETKIT_TERM" ] &&       TERM_TYPE=$NETKIT_TERM
 
 
+# Set the global USER_ID variable
+USER_ID=$(id -un)
+
+
 # Ensure critical directories exist
 netkit_dir_check "$HOME/.netkit"
 netkit_dir_check "$HUB_SOCKET_DIR"
 netkit_dir_check "$MCONSOLE_DIR"
-
-
-USER_ID=$(id -un)
diff --git a/core/bin/vclean b/core/bin/vclean
--- a/core/bin/vclean
+++ b/core/bin/vclean
@@ -125,28 +125,30 @@ END_OF_HELP
 ###############################################################################
 # Kill all running VMs.
 # Usage:
-#   kill_all_vms USER
+#   kill_all_vms TEST_MODE USER
 # Globals:
 #   r- BE_QUIET
 #   r- NETKIT_HOME
-#   r- TEST_MODE
 # Arguments:
-#   $1 - owner of the machines; pass an empty string for all users
+#   $1 - set to 1 for test mode, empty string otherwise
+#   $2 - owner of the machines; pass an empty string for all users
 # Returns:
 #   None. Returns early on test mode (only outputs PIDs without killing them).
 # Example:
 #   None
 ###############################################################################
 kill_all_vms() {
-   local user=$1
-   [ -n "$user" ] && pgrep_euid="--euid"
+   local test_mode=$1
+   local target_user=$2
 
-   mapfile -t pids < <(pgrep "${pgrep_euid:+$pgrep_euid}" "${user:+$user}" --full "^$NETKIT_HOME/kernel/netkit-kernel[[:blank:]]")
+   local pids
+
+   mapfile -t pids < <(pgrep ${target_user:+"--euid=$target_user"} --full "^$NETKIT_HOME/kernel/netkit-kernel[[:blank:]]")
 
    [ -z "$BE_QUIET" ] && echo "   PIDs: ${pids[*]}"
 
    # We are in test mode, just show which processes would be killed
-   [ -n "$TEST_MODE" ] && return
+   [ -n "$test_mode" ] && return
 
    if [ -z "$BE_QUIET" ]; then
       echo -n "   Killing... "
@@ -157,7 +159,7 @@ kill_all_vms() {
       kill -TERM "${pids[@]}"
 
       sleep 1
-      mapfile -t pids < <(pgrep "${pgrep_euid:+$pgrep_euid}" "${user:+$user}" --full "^$NETKIT_HOME/kernel/netkit-kernel[[:blank:]]")
+      mapfile -t pids < <(pgrep ${target_user:+"--euid=$target_user"} --full "^$NETKIT_HOME/kernel/netkit-kernel[[:blank:]]")
 
       if [ "${#pids[@]}" -gt 0 ]; then
          echo -n "killing harder... "
@@ -166,7 +168,7 @@ kill_all_vms() {
          kill -CONT "${pids[@]}"
 
          sleep 1
-         mapfile -t pids < <(pgrep "${pgrep_euid:+$pgrep_euid}" "${user:+$user}" --full "^$NETKIT_HOME/kernel/netkit-kernel[[:blank:]]")
+         mapfile -t pids < <(pgrep ${target_user:+"--euid=$target_user"} --full "^$NETKIT_HOME/kernel/netkit-kernel[[:blank:]]")
 
          if [ "${#pids[@]}" -gt 0 ]; then
             echo "failed!"
@@ -187,13 +189,13 @@ kill_all_vms() {
 ###############################################################################
 # Kill unused hubs by process ID and remove their socket files.
 # Usage:
-#   kill_hubs FORCE [PID]...
+#   kill_hubs FORCE TEST_MODE [PID]...
 # Globals:
 #   r- BE_QUIET
-#   r- TEST_MODE
 # Arguments:
 #   $1 - set to 1 to kill and remove hubs even if being used, otherwise pass an
 #        empty string.
+#   $2 - set to 1 for test mode, empty string otherwise
 #  ... - the process IDs of the virtual hubs to clean up.
 # Returns:
 #   None
@@ -201,18 +203,18 @@ kill_all_vms() {
 #   None
 ###############################################################################
 kill_hubs() {
-   local uml_switch_cmd
-   local hub_pid hub_file found_unused_hub
-
    local force=$1
-   shift
-
-   local hub_pids=( "$@" )
+   local test_mode=$2
+   local hub_pids=( "${@:3}" )
+   
+   local hub_pid hub_file
+   local uml_switch_cmd
+   local found_unused_hub   
 
    for hub_pid in "${hub_pids[@]}"; do
       # Safely extract the socket filename from argv.
       # NOTE: we assume the final command line argument is the socket filename.
-      mapfile -d "" uml_switch_cmd < "/proc/$hub_pid/cmdline"
+      mapfile -d "" -t uml_switch_cmd < "/proc/$hub_pid/cmdline"
       hub_file=${uml_switch_cmd[-1]}
 
       if [ -n "$force" ] || [ "$(lsof -a -U -p "$hub_pid" -Fn | grep -c "^n$hub_file")" -le 1 ]; then
@@ -222,7 +224,7 @@ kill_hubs() {
 
          [ -z "$BE_QUIET" ] && echo -n "   $hub_file (PID $hub_pid)"
 
-         if [ -z "$TEST_MODE" ]; then
+         if [ -z "$test_mode" ]; then
             echo -n ": Killing... "
             kill "$hub_pid" && rm "$hub_file"
             echo -n "done."
@@ -232,7 +234,7 @@ kill_hubs() {
       fi
    done
 
-   [ -n "$found_unused_hub" ] && [ -z "$BE_QUIET" ] && echo "   No unused virtual hubs have been found."
+   [ -z "$found_unused_hub" ] && [ -z "$BE_QUIET" ] && echo "   No unused virtual hubs have been found."
 }
 
 
@@ -268,27 +270,27 @@ eval set -- "$getopt_opts"
 while true; do
    case $1 in
       --clean-all)
-         KILL_MACHINES=1
-         REMOVE_TUNNELS=1
+         kill_machines=1
+         remove_tunnels=1
          ;;
       -H|--remove-hubs)
-         REMOVE_UNUSED_HUBS=1
+         remove_hubs=1
          ;;
       --help)
          usage 0
          ;;
       -K|--kill-machines)
-         KILL_MACHINES=1
+         kill_machines=1
          ;;
       # TODO: Separate options (and use --verbose)
       -q|--quick|--quiet)
          BE_QUIET=1
          ;;
       -T|--remove-tunnels)
-         REMOVE_TUNNELS=1
+         remove_tunnels=1
          ;;
       --test)
-         TEST_MODE=1
+         test_mode=1
          ;;
       --user|-u)
          target_user=$2
@@ -321,82 +323,80 @@ fi
 
 
 # Test mode is senseless if working in quiet mode
-if [ -n "$TEST_MODE" ] && [ -n "$BE_QUIET" ]; then
+if [ -n "$test_mode" ] && [ -n "$BE_QUIET" ]; then
    echo 1>&2 "$SCRIPTNAME: test mode cannot function in quiet mode"
    exit 1
 fi
 
 # Actions --remove-hubs and --kill-machines are incompatible
-if [ -n "$REMOVE_UNUSED_HUBS" ] && [ -n "$KILL_MACHINES" ]; then
+if [ -n "$remove_hubs" ] && [ -n "$kill_machines" ]; then
    echo 1>&2 "$SCRIPTNAME: Hub removal and machine kill cannot be performed simultaneously"
    exit 1
 fi
 
 # Enable default action (remove unused virtual hubs) if none has been requested
-if [ -z "$KILL_MACHINES" ] && [ -z "$REMOVE_TUNNELS" ]; then
-   REMOVE_UNUSED_HUBS=1
+if [ -z "$kill_machines" ] && [ -z "$remove_tunnels" ]; then
+   remove_hubs=1
 fi
 
 
 if [ -z "$target_user" ]; then
-   USER_STRING="all users"
+   user_str="all users"
 else
-   # We need the euid option for pgrep to filter by user
-   pgrep_euid="--euid"
-   USER_STRING=$target_user
+   user_str=$target_user
 fi
 
 
 # Remove unused hubs (if asked to)
-if [ -n "$REMOVE_UNUSED_HUBS" ]; then
+if [ -n "$remove_hubs" ]; then
    # Just remove unused switches
-   [ -z "$BE_QUIET" ] && echo "Killing unusued virtual hubs owned by $USER_STRING:"
+   [ -z "$BE_QUIET" ] && echo "Killing unusued virtual hubs owned by $user_str:"
 
    # Get the process IDs of running UML virtual hubs
-   mapfile -t hub_pids < <(pgrep "${pgrep_euid:+$pgrep_euid}" "${user:+$user}" --full "^$NETKIT_HOME/bin/uml_switch")
+   mapfile -t hub_pids < <(pgrep ${target_user:+"--euid=$target_user"} --full "^$NETKIT_HOME/bin/uml_switch")
 
-   # Kill uml_switch processes and clean up hub files
-   kill_hubs "" "${hub_pids[@]}"
+   # Kill uml_switch processes and clean up unused hub files
+   kill_hubs "" "$test_mode" "${hub_pids[@]}"
 fi
 
 
 # Kill running virtual machines and hubs (if asked to)
-if [ -n "$KILL_MACHINES" ]; then
+if [ -n "$kill_machines" ]; then
    # Kill all running virtual machine kernels and all virtual hubs
-   [ -z "$BE_QUIET" ] && echo "Killing virtual machines owned by $USER_STRING:"
+   [ -z "$BE_QUIET" ] && echo "Killing virtual machines owned by $user_str:"
 
-   kill_all_vms "$target_user"
+   kill_all_vms "$test_mode" "$target_user"
 
-   [ -z "$BE_QUIET" ] && echo "Killing virtual hubs owned by $USER_STRING:"
+   [ -z "$BE_QUIET" ] && echo "Killing virtual hubs owned by $user_str:"
 
    # Get the process IDs of running UML virtual hubs
-   mapfile -t hub_pids < <(pgrep "${pgrep_euid:+$pgrep_euid}" "${user:+$user}" --full "^$NETKIT_HOME/bin/uml_switch")
+   mapfile -t hub_pids < <(pgrep ${target_user:+"--euid=$target_user"} --full "^$NETKIT_HOME/bin/uml_switch")
 
-   # Kill uml_switch processes and clean up hub files
-   kill_hubs "1" "${hub_pids[@]}"
+   # Kill uml_switch processes and clean up all hub files
+   kill_hubs "1" "$test_mode" "${hub_pids[@]}"
 fi
 
 
 # Remove tunnel configurations (if asked to)
-if [ -n "$REMOVE_TUNNELS" ]; then
+if [ -n "$remove_tunnels" ]; then
    # Remove any previously configured tunnel
    if [ -z "$BE_QUIET" ]; then
       echo "************* Removing tap configurations *************"
-      echo " This will affect tap configurations for $USER_STRING."
+      echo " This will affect tap configurations for $user_str."
       echo "******* This operation requires root privileges *******"
    fi
 
    # TODO: These commands don't run for the specified user (this is a
    # manage_tuntap limitation). 
-   TUNTAP_COMMAND=( "$NETKIT_HOME/bin/manage_tuntap" "stop" )
+   manage_tuntap_cmd=( "$NETKIT_HOME/bin/manage_tuntap" "stop" )
 
    if [ -z "$BE_QUIET" ]; then   
-      if ! run_command "" "${TUNTAP_COMMAND[*]}" "${TUNTAP_COMMAND[@]}"; then
+      if ! run_command "" "${manage_tuntap_cmd[*]}" "${manage_tuntap_cmd[@]}"; then
          echo 1>&2 "Error while removing tap configurations"
          exit 1
       fi
    else
-      if ! run_command "" "${TUNTAP_COMMAND[*]}" "${TUNTAP_COMMAND[@]}" > /dev/null; then
+      if ! run_command "" "${manage_tuntap_cmd[*]}" "${manage_tuntap_cmd[@]}" > /dev/null; then
          echo 1>&2 "Error while removing tap configurations"
          exit 1
       fi
diff --git a/core/bin/vconf b/core/bin/vconf
--- a/core/bin/vconf
+++ b/core/bin/vconf
@@ -131,7 +131,7 @@ END_OF_HELP
 #   setup_interfaces [INTERFACE]...
 # Globals:
 #   r- BE_QUIET
-#   -w HUBLIST
+#   -w HUB_LIST
 #   r- HUB_SOCKET_DIR
 #   r- HUB_SOCKET_EXTENSION
 #   r- HUB_SOCKET_PREFIX
@@ -146,12 +146,12 @@ END_OF_HELP
 #   None
 ###############################################################################
 setup_interfaces() {
-   local interface_specification interface_specifications
-   local device hub_name hub_socket tap_address
-   local guest_address used_devices
-   local first_iteration
+   local interface_specifications=( "$@" )
 
-   interface_specifications=( "$@" )
+   local first_iteration
+   local interface_specification device hub_specification used_devices
+   local hub_name tap_address guest_address hub_socket
+   
 
    first_iteration=true
    for interface_specification in "${interface_specifications[@]}"; do
@@ -159,13 +159,14 @@ setup_interfaces() {
       hub_specification=${interface_specification#*=}
 
       # Check if interface has already been configured
-      if [[ " $used_devices " == *" $device "* ]]; then
+      # TODO: is this check really necessary?
+      if array_contains "$device" "${used_devices[@]}"; then
          echo 1>&2 "$SCRIPTNAME: $device: Duplicate interface"
          usage 1
       fi
 
       # Remember that this network interface has been configured
-      used_devices="$used_devices $device"
+      used_devices+=( "$device" )
 
       # Check if tap interface (regular hubs cannot be named with commas)
       if [[ "$hub_specification" == tap,* ]]; then
@@ -187,12 +188,13 @@ setup_interfaces() {
          hub_name=$hub_specification
       fi
       
+      # TODO: should USER_ID or target_user be used here?
       hub_socket="$HUB_SOCKET_DIR/${HUB_SOCKET_PREFIX}_${USER_ID}_$hub_name$HUB_SOCKET_EXTENSION"
 
       if [ -n "$tap_address" ]; then
-         HUBLIST+=( "$hub_name,$tap_address" )
+         HUB_LIST+=( "$hub_name,$tap_address" )
       elif [ -n "$hub_name" ]; then
-         HUBLIST+=( "$hub_name" )
+         HUB_LIST+=( "$hub_name" )
       fi
 
       if $first_iteration; then
@@ -215,21 +217,26 @@ setup_interfaces() {
 ###############################################################################
 # Attach/remove network interfaces from running machines with mconsole.
 # Usage:
-#   invoke_mconsole MCONSOLE_CMD
+#   invoke_mconsole MACHINE [MCONSOLE_CMD]...
 # Globals:
+#   r- JUST_PRINT
 #   r- NETKIT_HOME
-#   r- VM_ID
 # Arguments:
-#   $1 - list of mconsole commands
+#   $1 - machine name
+#  ... - list of mconsole commands. To remove an interface: 'ethN', to add an
+#        interface: 'ethN=daemon,,,path/to/socket'.
 # Returns:
 #   None
 # Example:
 #   None
 ###############################################################################
 invoke_mconsole() {
-   local action action_desc arg device hub_specification mconsole_cmd
+   local vm=$1
+   local mconsole_cmd=( "${@:2}" )
 
-   mconsole_cmd=( "$@" )
+   local arg device hub_specification
+   local action action_desc
+
 
    for arg in "${mconsole_cmd[@]}"; do
       # Format is either:
@@ -248,7 +255,7 @@ invoke_mconsole() {
          action_desc="remove"
       fi
 
-      if ! run_command "$JUST_PRINT" "" "$NETKIT_HOME/bin/uml_mconsole" "$VM_ID" "$action" "$device" 2>&1; then
+      if ! run_command "$JUST_PRINT" "" "$NETKIT_HOME/bin/uml_mconsole" "$vm" "$action" "$device" 2>&1; then
          echo 2>&1 "Failed to $action_desc interface '$device'"
       fi
    done
@@ -276,10 +283,9 @@ target_user=$USER_ID
 long_opts="help,print,quiet,version,user:"
 short_opts="pqu:"
 
-i=0
-while [ "$i" -lt "$MAX_INTERFACES" ]; do
-   long_opts="$long_opts,eth$i:"
-   i=$((i + 1))
+# Append a new long option for each network interface that can be configured
+for ((i = 0; i < MAX_INTERFACES; ++i)); do
+   long_opts+=",eth$i:"
 done
 
 if ! getopt_opts=$(getopt --name "$SCRIPTNAME" --options "$short_opts" --longoptions "$long_opts" -- "$@"); then
@@ -293,30 +299,28 @@ eval set -- "$getopt_opts"
 while true; do
    case $1 in
       --eth*)
-         interface=${1#--}
-         DOMAIN=$2
+         device=${1#--}
+         hub_name=$2
          shift
 
-         if string_contains "_" "$DOMAIN"; then
-            echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - underscores are not allowed"
-            usage 1
-         fi
+         # Check if tap interface (regular hubs cannot be named with commas)
+         if [[ "$hub_name" == tap,* ]]; then
+            # Format: tap,tap_address,guest_address
+            IFS=, read -r _ tap_address guest_address <<< "$hub_name"
 
-         if string_contains "," "$DOMAIN" || string_contains "." "$DOMAIN"; then
-            # If not a tap specification, but its name contains a comma
-            if [ "${DOMAIN#tap,}" = "$DOMAIN" ]; then
-               echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - commas and periods are only valid for tap interface specification"
+            if ! is_inet_addr "$tap_address"; then
+               echo 1>&2 "$SCRIPTNAME: $tap_address: Invalid tap address"
+               usage 1
+            fi
+
+            if ! is_inet_addr "$guest_address"; then
+               echo 1>&2 "$SCRIPTNAME: $guest_address: Invalid guest address"
                usage 1
             fi
          fi
 
-         if string_contains " " "$DOMAIN"; then
-            echo 1>&2 "$SCRIPTNAME: $DOMAIN: Collision domain name cannot contain whitespace"
-            exit 1
-         fi
-
-         # Construct array of ethN=DOMAIN
-         network_interfaces+=( "$interface=$DOMAIN" )
+         # Construct array of ethN=hub_name
+         network_interfaces+=( "$device=$hub_name" )
          ;;
       --help)
          usage 0
@@ -358,17 +362,17 @@ elif [ $# -gt 1 ]; then
    usage 1
 fi
 
-VM_ID=$1
+vm=$1
 shift
 
-if string_contains " " "$VM_ID"; then
+if string_contains " " "$vm"; then
    echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
    exit 1
 fi
 
 
-if ! get_machine_state "$target_user" "$VM_ID"; then
-   echo -n 1>&2 "$SCRIPTNAME: no virtual machine named '$VM_ID' exists"
+if ! get_machine_state "$target_user" "$vm"; then
+   echo -n 1>&2 "$SCRIPTNAME: no virtual machine named '$vm' exists"
    [ -n "$target_user" ] && echo " for user $target_user." || echo "."
    exit 1
 fi
@@ -376,7 +380,7 @@ fi
 
 # Setup network interfaces
 if [ -z "$BE_QUIET" ]; then
-   echo "============= Configuring virtual machine '$VM_ID' (PID $(get_vm_pid_by_name "$user" "$vm")) ============="
+   echo "============= Configuring virtual machine '$vm' (PID $(get_vm_pid_by_name "$target_user" "$vm")) ============="
    echo "   Virtual machine owner: $target_user"
 fi
 
@@ -386,7 +390,7 @@ if [ ${#network_interfaces[@]} -gt 0 ]; then
 fi
 
 # Start network hubs
-run_hubs "${HUBLIST[@]}"
+run_hubs "${HUB_LIST[@]}"
 
 # Attach/remove network interfaces
-invoke_mconsole "${MCONSOLE_CMD[@]}"
+invoke_mconsole "$vm" "${MCONSOLE_CMD[@]}"
diff --git a/core/bin/vconnect b/core/bin/vconnect
--- a/core/bin/vconnect
+++ b/core/bin/vconnect
@@ -15,7 +15,7 @@
 #   None
 ###############################################################################
 usage_line() {
-   echo "Usage: $SCRIPTNAME [OPTION]..."
+   echo "Usage: $SCRIPTNAME [OPTION]... MACHINE"
 }
 
 
@@ -45,13 +45,12 @@ usage() {
 
    cat << END_OF_HELP
 $(usage_line)
-Connect to the tmux session of a Netkit virtual machine.
+Connect to the tmux session of a Netkit MACHINE.
 
   -l, --list          list all running sessions on the tmux 'netkit' server
   -t, --terminal      connect to the tmux session from a new terminal. The
                         terminal opened is dependent on the TERM_TYPE set in
                         netkit.conf
-  -m, --machine=MACHINE  name of the machine to connect to
   -r, --retry-count=N  number of times to attempt to connect to a tmux session
   -n, --interval=N    sleep duration between attempts to connect to a tmux
                         session
@@ -98,7 +97,9 @@ tmux_connect() {
 #   None
 ###############################################################################
 open_terminal() {
-   vm=$1
+   local vm=$1
+
+   local term_cmd
 
    case $TERM_TYPE in
       alacritty)     term_cmd=( "alacritty" "-e" );;
@@ -128,8 +129,8 @@ fi
 . "$NETKIT_HOME/bin/script_utils"
 
 
-RETRY_COUNT=1
-RETRY_INTERVAL=5
+retry_count=1
+retry_interval=5
 
 # Allow nesting of tmux sessions
 unset TMUX
@@ -153,22 +154,18 @@ while true; do
          usage 0
          ;;
       -l|--list)
-         LIST_ONLY=1
-         ;;
-      -m|--machine)
-         MACHINE_NAME=$2
-         shift
+         list_only=1
          ;;
       -n|--interval)
-         RETRY_INTERVAL=$2
+         retry_interval=$2
          shift
          ;;
       -r|--retry-count)
-         RETRY_COUNT=$2
+         retry_count=$2
          shift
          ;;
       -t|--terminal)
-         OPEN_TERM=1
+         open_term=1
          ;;
       --version)
          show_version
@@ -187,33 +184,50 @@ while true; do
    shift
 done
 
+# Parse virtual machine name
+if [ $# -eq 0 ]; then
+   echo 1>&2 "$SCRIPTNAME: Missing machine name"
+   usage 1
+elif [ $# -gt 1 ]; then
+   echo 1>&2 "$SCRIPTNAME: Can only specify one machine"
+   usage 1
+fi
+
+vm=$1
+shift
+
+if string_contains " " "$vm"; then
+   echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+   exit 1
+fi
+
 
 # Do not connect to the tmux session, just list available ones.
-if [ -n "$LIST_ONLY" ]; then
+if [ -n "$list_only" ]; then
    tmux -L netkit list-sessions
    exit 0
 fi
 
 
-echo -n "Connecting to '$MACHINE_NAME'."
+echo -n "Connecting to '$vm'."
 
-# Test that the tmux session exists RETRY_COUNT number of times.
-ATTEMPTS=0
-while ! tmux -L netkit has-session -t="$MACHINE_NAME" 2> /dev/null; do
-   ATTEMPTS=$((ATTEMPTS + 1))
+# Test that the tmux session exists retry_count number of times.
+attempts=0
+while ! tmux -L netkit has-session -t="$vm" 2> /dev/null; do
+   ((++attempts))
 
-   if [ "$ATTEMPTS" -eq "$RETRY_COUNT" ]; then
+   if [ "$attempts" -eq "$retry_count" ]; then
       echo
-      echo 1>&2 "Could not connect to '$MACHINE_NAME'."
+      echo 1>&2 "Could not connect to '$vm'."
       exit 1
    fi
 
-   sleep "$RETRY_INTERVAL"
+   sleep "$retry_interval"
    echo -n "."
 done
 
-if [ -n "$OPEN_TERM" ]; then
-   open_terminal "$MACHINE_NAME"
+if [ -n "$open_term" ]; then
+   open_terminal "$vm"
 else
-   tmux_connect "$MACHINE_NAME"
+   tmux_connect "$vm"
 fi
