rename vm variable to vhost

diff --git a/core/bin/lcommon b/core/bin/lcommon
--- a/core/bin/lcommon
+++ b/core/bin/lcommon
@@ -394,14 +394,14 @@ lab_crash() {
 single_lab_vm_start() {
    local fast_mode=$1
    local lab_directory=$2
-   local vm=$3
+   local vhost=$3
    local passthrough_args=( "${@:4}" )
 
    local configuration option value
 
    # Add host lab and working directory, and place filesystem inside the lab
    # directory.
-   local vstart_args=( "--hostlab" "$lab_directory" "--hostwd" "$PWD" "--filesystem" "$lab_directory/$vm.disk" )
+   local vstart_args=( "--hostlab" "$lab_directory" "--hostwd" "$PWD" "--filesystem" "$lab_directory/$vhost.disk" )
 
    # Generate vstart argument list
    if [ -e "$lab_directory/lab.conf" ]; then
@@ -428,30 +428,30 @@ single_lab_vm_start() {
          # appending the argument must be made (an '=' is required for long
          # options, no delimiter for short ones).
          [ -n "$value" ] && vstart_args+=( "$value" )
-      done < <(grep "^[[:blank:]]*$vm\[.*\][[:blank:]]*=" "$lab_directory/lab.conf")
+      done < <(grep "^[[:blank:]]*$vhost\[.*\][[:blank:]]*=" "$lab_directory/lab.conf")
    fi
    
    # Remove .ready file, if existing
-   [ -e "$lab_directory/$vm.ready" ] && rm -f "$lab_directory/$vm.ready"
+   rm -f "$lab_directory/$vhost.ready"
 
    if [ -z "$VERBOSE" ]; then
-      bold_print "Starting '$vm'..."
+      bold_print "Starting '$vhost'..."
    else
-      bold_print "Starting '$vm' with options '${vstart_args[*]} ${passthrough_args[*]}'... "
+      bold_print "Starting '$vhost' with options '${vstart_args[*]} ${passthrough_args[*]}'... "
    fi
 
-   if ! vstart "${vstart_args[@]}" "${passthrough_args[@]}" "$vm"; then
-      echo 2>&1 "Error while starting virtual machine '$vm'"
+   if ! vstart "${vstart_args[@]}" "${passthrough_args[@]}" "$vhost"; then
+      echo 2>&1 "Error while starting virtual machine '$vhost'"
       exit 1
    fi
 
    # Wait for virtual host startup script to create .ready file
    if [ -z "$fast_mode" ]; then
-      while [ ! -e "$lab_directory/$vm.ready" ]; do
+      while [ ! -e "$lab_directory/$vhost.ready" ]; do
          sleep 1
       done
 
-      rm -f "$lab_directory/$vm.ready"
+      rm -f "$lab_directory/$vhost.ready"
    fi
    
    # Wait for a specified amount of time before returning
@@ -495,7 +495,6 @@ lab_start() {
    # We prepend so passthrough_args can override 
    [ -z "$VERBOSE" ] && passthrough_args=( "-q" "${passthrough_args[@]}" )
 
-   # TODO: global rename of vhost to vm? Or vice-versa
    for vhost in "${VHOSTLIST[@]}"; do
       single_lab_vm_start "$fast_mode" "$lab_directory" "$vhost" "${passthrough_args[@]}"
    done
@@ -623,7 +622,7 @@ EOF
 generate_dot_graph() {
    local lab_confs=( "$@" )
 
-   local configuration vm option value
+   local configuration vhost option value
    local hub_name hub_names
 
    declare -A device_ids options
@@ -641,23 +640,23 @@ EOF
       # The [][] is ][ inside a bracket expression to match an opening or
       # closing square bracket. We know the machine name cannot contain
       # square brackets, so the option is the first instance of them.
-      vm=$(awk -F"[][]" '{ print $1 }' <<< "$configuration")
+      vhost=$(awk -F"[][]" '{ print $1 }' <<< "$configuration")
       option=$(awk -F"[][]" '{ print $2 }' <<< "$configuration")
 
       # Everything after the first '='
       value=${configuration#*=}
 
       # Ignore if VM is not part of the lab
-      array_contains "$vm" "${VHOSTLIST[@]}" || continue
+      array_contains "$vhost" "${VHOSTLIST[@]}" || continue
 
       # If option is all-digit, it must be a network interface specification
       if [[ "$option" =~ ^([0-9]|[1-9][0-9]+)$ ]]; then
          # Ignore if it has already been seen
-         [[ "${device_ids[$vm]}" =~ \ $option\  ]] && continue
+         [[ "${device_ids[$vhost]}" =~ \ $option\  ]] && continue
 
          # Add an edge between the machine and its collision domain
          cat << EOF
-   "$vm" -- "$value" [
+   "$vhost" -- "$value" [
       taillabel=<
          <TABLE BGCOLOR="white" BORDER="0" CELLPADDING="1" CELLSPACING="0">
             <TR>
@@ -674,23 +673,23 @@ EOF
 
          # Device IDs cannot have whitespace, so a space-separated list is
          # safe.
-         device_ids[$vm]+=" $option "
+         device_ids[$vhost]+=" $option "
       else
-         options[$vm]+="$option = $value<BR/>"
+         options[$vhost]+="$option = $value<BR/>"
       fi
    done < <(grep --no-filename "^[[:blank:]].*\[.*\][[:blank:]]*=" "${lab_confs[@]}")
    # TODO: Replace .* in above grep (and any other similar search) with the
    # hostname regex.
 
    # Label each machine with its hostname and vstart options
-   for vm in "${VHOSTLIST[@]}"; do
+   for vhost in "${VHOSTLIST[@]}"; do
       cat << EOF
-   "$vm" [
+   "$vhost" [
       shape=box,
       label=<
-         $vm
+         $vhost
          <FONT POINT-SIZE="10">
-            <BR/>${options[$vm]}
+            <BR/>${options[$vhost]}
          </FONT>
       >,
       height=0.5,
diff --git a/core/bin/vconnect b/core/bin/vconnect
--- a/core/bin/vconnect
+++ b/core/bin/vconnect
@@ -97,7 +97,7 @@ tmux_connect() {
 #   None
 ###############################################################################
 open_terminal() {
-   local vm=$1
+   local vhost=$1
 
    local term_cmd
 
@@ -114,7 +114,7 @@ open_terminal() {
          term_cmd=( "xterm" "-e" );;
    esac
    
-   nohup "${term_cmd[@]}" tmux -L netkit attach -t "$vm" > /dev/null 2>&1 &
+   nohup "${term_cmd[@]}" tmux -L netkit attach -t "$vhost" > /dev/null 2>&1 &
 }
 
 
@@ -193,8 +193,8 @@ elif [ $# -gt 1 ]; then
    usage 1
 fi
 
-vm=$1
-validate_hostnames "$vm"
+vhost=$1
+validate_hostnames "$vhost"
 
 
 # Do not connect to the tmux session, just list available ones.
@@ -204,16 +204,16 @@ if [ -n "$list_only" ]; then
 fi
 
 
-echo -n "Connecting to '$vm'."
+echo -n "Connecting to '$vhost'."
 
 # Test that the tmux session exists retry_count number of times.
 attempts=0
-while ! tmux -L netkit has-session -t="$vm" 2> /dev/null; do
+while ! tmux -L netkit has-session -t="$vhost" 2> /dev/null; do
    ((++attempts))
 
    if [ "$attempts" -eq "$retry_count" ]; then
       echo
-      echo 1>&2 "Could not connect to '$vm'."
+      echo 1>&2 "Could not connect to '$vhost'."
       exit 1
    fi
 
@@ -222,7 +222,7 @@ while ! tmux -L netkit has-session -t="$vm" 2> /dev/null; do
 done
 
 if [ -n "$open_term" ]; then
-   open_terminal "$vm"
+   open_terminal "$vhost"
 else
-   tmux_connect "$vm"
+   tmux_connect "$vhost"
 fi
diff --git a/core/bin/vcrash b/core/bin/vcrash
--- a/core/bin/vcrash
+++ b/core/bin/vcrash
@@ -134,7 +134,7 @@ END_OF_HELP
 ###############################################################################
 kill_by_signaling() {
    local target_user=$1
-   local vm=$2
+   local vhost=$2
 
    local pids
 
@@ -142,7 +142,7 @@ kill_by_signaling() {
 
    # Signalling processes twice ensures they stop even if they need to be
    # killed in a certain order
-   IFS=" " read -r -a pids <<< "$(get_vm_all_pids_by_name "$target_user" "$vm")"
+   IFS=" " read -r -a pids <<< "$(get_vm_all_pids_by_name "$target_user" "$vhost")"
 
    if [ "${#pids[@]}" -eq 0 ]; then
       kill -TERM "${pids[@]}" > /dev/null
@@ -152,11 +152,11 @@ kill_by_signaling() {
    if [ -z "$BE_QUIET" ]; then
       sleep 1
 
-      if get_machine_state "$target_user" "$vm"; then
+      if get_machine_state "$target_user" "$vhost"; then
          [ -z "$BE_QUIET" ] && echo -n "killing harder... "
          # Recompute PID list (some threads may have been launched in the
          # meantime).
-         IFS=" " read -r -a pids <<< "$(get_vm_all_pids_by_name "$target_user" "$vm")"
+         IFS=" " read -r -a pids <<< "$(get_vm_all_pids_by_name "$target_user" "$vhost")"
 
          if [ "${#pids[@]}" -eq 0 ]; then
             kill -KILL "${pids[@]}" > /dev/null
@@ -165,9 +165,9 @@ kill_by_signaling() {
 
          sleep 1
 
-         if get_machine_state "$target_user" "$vm"; then
+         if get_machine_state "$target_user" "$vhost"; then
             [ -z "$BE_QUIET" ] && echo "failed!"
-            echo 1>&2 "Failed to crash virtual machine '$vm'"
+            echo 1>&2 "Failed to crash virtual machine '$vhost'"
             return 1
          fi
       fi
@@ -235,7 +235,7 @@ mconsole_halt() {
 kill_by_mconsole() {
    local mconsole=$1
    local target_user=$2
-   local vm=$3
+   local vhost=$3
 
    [ -z "$BE_QUIET" ] && echo -n "Crashing... "
 
@@ -244,7 +244,7 @@ kill_by_mconsole() {
    # When the above command exits, an attempt via the mconsole has been
    # performed. Regardless of whether the virtual machine has actually halted,
    # the above command ensures that the uml_mconsole process has ended.
-   if [ -z "$BE_QUIET" ] && get_machine_state "$target_user" "$vm"; then
+   if [ -z "$BE_QUIET" ] && get_machine_state "$target_user" "$vhost"; then
       # Make a second attempt if machine is still running
       echo -n "retrying... "
       sleep 1
@@ -351,27 +351,27 @@ if [ -n "$test_mode" ] && [ -n "$BE_QUIET" ]; then
 fi
 
 
-for vm in "${vm_ids[@]}"; do
+for vhost in "${vm_ids[@]}"; do
    # Check whether the current machine exists
-   if get_machine_state "$target_user" "$vm"; then
-      get_vm_info_by_name "$target_user" "$vm"
+   if get_machine_state "$target_user" "$vhost"; then
+      get_vm_info_by_name "$target_user" "$vhost"
 
       if [ -z "$BE_QUIET" ]; then
-         echo "============= Crashing virtual machine '$vm' (PID ${vm_info[pid]}) ========="
+         echo "============= Crashing virtual machine '$vhost' (PID ${vm_info[pid]}) ========="
          echo "Virtual machine owner: $target_user"
          echo "Virtual machine mconsole socket: ${vm_info[mconsole]}"
-         echo "Virtual machine PIDs: $(get_vm_all_pids_by_name "$target_user" "$vm")"
+         echo "Virtual machine PIDs: $(get_vm_all_pids_by_name "$target_user" "$vhost")"
       fi
    
       [ -n "$test_mode" ] && continue
 
       if [ -n "$force" ]; then
          # Crash virtual machines by simply killing their processes
-         kill_by_signaling "$target_user" "$vm" || continue
+         kill_by_signaling "$target_user" "$vhost" || continue
       else
          # Crash virtual machines via uml_mconsole
-         if ! kill_by_mconsole "${vm_info[mconsole]}" "$target_user" "$vm"; then
-            kill_by_signaling "$target_user" "$vm" || continue
+         if ! kill_by_mconsole "${vm_info[mconsole]}" "$target_user" "$vhost"; then
+            kill_by_signaling "$target_user" "$vhost" || continue
          fi
       fi
 
@@ -379,11 +379,11 @@ for vm in "${vm_ids[@]}"; do
       # successfully shut down (if the previous commands returned 0).
 
       # Kill tmux Sessions
-      [ -z "$BE_QUIET" ] && echo "Checking for '$vm' tmux session"
+      [ -z "$BE_QUIET" ] && echo "Checking for '$vhost' tmux session"
 
-      if tmux -L netkit has-session -t="$vm" 2>/dev/null; then
-         [ -z "$BE_QUIET" ] && echo "Killing tmux session '$vm'"
-         tmux -L netkit kill-session -t="$vm"
+      if tmux -L netkit has-session -t="$vhost" 2>/dev/null; then
+         [ -z "$BE_QUIET" ] && echo "Killing tmux session '$vhost'"
+         tmux -L netkit kill-session -t="$vhost"
       fi
 
       [ -z "$BE_QUIET" ] && echo "Checking for '$vm-dead' tmux session"
diff --git a/core/bin/vhalt b/core/bin/vhalt
--- a/core/bin/vhalt
+++ b/core/bin/vhalt
@@ -173,20 +173,20 @@ if [ -n "$remove_fs" ] && [ -n "$BE_QUIET" ]; then
 fi
 
 
-for vm in "${vm_ids[@]}"; do
-   if ! get_vm_info_by_name "$target_user" "$vm"; then
-      echo -n 1>&2 "$SCRIPTNAME: no virtual machine named '$vm' exists"
+for vhost in "${vm_ids[@]}"; do
+   if ! get_vm_info_by_name "$target_user" "$vhost"; then
+      echo -n 1>&2 "$SCRIPTNAME: no virtual machine named '$vhost' exists"
       [ -n "$target_user" ] && echo " for user $target_user." || echo "."
       exit 1
    fi
 
-   [ -z "$BE_QUIET" ] && echo -e -n "Halting '$vm' (PID ${vm_info[pid]}) owned by \
+   [ -z "$BE_QUIET" ] && echo -e -n "Halting '$vhost' (PID ${vm_info[pid]}) owned by \
    $target_user [                    ]\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
 
    # Old method uses CTRL-ALT-DEL. This yields the error
    #   harddog_open - run_helper failed, errno = -2
    # and subsequently reboots (as opposed to powering off.)
-   #"$NETKIT_HOME/bin/uml_mconsole" "$vm" cad > /dev/null
+   #"$NETKIT_HOME/bin/uml_mconsole" "$vhost" cad > /dev/null
 
    # TODO: Try to use the old method - it uses /sbin/shutdown and is safer and
    # quicker.
@@ -198,27 +198,27 @@ for vm in "${vm_ids[@]}"; do
    # in the time given by the delay. s, u, and o are almost instant.
 
    # e: send a SIGTERM to all processes, except for init
-   "$NETKIT_HOME/bin/uml_mconsole" "$vm" sysrq e > /dev/null
+   "$NETKIT_HOME/bin/uml_mconsole" "$vhost" sysrq e > /dev/null
    sleep 2
 
    # i: send a SIGKILL to all processes, except for init
-   "$NETKIT_HOME/bin/uml_mconsole" "$vm" sysrq i > /dev/null
+   "$NETKIT_HOME/bin/uml_mconsole" "$vhost" sysrq i > /dev/null
    sleep 2
 
    # s: attempt to sync all mounted filesystems
-   "$NETKIT_HOME/bin/uml_mconsole" "$vm" sysrq s > /dev/null
+   "$NETKIT_HOME/bin/uml_mconsole" "$vhost" sysrq s > /dev/null
    sleep 0.2
 
    # u: attempt to remount all mounted filesystems read-only
-   "$NETKIT_HOME/bin/uml_mconsole" "$vm" sysrq u > /dev/null
+   "$NETKIT_HOME/bin/uml_mconsole" "$vhost" sysrq u > /dev/null
    sleep 0.2
 
    # o: shut the system off (if configured and supported)
-   "$NETKIT_HOME/bin/uml_mconsole" "$vm" sysrq o > /dev/null
+   "$NETKIT_HOME/bin/uml_mconsole" "$vhost" sysrq o > /dev/null
 
    if [ -z "$BE_QUIET" ]; then
       for _ in {1..21}; do
-         get_machine_state "$target_user" "$vm" || break
+         get_machine_state "$target_user" "$vhost" || break
          sleep 1
          echo -n "."
       done
@@ -226,8 +226,8 @@ for vm in "${vm_ids[@]}"; do
       echo
 
       # If machine is still up
-      if get_machine_state "$target_user" "$vm"; then
-         echo 1>&2 "$SCRIPTNAME: could not shut down '$vm'."
+      if get_machine_state "$target_user" "$vhost"; then
+         echo 1>&2 "$SCRIPTNAME: could not shut down '$vhost'."
       else
          # Remove filesystem (.disk file)
          [ -n "$remove_fs" ] && [ -n "${vm_info[disk]}" ] && rm_filesystem "${vm_info[disk]}"
