refactor lcrash

diff --git a/core/bin/lcrash b/core/bin/lcrash
--- a/core/bin/lcrash
+++ b/core/bin/lcrash
@@ -129,108 +129,95 @@ END_OF_HELP
 
 
 # Get command line options
-INVALID_OPTION=0
-OPT_LIST="help,version,kill,keep-fs,list,quick,quiet"
-CMDLINE_OPTIONS=$(getopt -ql "$OPT_LIST" -- "d:Fklq" "$@")
-if [ $? -gt 0 ]; then
-   INVALID_OPTION=1
+LONG_OPTS="help,version,keep-fs,kill,list,quiet,quick"
+SHORT_OPTS="d:Fklq"
+
+if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
+   # getopt will output the errorneous command-line argument
+   usage 1
 fi
 
-
-# Using verbose mode tells vcrash to wait for virtual machines to stop before
-# returning.
+# Verbose mode tells vcrash to wait for machines to stop before returning
 VERBOSE=1
 
-# Parse command line options
-parseCmdLine() {
-   while [ $# -gt 0 ]; do
-      CURRENT_ARGUMENT="$1"
-      case "$CURRENT_ARGUMENT" in
-      
-         -d)
-            shift; CURRENT_ARGUMENT="$1"
-            if [ ! -z "$LAB_DIRECTORY" ]; then
-               echo 1>&2 "$SCRIPTNAME: Multiple directory specifications: where can I find the lab?"
-               exit 1
-            fi
-            LAB_DIRECTORY=$(makeAbsolutePath "$CURRENT_ARGUMENT");;
-         
-         --help)
-            usage 0;;
-            
-         --keep-fs|-F)
-            KEEP_FILESYSTEM=1;;
-         
-         --kill|-k)
-            KILL_MODE=1;;
-         
-         --list|-l)
-            LISTVM=1;;
-         
-         --quick|--quiet|-q)
-            unset VERBOSE;;
-         
-         --version)
-            show_version
-            exit 0;;
-            
-         --)
-            shift
-            break;;
-      esac
-      shift
-   done
-   
-   while [ $# -gt 0 ]; do
-      checkSpaces "$1"
-      VHOSTLIST="$VHOSTLIST $1"
-      shift
-   done
-}
-eval parseCmdLine $CMDLINE_OPTIONS
+# (Safely) set positional parameters to those reordered by getopt
+eval set -- "$GETOPT_OPTS"
 
+while true; do
+   case "$1" in
+      -d)
+         LAB_DIRECTORY=$(makeAbsolutePath "$2")
+         shift
+         ;;
+      --help)
+         usage 0
+         ;;
+      -F|--keep-fs)
+         KEEP_FILESYSTEM=1
+         ;;
+      -k|--kill)
+         KILL_MODE=1
+         ;;
+      -l|--list)
+         LISTVM=1
+         ;;
+      -q|--quick|--quiet)
+         unset VERBOSE
+         ;;
+      --version)
+         show_version
+         exit 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
+         usage 1
+         ;;
+   esac
 
-# Check whether user gave some strange options
-if [ $INVALID_OPTION -eq 1 ]; then
-   echo 1>&2 "$SCRIPTNAME: Invalid option or missing option parameter"
-   exit 1
-fi
+   shift
+done
+
+# Non-option arguments are machine names
+VHOSTLIST=( "$@" )
+
+for host in "${VHOSTLIST[@]}"; do
+   checkSpaces "$host"
+done
+
 
 # If no lab directory has been given, assume current directory
 LAB_DIRECTORY=${LAB_DIRECTORY:-$PWD}
 
-# shellcheck source=./lcommon
-. "$NETKIT_HOME/bin/lcommon"
-
 # Check that the lab directory exists
 if [ ! -d "$LAB_DIRECTORY" ]; then
-   echo 1>&2 "$SCRIPTNAME: Lab directory ($LAB_DIRECTORY) does not exist"
+   echo 1>&2 "$SCRIPTNAME: $LAB_DIRECTORY: No such directory"
    exit 1
 fi
 
 # Check whether path to the lab directory contains spaces
 if containsRegexp LAB_DIRECTORY " "; then
-   echo 1>&2 "$SCRIPTNAME: Invalid lab directory: '$LAB_DIRECTORY' (path contains spaces)"
+   echo 1>&2 "$SCRIPTNAME: $LAB_DIRECTORY: Path contains spaces"
    exit 1
 fi
 
 
+# shellcheck source=./lcommon
+. "$NETKIT_HOME/bin/lcommon"
+
+
 # Print lab information
-echo
-bold_print "======================== Crashing lab ==========================="
+bold_print "========================== Crashing lab ========================="
 lab_welcome
 bold_print "================================================================="
 
 # Crash virtual machines
 lab_crash
-echo
 bold_print "Lab has been crashed."
 bold_print "================================================================="
 
 # Show a list of running virtual machines, if asked to
-if [ ! -z "$LISTVM" ]; then
-   echo
-   vlist
-fi
-
-echo
+[ -n "$LISTVM" ] && vlist
