remove warning function

diff --git a/core/bin/lcrash b/core/bin/lcrash
--- a/core/bin/lcrash
+++ b/core/bin/lcrash
@@ -28,8 +28,6 @@ if [ -z "$NETKIT_HOME" ]; then
    exit 1
 fi
 
-CMDLINE="$0 $*"
-
 # shellcheck source=./script_utils
 . "$NETKIT_HOME/bin/script_utils"
 
@@ -152,8 +150,7 @@ parseCmdLine() {
          -d)
             shift; CURRENT_ARGUMENT="$1"
             if [ ! -z "$LAB_DIRECTORY" ]; then
-               warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                  "Multiple directory specifications: where can I find the lab?"
+               echo 1>&2 "$SCRIPTNAME: Multiple directory specifications: where can I find the lab?"
                exit 1
             fi
             LAB_DIRECTORY=$(makeAbsolutePath "$CURRENT_ARGUMENT");;
@@ -195,7 +192,7 @@ eval parseCmdLine $CMDLINE_OPTIONS
 
 # Check whether user gave some strange options
 if [ $INVALID_OPTION -eq 1 ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid option or missing option parameter."
+   echo 1>&2 "$SCRIPTNAME: Invalid option or missing option parameter"
    exit 1
 fi
 
@@ -207,14 +204,13 @@ LAB_DIRECTORY=${LAB_DIRECTORY:-$PWD}
 
 # Check that the lab directory exists
 if [ ! -d "$LAB_DIRECTORY" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Lab directory ($LAB_DIRECTORY) does not exist."
+   echo 1>&2 "$SCRIPTNAME: Lab directory ($LAB_DIRECTORY) does not exist"
    exit 1
 fi
 
 # Check whether path to the lab directory contains spaces
 if containsRegexp LAB_DIRECTORY " "; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-            "Invalid lab directory: \"$LAB_DIRECTORY\" (path contains spaces)."
+   echo 1>&2 "$SCRIPTNAME: Invalid lab directory: '$LAB_DIRECTORY' (path contains spaces)"
    exit 1
 fi
 
diff --git a/core/bin/linfo b/core/bin/linfo
--- a/core/bin/linfo
+++ b/core/bin/linfo
@@ -28,8 +28,6 @@ if [ -z "$NETKIT_HOME" ]; then
    exit 1
 fi
 
-CMDLINE="$0 $*"
-
 # shellcheck source=./script_utils
 . "$NETKIT_HOME/bin/script_utils"
 
@@ -160,7 +158,7 @@ parseCmdLine() {
    done
 
    if [ $# -gt 0 ]; then
-      warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid option: \"$1\"."
+      echo 1>&2 "$SCRIPTNAME: Invalid option: '$1'"
       exit 1
    fi
 }
@@ -168,7 +166,7 @@ eval parseCmdLine $CMDLINE_OPTIONS
 
 # Check whether user gave some strange options
 if [ $INVALID_OPTION -eq 1 ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid option or missing option parameter."
+   echo 1>&2 "$SCRIPTNAME: Invalid option or missing option parameter"
    exit 1
 fi
 
@@ -186,14 +184,13 @@ for LAB_DIRECTORY in $LAB_DIRECTORIES; do
    LAB_DESCRIPTIONS="$LAB_DESCRIPTIONS  \"$LAB_DESCRIPTION\""
    # Check that the lab directory exists
    if [ ! -d "$LAB_DIRECTORY" ]; then
-      warning "$SCRIPTNAME" "$CMDLINE" "$0" "Lab directory ($LAB_DIRECTORY) does not exist."
+      echo 1>&2 "$SCRIPTNAME: Lab directory ($LAB_DIRECTORY) does not exist"
       exit 1
    fi
 
    # Check whether path to the lab directory contains spaces
    if containsRegexp LAB_DIRECTORY " "; then
-      warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-               "Invalid lab directory: \"$LAB_DIRECTORY\" (path contains spaces)."
+      echo 1>&2 "$SCRIPTNAME: Invalid lab directory: '$LAB_DIRECTORY' (path contains spaces)"
       exit 1
    fi
 
@@ -224,13 +221,13 @@ done
 if [ ! -z "$MAP_FILE" ]; then
    for LAB_DIRECTORY in $LAB_DIRECTORIES; do
       if [ ! -f "${LAB_DIRECTORY%/}/lab.conf" ]; then
-         warning "$SCRIPTNAME" "$CMDLINE" "$0" "Unable to find file ${LAB_DIRECTORY}/lab.conf: Skipping"
+         echo 1>&2 "$SCRIPTNAME: Unable to find file $LAB_DIRECTORY/lab.conf: Skipping"
          continue
       fi
       CONFLIST="$CONFLIST ${LAB_DIRECTORY%/}/lab.conf"
    done
    if [ -z "$CONFLIST" ]; then
-      warning "$SCRIPTNAME" "$CMDLINE" "$0" "No valid lab.confs found: cannot create topology map."
+      echo 1>&2 "$SCRIPTNAME: No valid lab.confs found: cannot create topology map"
       exit 1
    fi
    if labMap "$MAP_FILE" $CONFLIST; then
diff --git a/core/bin/lstart b/core/bin/lstart
--- a/core/bin/lstart
+++ b/core/bin/lstart
@@ -27,8 +27,6 @@ if [ -z "$NETKIT_HOME" ]; then
    exit 1
 fi
 
-CMDLINE="$0 $*"
-
 . "$NETKIT_HOME/bin/script_utils"
 
 
@@ -221,8 +219,7 @@ parseCmdLine() {
          -d)
             shift; CURRENT_ARGUMENT="$1"
             if [ ! -z "$LAB_DIRECTORY" ]; then
-               warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                  "Multiple directory specifications: where can I find the lab?"
+               echo 1>&2 "$SCRIPTNAME: Multiple directory specifications: where can I find the lab?"
                exit 1
             fi
             LAB_DIRECTORY=$(makeAbsolutePath "$CURRENT_ARGUMENT");;
@@ -257,13 +254,11 @@ parseCmdLine() {
             shift; CURRENT_ARGUMENT="$1"
             if [ ! -z "$CURRENT_ARGUMENT" ]; then
                if ! echo "$CURRENT_ARGUMENT" | grep -q "^[0-9][0-9]*$"; then
-                  warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                     "Invalid setting for option -p: \"$CURRENT_ARGUMENT\". Positive integer expected."
+                  echo 1>&2 "$SCRIPTNAME: Invalid setting for option -p: '$CURRENT_ARGUMENT'. Positive integer expected"
                   exit 1
                fi
                if [ ! -z "$FORCE_PARALLEL_MODE" ]; then
-                  warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                     "Option -p is used multiple times."
+                  echo 1>&2 "$SCRIPTNAME: Option -p is used multiple times"
                   exit 1
                fi
                MAX_SIMULTANEOUS_VMS="$CURRENT_ARGUMENT"
@@ -283,8 +278,7 @@ parseCmdLine() {
          --wait|-w)
             shift; CURRENT_ARGUMENT="$1"
             if ! echo "$CURRENT_ARGUMENT" | grep -q "^[0-9][0-9]*$"; then
-               warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                  "Invalid setting for option -w: \"$CURRENT_ARGUMENT\". Positive integer expected."
+               echo 1>&2 "$SCRIPTNAME: Invalid setting for option -w: '$CURRENT_ARGUMENT'. Positive integer expected"
                exit 1
             fi
             GRACE_TIME="$CURRENT_ARGUMENT";;
@@ -301,8 +295,7 @@ parseCmdLine() {
                user|builtin|both)
                   VERIFY="$CURRENT_ARGUMENT";;
                *)
-                  warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                     "Invalid setting for option --verify: \"$CURRENT_ARGUMENT\"."
+                  echo 1>&2 "$SCRIPTNAME: Invalid setting for option --verify: '$CURRENT_ARGUMENT'"
                   exit 1;;
             esac;;
 
@@ -325,7 +318,7 @@ eval parseCmdLine $CMDLINE_OPTIONS
 
 # Check whether user gave some strange options
 if [ $INVALID_OPTION -eq 1 ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid option or missing option parameter."
+   echo 1>&2 "$SCRIPTNAME: Invalid option or missing option parameter"
    exit 1
 fi
 
@@ -334,14 +327,13 @@ LAB_DIRECTORY=${LAB_DIRECTORY:-$PWD}
 
 # Check that the lab directory exists
 if [ ! -d "$LAB_DIRECTORY" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Lab directory ($LAB_DIRECTORY) does not exist."
+   echo 1>&2 "$SCRIPTNAME: Lab directory ($LAB_DIRECTORY) does not exist"
    exit 1
 fi
 
 # Check whether path to the lab directory contains spaces
 if containsRegexp LAB_DIRECTORY " "; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-            "Invalid lab directory: \"$LAB_DIRECTORY\" (path contains spaces)."
+   echo 1>&2 "$SCRIPTNAME: Invalid lab directory: '$LAB_DIRECTORY' (path contains spaces)"
    exit 1
 fi
 
@@ -354,8 +346,7 @@ fi
 
 # Check if -p and -s options are being used together
 if [ ! -z "$FORCE_PARALLEL_MODE" -a ! -z "$BE_SEQUENTIAL" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-            "Options -s and -p cannot be used together."
+   echo 1>&2 "$SCRIPTNAME: Options -s and -p cannot be used together"
    exit 1
 fi
 
@@ -381,8 +372,7 @@ if [ ! -z "$MAKEFILE" ]; then
 fi
 
 if [ ! -f "$LAB_DIRECTORY/lab.conf" -a ! -f "$LAB_DIRECTORY/lab.dep" -a -z "$FORCE_LAB" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-            "This does not appear to be a lab directory. Use option -F to convince me it is."
+   echo 1>&2 "$SCRIPTNAME: This does not appear to be a lab directory. Use option -F to convince me it is"
    exit 1
 fi
 
diff --git a/core/bin/vclean b/core/bin/vclean
--- a/core/bin/vclean
+++ b/core/bin/vclean
@@ -28,8 +28,6 @@ if [ -z "$NETKIT_HOME" ]; then
    exit 1
 fi
 
-CMDLINE="$0 $*"
-
 . "$NETKIT_HOME/bin/script_utils"
 
 # Write to the vcommands log
@@ -175,8 +173,7 @@ parseCmdLine() {
          --user|-u)
             shift; CURRENT_ARGUMENT="$1"
             if [ "x$CURRENT_ARGUMENT" = "x" ]; then
-               warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                       "Expecting username."
+               echo 1>&2 "$SCRIPTNAME: Expecting username"
                exit 1
             fi
             checkSpaces "$CURRENT_ARGUMENT"
@@ -204,7 +201,7 @@ parseCmdLine() {
    done
    
    if [ $# -gt 0 ]; then
-      warning "$SCRIPTNAME" "$CMDLINE" "$0" "Too many arguments: $*"
+      echo 1>&2 "$SCRIPTNAME: Too many arguments: $*"
       exit 1
    fi
 }
@@ -213,20 +210,20 @@ eval parseCmdLine $CMDLINE_OPTIONS
 
 # Check whether user gave some strange options
 if [ $INVALID_OPTION -eq 1 ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid option or missing option parameter."
+   echo 1>&2 "$SCRIPTNAME: Invalid option or missing option parameter"
    exit 1
 fi
 
 
 # Test mode is senseless if working in quiet mode
 if [ ! -z "$TEST_MODE" -a ! -z "$BE_QUIET" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Option --test cannot be used when working in quiet mode."
+   echo 1>&2 "$SCRIPTNAME: Option --test cannot be used when working in quiet mode"
    exit 1
 fi
 
 # Actions --remove-hubs and --kill-machines are incompatible
 if [ ! -z "$REMOVE_UNUSED_HUBS" -a ! -z "$KILL_MACHINES" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Actions --remove-hubs and --kill-machines cannot be performed at the same time."
+   echo 1>&2 "$SCRIPTNAME: Actions --remove-hubs and --kill-machines cannot be performed at the same time"
    exit 1
 fi
 
diff --git a/core/bin/vconf b/core/bin/vconf
--- a/core/bin/vconf
+++ b/core/bin/vconf
@@ -32,8 +32,6 @@ if [ -z "$NETKIT_HOME" ]; then
    exit 1
 fi
 
-CMDLINE="$0 $*"
-
 . "$NETKIT_HOME/bin/script_utils"
 
 # Write to the vcommands log
@@ -163,15 +161,13 @@ parseCmdLine() {
             ETH_INTERFACES="${ETH_INTERFACES} ${CURRENT_ARGUMENT#--}="
             shift; CURRENT_ARGUMENT="$1"
             if containsRegexp CURRENT_ARGUMENT "_"; then
-               warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                       "Invalid collision domain: $CURRENT_ARGUMENT (underscoresare are not allowed)."
+               echo 1>&2 "$SCRIPTNAME: Invalid collision domain: $CURRENT_ARGUMENT (underscoresare are not allowed)"
                exit 1
             fi
             if containsRegexp CURRENT_ARGUMENT "," || containsRegexp CURRENT_ARGUMENT "\\."; then
                if [ "${CURRENT_ARGUMENT#tap,}" = "$CURRENT_ARGUMENT" ]; then
                   # This is not a special hub, but its name contains a comma
-                  warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                        "Invalid collision domain: $CURRENT_ARGUMENT (commas and dots are only allowed for Internet connected collision domains)."
+                  echo 1>&2 "$SCRIPTNAME: Invalid collision domain: $CURRENT_ARGUMENT (commas and dots are only allowed for Internet connected collision domains)"
                   exit 1
                fi
             fi
@@ -193,8 +189,7 @@ parseCmdLine() {
          --user|-u)
             shift; CURRENT_ARGUMENT="$1"
             if [ "x$CURRENT_ARGUMENT" = "x" ]; then
-               warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                       "Expecting username."
+               echo 1>&2 "$SCRIPTNAME: Expecting username"
                exit 1
             fi
             checkSpaces "$CURRENT_ARGUMENT"
@@ -218,7 +213,7 @@ parseCmdLine() {
    # Parse virtual machine name   
    while [ $# != 0 ]; do
       if [ ! -z "$VM_ID" ]; then
-         warning "$SCRIPTNAME" "$CMDLINE" "$0" "Too many arguments: $*"
+         echo 1>&2 "$SCRIPTNAME: Too many arguments: $*"
          exit 1
       fi
       checkSpaces "$1"
@@ -232,13 +227,13 @@ eval parseCmdLine $CMDLINE_OPTIONS
 
 # Check whether user gave some strange options
 if [ $INVALID_OPTION -eq 1 ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid option or missing option parameter."
+   echo 1>&2 "$SCRIPTNAME: Invalid option or missing option parameter"
    exit 1
 fi
 
 # Check whether virtual machine name is missing
 if [ -z "$VM_ID" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Virtual machine name/PID is missing."
+   echo 1>&2 "$SCRIPTNAME: Virtual machine name/PID is missing"
    exit 1
 fi
 
@@ -256,7 +251,7 @@ setupInterfaces() {
       HUB_NAME=${1#*=}
       if [ "${HUB_NAME}" = "tap" ]; then
          echo 1>&2
-         warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid tap collision domain specification: \"$1\"."
+         echo 1>&2 "$SCRIPTNAME: Invalid tap collision domain specification: '$1'"
          exit 1
       fi
       if containsRegexp HUB_NAME "tap,"; then
@@ -277,7 +272,7 @@ setupInterfaces() {
             ')
          if [ "x$CHECK_TAP" = "x0" ]; then
             echo 1>&2
-            warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid tap collision domain specification: \"$1\"."
+            echo 1>&2 "$SCRIPTNAME: Invalid tap collision domain specification: '$1'"
             exit 1
          else
             eval "$CHECK_TAP"
@@ -287,7 +282,7 @@ setupInterfaces() {
       HUB_SOCKET="${HUB_SOCKET_DIR}/${HUB_SOCKET_PREFIX}_${USERID}_${HUB_NAME}${HUB_SOCKET_EXTENSION}"
       
       if containsRegexp MCONSOLE_CMD "${DEVICE}=daemon,,,"; then
-         warning "$SCRIPTNAME" "$CMDLINE" "$0" "Duplicate interface: $DEVICE."
+         echo 1>&2 "$SCRIPTNAME: Duplicate interface: $DEVICE"
          exit 1
       fi
       
diff --git a/core/bin/vcrash b/core/bin/vcrash
--- a/core/bin/vcrash
+++ b/core/bin/vcrash
@@ -30,8 +30,6 @@ if [ -z "$NETKIT_HOME" ]; then
    exit 1
 fi
 
-CMDLINE="$0 $*"
-
 # shellcheck source=./script_utils
 . "$NETKIT_HOME/bin/script_utils"
 
@@ -175,8 +173,7 @@ parseCmdLine() {
          --user|-u)
             shift; CURRENT_ARGUMENT="$1"
             if [ "x$CURRENT_ARGUMENT" = "x" ]; then
-               warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                       "Expecting username."
+               echo 1>&2 "$SCRIPTNAME: Expecting username"
                exit 1
             fi
             checkSpaces "$CURRENT_ARGUMENT"
@@ -211,7 +208,7 @@ parseCmdLine() {
          checkSpaces "$1"
          if [ ! -z "$VM_PID" ]; then
             if [ ! -z "$VM_NAME" ]; then
-               warning "$SCRIPTNAME" "$CMDLINE" "$0" "Too many arguments: \"$1\". Option --force requires two arguments."
+               echo 1>&2 "$SCRIPTNAME: Too many arguments: '$1'. Option --force requires two arguments"
                exit 1
             else
                VM_NAME=$1
@@ -234,21 +231,21 @@ eval parseCmdLine $CMDLINE_OPTIONS
 
 # Check whether user gave some strange options
 if [ $INVALID_OPTION -eq 1 ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid option or missing option parameter."
+   echo 1>&2 "$SCRIPTNAME: Invalid option or missing option parameter"
    exit 1
 fi
 
 
 # Check whether virtual machine name is missing
 if [ -z "$FORCE_MODE" -a -z "$VM_IDS" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Virtual machine name/PID is missing."
+   echo 1>&2 "$SCRIPTNAME: Virtual machine name/PID is missing"
    exit 1
 fi
 
 
 # Check whether incompatible modes have been selected
 if [ ! -z "$FORCE_MODE" -a ! -z "$USE_MCONSOLE" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "You cannot use the --force option if you asked to use mconsole sockets."
+   echo 1>&2 "$SCRIPTNAME: You cannot use the --force option if you asked to use mconsole sockets"
    exit 1
 fi
 
@@ -256,7 +253,7 @@ fi
 # Check whether arguments for the --force option are missing
 if [ ! -z "$FORCE_MODE" ]; then
    if [ -z "$VM_PID" -o -z "$VM_NAME" ]; then
-      warning "$SCRIPTNAME" "$CMDLINE" "$0" "Missing virtual machine and/or PID."
+      echo 1>&2 "$SCRIPTNAME: Missing virtual machine and/or PID"
       exit 1
    fi
 fi
@@ -264,7 +261,7 @@ fi
 
 # Test mode is senseless if working in quiet mode
 if [ ! -z "$TEST_MODE" -a ! -z "$BE_QUIET" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Option --test cannot be used when working in quiet mode."
+   echo 1>&2 "$SCRIPTNAME: Option --test cannot be used when working in quiet mode"
    exit 1
 fi
 
diff --git a/core/bin/vdump b/core/bin/vdump
--- a/core/bin/vdump
+++ b/core/bin/vdump
@@ -136,7 +136,7 @@ eval parseCmdLine $CMDLINE_OPTIONS
 
 # Check whether user gave some strange options
 if [ $INVALID_OPTION -eq 1 ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid option or missing option parameter."
+   echo 1>&2 "$SCRIPTNAME: Invalid option or missing option parameter"
    exit 1
 fi
 
