refactor lhalt

diff --git a/core/bin/lhalt b/core/bin/lhalt
--- a/core/bin/lhalt
+++ b/core/bin/lhalt
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 #     Copyright 2002-2009 Stefano Pettini, Fabio Ricci, Massimo Rimondini
 #     Computer Networks Research Group, Roma Tre University.
@@ -23,31 +23,27 @@
 
 SCRIPTNAME=$(basename "$0")
 
-# The following line has been introduced to ensure backward compatibility
-: "${NETKIT_HOME:=$VLAB_HOME}"
-
 if [ -z "$NETKIT_HOME" ]; then
    echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not properly set;"
-   echo 1>&2 "please set it as described in the Netkit documentation and try"
-   echo 1>&2 "again."
+   echo 1>&2 "please set it as described in the Netkit documentation and try again."
    exit 1
 fi
 
 CMDLINE="$0 $*"
 
+# shellcheck source=./script_utils
 . "$NETKIT_HOME/bin/script_utils"
 
 
 # Write to the vcommands log
-logWrite $0 $*
+logWrite "$0 $*"
 
 
 # This function is used to print the lhalt usage
 help() {
    echo
-   echo "Usage: $SCRIPTNAME [options] [MACHINE-NAME] ..."
+   echo "Usage: $SCRIPTNAME [OPTION]... [MACHINE]..."
    cat << END_OF_HELP
-
 This command gracefully shuts down the virtual machines of a Netkit lab. Halting
 instead of crashing is much slower but preserves virtual machines filesystem
 integrity. Optionally, this command also deletes virtual machines filesystems.
@@ -79,120 +75,131 @@ If one or more MACHINE-NAMEs are passed on the command line, then only those
 machines will be halted (and their filesystems deleted, if asked to). If any
 of the MACHINE-NAMEs is invalid (i.e., it does not correspond to a virtual
 machine of the lab), it will simply be skipped.
-
 END_OF_HELP
 }
 
 
-# Get command line options
-INVALID_OPTION=0
-OPT_LIST="help,version,remove-fs,quick,quiet,list"
-CMDLINE_OPTIONS=$(getopt -ql "$OPT_LIST" -- "hd:lqr" "$@")
-if [ $? -gt 0 ]; then
-   INVALID_OPTION=1
-fi
+# Output lhalt's usage to stderr
+# Usage: usage
+usage() {
+   echo 1>&2 "Usage: $SCRIPTNAME [OPTION]... MACHINE..."
+   echo 1>&2 "Try '$SCRIPTNAME --help' for more information."
+}
 
 
 # Using verbose mode tells vcrash to wait for virtual machines to stop before
 # returning.
 VERBOSE=1
 
-# Parse command line options
-parseCmdLine() {
-   while [ $# -gt 0 ]; do
-      CURRENT_ARGUMENT="$1"
-      case "$CURRENT_ARGUMENT" in
-      
-         -d)
-            shift; CURRENT_ARGUMENT="$1"
-            if [ ! -z "$LAB_DIRECTORY" ]; then
-               warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                  "Multiple directory specifications: where can I find the lab?"
-               exit 1
-            fi
-            LAB_DIRECTORY=$(makeAbsolutePath "$CURRENT_ARGUMENT");;
-         
-         --help|-h)
-            help
-            exit;;
-            
-         --remove-fs|-r)
-            REMOVE_FILESYSTEM=1;;
-         
-         --list|-l)
-            LISTVM=1;;
-         
-         --quick|--quiet|-q)
-            unset VERBOSE;;
-         
-         --version)
-            showVersion
-            exit 0;;
-            
-         --)
-            shift
-            break;;
-      esac
-      shift
-   done
-   
-   while [ $# -gt 0 ]; do
-      checkSpaces "$1"
-      VHOSTLIST="$VHOSTLIST $1"
-      shift
-   done
-}
-eval parseCmdLine $CMDLINE_OPTIONS
 
+# Get command line options
+LONG_OPTS="help,version,remove-fs,quick,quiet,list"
+SHORT_OPTS="d:hlqr"
 
-# Check whether user gave some strange options
-if [ $INVALID_OPTION -eq 1 ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid option or missing option parameter."
+if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
+   # getopt will output the errorneous command-line argument
+   usage
    exit 1
 fi
 
+# (Safely) set positional parameters to those reordered by getopt
+eval set -- "$GETOPT_OPTS"
+
+while true; do
+   case "$1" in
+      -d)
+         OPT_ARG="$2"
+         shift
+
+         if [ -n "$LAB_DIRECTORY" ]; then
+            echo 1>&2 "$SCRIPTNAME: Multiple directory specifications"
+            usage
+            exit 1
+         fi
+
+         LAB_DIRECTORY=$(makeAbsolutePath "$OPT_ARG")
+         ;;
+      -h|--help)
+         help
+         exit 0
+         ;;
+      -r|--remove-fs)
+         REMOVE_FILESYSTEM=1
+         ;;
+      -l|--list)
+         LISTVM=1
+         ;;
+      -q|--quick|--quiet)
+         unset VERBOSE
+         ;;
+      --version)
+         showVersion
+         exit 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
+         usage
+         exit 1
+         ;;
+   esac
+
+   shift
+done
+   
+# Non-option arguments are machine names
+VHOSTLIST=( "$@" )
+
+for host in "${VHOSTLIST[@]}"; do
+   checkSpaces "$host"
+done
+
+
 # If no lab directory has been given, assume current directory
-LAB_DIRECTORY=${LAB_DIRECTORY:-${PWD}}
-. "$NETKIT_HOME/bin/lcommon"
+LAB_DIRECTORY=${LAB_DIRECTORY:-$PWD}
 
 # Check that the lab directory exists
 if [ ! -d "$LAB_DIRECTORY" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Lab directory ($LAB_DIRECTORY) does not exist."
-   exit 1
-fi
-
-# Check whether path to the lab directory contains spaces
-if containsRegexp LAB_DIRECTORY " "; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-            "Invalid lab directory: \"$LAB_DIRECTORY\" (path contains spaces)."
+   echo 1>&2 "$SCRIPTNAME: $LAB_DIRECTORY: Directory does not exist"
    exit 1
 fi
 
 # Filesystem cannot be removed if we are working in quiet mode
-if [ -z "$VERBOSE" -a ! -z "$REMOVE_FILESYSTEM" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-            "Filesystems cannot be removed (option -r) when working in quiet mode (option -q)."
+if [ -z "$VERBOSE" ] && [ -n "$REMOVE_FILESYSTEM" ]; then
+   echo 1>&2 "$SCRIPTNAME: Filesystems cannot be removed (-r) when working in quiet mode (-q)"
    exit 1
 fi
 
+# shellcheck source=./lcommon
+. "$NETKIT_HOME/bin/lcommon"
 
-
-# Print some information about the lab
-echo
-becho "======================== Halting lab ============================"
-labWelcome
-becho "================================================================="
+# Print lab information
+bold_print "======================== Halting lab ============================"
+lab_welcome
+bold_print "================================================================="
 
 # Halt virtual machines
-labHalt
-echo
-becho "Lab has been halted."
-becho "================================================================="
+build_vhostlist
+
+[ -z "$VERBOSE" ] && lhalt_quiet="-q"
+[ -n "$REMOVE_FILESYSTEM" ] && lhalt_rm_fs="-r"
+
+for host in "${VHOSTLIST[@]}"; do
+   [ -z "$VERBOSE" ] && bold_print "Halting '$host'... "
+   vhalt "$lhalt_quiet" "$lhalt_rm_fs" "$host" && rm -f "$LAB_DIRECTORY/$host.ready"
+done
+
+bold_print "Removing readyfor.test..."
+rm -f "$LAB_DIRECTORY/readyfor.test"
+
+bold_print "Lab has been halted."
+bold_print "================================================================="
 
 # Show a list of running virtual machines, if asked to
-if [ ! -z "$LISTVM" ]; then
+if [ -n "$LISTVM" ]; then
    echo
    vlist
 fi
-
-echo
