make script order consistent

diff --git a/core/bin/linfo b/core/bin/linfo
--- a/core/bin/linfo
+++ b/core/bin/linfo
@@ -21,20 +21,6 @@
 # This script displays information about a lab without running it. Optionally,
 # it can create a PNG file containing the level 2 topology of the lab.
 
-SCRIPTNAME=$(basename "$0")
-
-if [ -z "$NETKIT_HOME" ]; then
-   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
-   exit 1
-fi
-
-# shellcheck source=./script_utils
-. "$NETKIT_HOME/bin/script_utils"
-
-
-# Write to the vcommands log
-log_write "$0 $*"
-
 
 ###############################################################################
 # Write linfo's usage line to standard output.
@@ -110,108 +96,6 @@ END_OF_HELP
 }
 
 
-# Get command line options
-LONG_OPTS="auto,help,version,map:"
-SHORT_OPTS="ad:m:"
-
-if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
-   # getopt will output the errorneous command-line argument
-   usage 1
-fi
-
-VERBOSE=1
-
-# (Safely) set positional parameters to those reordered by getopt
-eval set -- "$GETOPT_OPTS"
-
-while true; do
-   case $1 in
-      -a|--auto)
-         # TODO: Remove or make better.
-         for LAB_DIRECTORY in "${PWD%?}"*/; do
-            LAB_DIRECTORIES+=( "$LAB_DIRECTORY" )
-         done
-         ;;
-      -d)
-         LAB_DIRECTORY=$(readlink --canonicalize-missing "$2")
-         LAB_DIRECTORIES+=( "$LAB_DIRECTORY" )
-         shift
-         ;;
-      --help)
-         usage 0
-         ;;
-      -m|--map)
-         MAP_FILE=$2
-         shift
-         ;;
-      --version)
-         show_version
-         exit 0
-         ;;
-      --)
-         shift
-         break
-         ;;
-      *)
-         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
-         usage 1
-         ;;
-   esac
-   shift
-done
-
-if [ $# -gt 0 ]; then
-   echo 1>&2 "$SCRIPTNAME: Too many arguments"
-   exit 1
-fi
-
-
-# If no lab directory has been given, assume current directory
-[ "${#LAB_DIRECTORIES[@]}" -eq 0 ] && LAB_DIRECTORIES=( "$PWD" )
-
-# shellcheck source=./lcommon
-. "$NETKIT_HOME/bin/lcommon"
-
-
-declare -A LAB_VERSIONS LAB_AUTHORS LAB_EMAILS LAB_WEBS LAB_DESCRIPTIONS
-
-for LAB_DIRECTORY in "${LAB_DIRECTORIES[@]}"; do
-   # Check that the lab directory exists
-   if [ ! -d "$LAB_DIRECTORY" ]; then
-      echo 1>&2 "$SCRIPTNAME: $LAB_DIRECTORY: No such directory"
-      exit 1
-   fi
-
-   # TODO: change lab variable assignment to an lcommon function
-   # shellcheck source=./lcommon
-   . "$NETKIT_HOME/bin/lcommon"
-
-   dir=$(basename "$LAB_DIRECTORY")
-
-   # We use associative arrays for printing the values with their respective
-   # directory basename. SC2034 (variable appears unused) must be ignored
-   # because the array is only referenced by name.
-   # shellcheck disable=SC2034
-   [ -n "$LAB_VERSION" ] &&     LAB_VERSIONS[$dir]=$LAB_VERSION
-   # shellcheck disable=SC2034
-   [ -n "$LAB_AUTHOR" ] &&      LAB_AUTHORS[$dir]=$LAB_AUTHOR
-   # shellcheck disable=SC2034
-   [ -n "$LAB_EMAIL" ] &&       LAB_EMAILS[$dir]=$LAB_EMAIL
-   # shellcheck disable=SC2034
-   [ -n "$LAB_WEB" ] &&         LAB_WEBS[$dir]=$LAB_WEB
-   # shellcheck disable=SC2034
-   [ -n "$LAB_DESCRIPTION" ] && LAB_DESCRIPTIONS[$dir]=$LAB_DESCRIPTION
-
-   # Check whether path to the lab directory contains spaces
-   if string_contains " " "$LAB_DIRECTORY"; then
-      echo 1>&2 "$SCRIPTNAME: $LAB_DIRECTORY: Path contains whitespace"
-      exit 1
-   fi
-
-   build_vhostlist
-done
-
-
 ###############################################################################
 # From a lab info associative array (key is directory basename, value is the
 # relevant attribute's value) construct a formatted list suitable for
@@ -283,6 +167,120 @@ generate_info_str() {
 }
 
 
+SCRIPTNAME=$(basename "$0")
+
+if [ -z "$NETKIT_HOME" ]; then
+   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
+   exit 1
+fi
+
+# shellcheck source=./script_utils
+. "$NETKIT_HOME/bin/script_utils"
+# shellcheck source=./lcommon
+. "$NETKIT_HOME/bin/lcommon"
+
+# Write to the vcommands log
+log_write "$0 $*"
+
+
+# Get command line options
+LONG_OPTS="auto,help,version,map:"
+SHORT_OPTS="ad:m:"
+
+if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
+   # getopt will output the errorneous command-line argument
+   usage 1
+fi
+
+# (Safely) set positional parameters to those reordered by getopt
+eval set -- "$GETOPT_OPTS"
+
+while true; do
+   case $1 in
+      -a|--auto)
+         # TODO: Remove or make better.
+         for LAB_DIRECTORY in "${PWD%?}"*/; do
+            LAB_DIRECTORIES+=( "$LAB_DIRECTORY" )
+         done
+         ;;
+      -d)
+         LAB_DIRECTORY=$(readlink --canonicalize-missing "$2")
+         LAB_DIRECTORIES+=( "$LAB_DIRECTORY" )
+         shift
+         ;;
+      --help)
+         usage 0
+         ;;
+      -m|--map)
+         MAP_FILE=$2
+         shift
+         ;;
+      --version)
+         show_version
+         exit 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
+         usage 1
+         ;;
+   esac
+
+   shift
+done
+
+if [ $# -gt 0 ]; then
+   echo 1>&2 "$SCRIPTNAME: Too many arguments"
+   exit 1
+fi
+
+
+# If no lab directory has been given, assume current directory
+[ "${#LAB_DIRECTORIES[@]}" -eq 0 ] && LAB_DIRECTORIES=( "$PWD" )
+
+
+declare -A LAB_VERSIONS LAB_AUTHORS LAB_EMAILS LAB_WEBS LAB_DESCRIPTIONS
+
+for LAB_DIRECTORY in "${LAB_DIRECTORIES[@]}"; do
+   # Check that the lab directory exists
+   if [ ! -d "$LAB_DIRECTORY" ]; then
+      echo 1>&2 "$SCRIPTNAME: $LAB_DIRECTORY: No such directory"
+      exit 1
+   fi
+
+   # TODO: change lab variable assignment to an lcommon function
+   # shellcheck source=./lcommon
+   . "$NETKIT_HOME/bin/lcommon"
+
+   dir=$(basename "$LAB_DIRECTORY")
+
+   # We use associative arrays for printing the values with their respective
+   # directory basename. SC2034 (variable appears unused) must be ignored
+   # because the array is only referenced by name.
+   # shellcheck disable=SC2034
+   [ -n "$LAB_VERSION" ] &&     LAB_VERSIONS[$dir]=$LAB_VERSION
+   # shellcheck disable=SC2034
+   [ -n "$LAB_AUTHOR" ] &&      LAB_AUTHORS[$dir]=$LAB_AUTHOR
+   # shellcheck disable=SC2034
+   [ -n "$LAB_EMAIL" ] &&       LAB_EMAILS[$dir]=$LAB_EMAIL
+   # shellcheck disable=SC2034
+   [ -n "$LAB_WEB" ] &&         LAB_WEBS[$dir]=$LAB_WEB
+   # shellcheck disable=SC2034
+   [ -n "$LAB_DESCRIPTION" ] && LAB_DESCRIPTIONS[$dir]=$LAB_DESCRIPTION
+
+   # Check whether path to the lab directory contains spaces
+   if string_contains " " "$LAB_DIRECTORY"; then
+      echo 1>&2 "$SCRIPTNAME: $LAB_DIRECTORY: Path contains whitespace"
+      exit 1
+   fi
+
+   build_vhostlist
+done
+
+
 printf -v LAB_DIRECTORY '%s, ' "${LAB_DIRECTORIES[@]}"
 LAB_DIRECTORY=${LAB_DIRECTORY%", "}
 
@@ -329,5 +327,3 @@ if [ -n "$MAP_FILE" ]; then
 fi
 
 bold_print "================================================================="
-
-echo
diff --git a/core/bin/vclean b/core/bin/vclean
--- a/core/bin/vclean
+++ b/core/bin/vclean
@@ -21,19 +21,6 @@
 # This is the Netkit vclean script, which can be used to remove unused virtual
 # hubs, hanging UML kernels and configured tunnels.
 
-SCRIPTNAME=$(basename "$0")
-
-if [ -z "$NETKIT_HOME" ]; then
-   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
-   exit 1
-fi
-
-# shellcheck source=./script_utils
-. "$NETKIT_HOME/bin/script_utils"
-
-# Write to the vcommands log
-log_write "$0 $*"
-
 
 ###############################################################################
 # Write vclean's usage line to standard output.
@@ -133,94 +120,6 @@ END_OF_HELP
 
    exit "$status"
 }
-
-
-# Get command line options
-LONG_OPTS="clean-all,help,kill-machines,quick,quiet,remove-hubs,remove-tunnels,test,user:,version"
-SHORT_OPTS="HKTu:q"
-
-if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
-   # getopt will output the errorneous command-line argument
-   usage 1
-fi
-
-# USER_ID is set in script_utils
-target_user=$USER_ID
-
-# (Safely) set positional parameters to those reordered by getopt
-eval set -- "$GETOPT_OPTS"
-
-while true; do
-   case $1 in
-      --clean-all)
-         KILL_MACHINES=1
-         REMOVE_TUNNELS=1
-         ;;
-      -H|--remove-hubs)
-         REMOVE_UNUSED_HUBS=1
-         ;;
-      --help)
-         usage 0
-         ;;
-      -K|--kill-machines)
-         KILL_MACHINES=1
-         ;;
-      # TODO: Separate options (and use --verbose)
-      -q|--quick|--quiet)
-         BE_QUIET=1
-         ;;
-      -T|--remove-tunnels)
-         REMOVE_TUNNELS=1
-         ;;
-      --test)
-         TEST_MODE=1
-         ;;
-      --user|-u)
-         target_user=$2
-         [ "$target_user" = "-" ] && unset target_user
-         shift
-         ;;
-      --version)
-         show_version
-         exit 0
-         ;;
-      --)
-         shift
-         break
-         ;;
-      *)
-         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
-         usage 1
-         ;;
-   esac
-
-   shift
-done
-
-# Check for further arguments
-if [ $# -gt 0 ]; then
-   echo 1>&2 "$SCRIPTNAME: Too many arguments"
-   usage 1
-   exit 1
-fi
-
-
-# Test mode is senseless if working in quiet mode
-if [ -n "$TEST_MODE" ] && [ -n "$BE_QUIET" ]; then
-   echo 1>&2 "$SCRIPTNAME: test mode cannot function in quiet mode"
-   exit 1
-fi
-
-# Actions --remove-hubs and --kill-machines are incompatible
-if [ -n "$REMOVE_UNUSED_HUBS" ] && [ -n "$KILL_MACHINES" ]; then
-   echo 1>&2 "$SCRIPTNAME: Hub removal and machine kill cannot be performed simultaneously"
-   exit 1
-fi
-
-# Enable default action (remove unused virtual hubs) if none has been requested
-if [ -z "$KILL_MACHINES" ] && [ -z "$REMOVE_TUNNELS" ]; then
-   REMOVE_UNUSED_HUBS=1
-fi
 
 
 ###############################################################################
@@ -336,6 +235,107 @@ kill_hubs() {
    [ -n "$found_unused_hub" ] && [ -z "$BE_QUIET" ] && echo "   No unused virtual hubs have been found."
 }
 
+
+SCRIPTNAME=$(basename "$0")
+
+if [ -z "$NETKIT_HOME" ]; then
+   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
+   exit 1
+fi
+
+# shellcheck source=./script_utils
+. "$NETKIT_HOME/bin/script_utils"
+
+# Write to the vcommands log
+log_write "$0 $*"
+
+
+target_user=$USER_ID
+
+
+# Get command line options
+LONG_OPTS="clean-all,help,kill-machines,quick,quiet,remove-hubs,remove-tunnels,test,user:,version"
+SHORT_OPTS="HKTu:q"
+
+if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
+   # getopt will output the errorneous command-line argument
+   usage 1
+fi
+
+# (Safely) set positional parameters to those reordered by getopt
+eval set -- "$GETOPT_OPTS"
+
+while true; do
+   case $1 in
+      --clean-all)
+         KILL_MACHINES=1
+         REMOVE_TUNNELS=1
+         ;;
+      -H|--remove-hubs)
+         REMOVE_UNUSED_HUBS=1
+         ;;
+      --help)
+         usage 0
+         ;;
+      -K|--kill-machines)
+         KILL_MACHINES=1
+         ;;
+      # TODO: Separate options (and use --verbose)
+      -q|--quick|--quiet)
+         BE_QUIET=1
+         ;;
+      -T|--remove-tunnels)
+         REMOVE_TUNNELS=1
+         ;;
+      --test)
+         TEST_MODE=1
+         ;;
+      --user|-u)
+         target_user=$2
+         [ "$target_user" = "-" ] && unset target_user
+         shift
+         ;;
+      --version)
+         show_version
+         exit 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
+         usage 1
+         ;;
+   esac
+
+   shift
+done
+
+# Check for further arguments
+if [ $# -gt 0 ]; then
+   echo 1>&2 "$SCRIPTNAME: Too many arguments"
+   usage 1
+   exit 1
+fi
+
+
+# Test mode is senseless if working in quiet mode
+if [ -n "$TEST_MODE" ] && [ -n "$BE_QUIET" ]; then
+   echo 1>&2 "$SCRIPTNAME: test mode cannot function in quiet mode"
+   exit 1
+fi
+
+# Actions --remove-hubs and --kill-machines are incompatible
+if [ -n "$REMOVE_UNUSED_HUBS" ] && [ -n "$KILL_MACHINES" ]; then
+   echo 1>&2 "$SCRIPTNAME: Hub removal and machine kill cannot be performed simultaneously"
+   exit 1
+fi
+
+# Enable default action (remove unused virtual hubs) if none has been requested
+if [ -z "$KILL_MACHINES" ] && [ -z "$REMOVE_TUNNELS" ]; then
+   REMOVE_UNUSED_HUBS=1
+fi
 
 
 if [ -z "$target_user" ]; then
diff --git a/core/bin/vconf b/core/bin/vconf
--- a/core/bin/vconf
+++ b/core/bin/vconf
@@ -18,25 +18,12 @@
 #     You should have received a copy of the GNU General Public License
 #     along with Netkit.  If not, see <http://www.gnu.org/licenses/>.
 
-# This is the Netkit vconfig script, which allows to attach virtual
-# machine interfaces on the fly. Interface detaching is not supported,
-# because the release function for uml-netdev0 is still under development.
-# This script already supports interface removal, which can be achieved by
-# using an empty collision domain name for an interface. Yet, this feature
-# is currently hidden by a check on the presence of a valid collision domain name.
-
-SCRIPTNAME=$(basename "$0")
-
-if [ -z "$NETKIT_HOME" ]; then
-   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
-   exit 1
-fi
-
-# shellcheck source=./script_utils
-. "$NETKIT_HOME/bin/script_utils"
-
-# Write to the vcommands log
-log_write "$0 $*"
+# This is the Netkit vconfig script, which allows to attach virtual machine
+# interfaces on the fly. Interface detaching is not supported, because the
+# release function for uml-netdev0 is still under development. This script
+# already supports interface removal, which can be achieved by using an empty
+# collision domain name for an interface. Yet, this feature is currently hidden
+# by a check on the presence of a valid collision domain name.
 
 
 ###############################################################################
@@ -136,103 +123,6 @@ END_OF_HELP
 
    exit "$status"
 }
-
-
-# Get command line options
-LONG_OPTS="help,print,quiet,version,user:"
-SHORT_OPTS="pqu:"
-
-i=0
-while [ "$i" -lt "$MAX_INTERFACES" ]; do
-   LONG_OPTS="$LONG_OPTS,eth$i:"
-   i=$((i + 1))
-done
-
-if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
-   # getopt will output the errorneous command-line argument
-   usage 1
-fi
-
-target_user=$USER_ID
-
-# (Safely) set positional parameters to those reordered by getopt
-eval set -- "$GETOPT_OPTS"
-
-while true; do
-   case $1 in
-      --eth*)
-         interface=${1#--}
-         DOMAIN=$2
-         shift
-
-         if string_contains "_" "$DOMAIN"; then
-            echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - underscores are not allowed"
-            usage 1
-         fi
-
-         if string_contains "," "$DOMAIN" || string_contains "." "$DOMAIN"; then
-            # If not a tap specification, but its name contains a comma
-            if [ "${DOMAIN#tap,}" = "$DOMAIN" ]; then
-               echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - commas and periods are only valid for tap interface specification"
-               usage 1
-            fi
-         fi
-
-         if string_contains " " "$DOMAIN"; then
-            echo 1>&2 "$SCRIPTNAME: $DOMAIN: Collision domain name cannot contain whitespace"
-            exit 1
-         fi
-
-         # Construct array of ethN=DOMAIN
-         network_interfaces+=( "$interface=$DOMAIN" )
-         ;;
-      --help)
-         usage 0
-         ;;
-      -p|--print)
-         JUST_PRINT=1
-         ;;
-      -q|--quiet)
-         BE_QUIET=1
-         ;;
-      -u|--user)
-         target_user=$2
-         [ "$target_user" = "-" ] && unset target_user
-         shift
-         ;;
-      --version)
-         show_version
-         exit 0
-         ;;
-      --)
-         shift
-         break
-         ;;
-      *)
-         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
-         usage 1
-         ;;
-   esac
-
-   shift
-done
-
-
-if [ $# -eq 0 ]; then
-   echo 1>&2 "$SCRIPTNAME: Missing machine name"
-   usage 1
-elif [ $# -gt 1 ]; then
-   echo 1>&2 "$SCRIPTNAME: Can only specify one machine"
-   usage 1
-fi
-
-# Parse virtual machine name
-VM_ID=$1
-if string_contains " " "$VM_ID"; then
-   echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
-   exit 1
-fi
-shift
 
 
 ###############################################################################
@@ -365,7 +255,118 @@ invoke_mconsole() {
 }
 
 
-############################# Configure interfaces ############################
+SCRIPTNAME=$(basename "$0")
+
+if [ -z "$NETKIT_HOME" ]; then
+   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
+   exit 1
+fi
+
+# shellcheck source=./script_utils
+. "$NETKIT_HOME/bin/script_utils"
+
+# Write to the vcommands log
+log_write "$0 $*"
+
+
+target_user=$USER_ID
+
+
+# Get command line options
+LONG_OPTS="help,print,quiet,version,user:"
+SHORT_OPTS="pqu:"
+
+i=0
+while [ "$i" -lt "$MAX_INTERFACES" ]; do
+   LONG_OPTS="$LONG_OPTS,eth$i:"
+   i=$((i + 1))
+done
+
+if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
+   # getopt will output the errorneous command-line argument
+   usage 1
+fi
+
+# (Safely) set positional parameters to those reordered by getopt
+eval set -- "$GETOPT_OPTS"
+
+while true; do
+   case $1 in
+      --eth*)
+         interface=${1#--}
+         DOMAIN=$2
+         shift
+
+         if string_contains "_" "$DOMAIN"; then
+            echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - underscores are not allowed"
+            usage 1
+         fi
+
+         if string_contains "," "$DOMAIN" || string_contains "." "$DOMAIN"; then
+            # If not a tap specification, but its name contains a comma
+            if [ "${DOMAIN#tap,}" = "$DOMAIN" ]; then
+               echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - commas and periods are only valid for tap interface specification"
+               usage 1
+            fi
+         fi
+
+         if string_contains " " "$DOMAIN"; then
+            echo 1>&2 "$SCRIPTNAME: $DOMAIN: Collision domain name cannot contain whitespace"
+            exit 1
+         fi
+
+         # Construct array of ethN=DOMAIN
+         network_interfaces+=( "$interface=$DOMAIN" )
+         ;;
+      --help)
+         usage 0
+         ;;
+      -p|--print)
+         JUST_PRINT=1
+         ;;
+      -q|--quiet)
+         BE_QUIET=1
+         ;;
+      -u|--user)
+         target_user=$2
+         [ "$target_user" = "-" ] && unset target_user
+         shift
+         ;;
+      --version)
+         show_version
+         exit 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
+         usage 1
+         ;;
+   esac
+
+   shift
+done
+
+# Parse virtual machine name
+if [ $# -eq 0 ]; then
+   echo 1>&2 "$SCRIPTNAME: Missing machine name"
+   usage 1
+elif [ $# -gt 1 ]; then
+   echo 1>&2 "$SCRIPTNAME: Can only specify one machine"
+   usage 1
+fi
+
+VM_ID=$1
+shift
+
+if string_contains " " "$VM_ID"; then
+   echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+   exit 1
+fi
+
+
 if ! get_machine_state "$target_user" "$VM_ID"; then
    echo -n 1>&2 "$SCRIPTNAME: no virtual machine named '$VM_ID' exists"
    [ -n "$target_user" ] && echo " for user $target_user." || echo "."
@@ -373,20 +374,19 @@ if ! get_machine_state "$target_user" "$VM_ID"; then
 fi
 
 
+# Setup network interfaces
 if [ -z "$BE_QUIET" ]; then
    echo "============= Configuring virtual machine '$VM_ID' (PID $(get_vm_pid_by_name "$user" "$vm")) ============="
    echo "   Virtual machine owner: $target_user"
 fi
 
-
-##### Setup network interfaces
 if [ ${#network_interfaces[@]} -gt 0 ]; then
    [ -z "$BE_QUIET" ] && echo -n "   Interfaces: "
    setup_interfaces "${network_interfaces[@]}"
 fi
 
-##### Start network hubs
+# Start network hubs
 run_hubs "${HUBLIST[@]}"
 
-##### Attach/remove network interfaces
+# Attach/remove network interfaces
 invoke_mconsole "${MCONSOLE_CMD[@]}"
diff --git a/core/bin/vcrash b/core/bin/vcrash
--- a/core/bin/vcrash
+++ b/core/bin/vcrash
@@ -23,19 +23,6 @@
 # their power cord. This script is also useful if you want to kill a hanging
 # virtual machine.
 
-SCRIPTNAME=$(basename "$0")
-
-if [ -z "$NETKIT_HOME" ]; then
-   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
-   exit 1
-fi
-
-# shellcheck source=./script_utils
-. "$NETKIT_HOME/bin/script_utils"
-
-# Write to the vcommands log
-log_write "$0 $*"
-
 
 ###############################################################################
 # Write vcrash's usage line to standard output.
@@ -130,6 +117,187 @@ END_OF_HELP
 }
 
 
+###############################################################################
+# Kill a virtual machine by signaling the corresponding processes. It is
+# assumed that vm_info will be populated for disk removal.
+# Usage:
+#   kill_by_signaling MACHINE
+# Globals:
+#   r- BE_QUIET
+#   r- REMOVE_FS
+#   r- vm_info
+# Arguments:
+#   $1 - machine to kill
+# Returns:
+#   Returns zero on success, non-zero if there was an issue with killing the
+#   machine.
+# Example:
+#   None
+###############################################################################
+kill_by_signaling() {
+   vm=$1
+
+   [ -z "$BE_QUIET" ] && echo -n "Killing... "
+
+   # Signalling processes twice ensures they stop even if they need to be
+   # killed in a certain order
+   IFS=" " read -r -a pids <<< "$(get_vm_all_pids_by_name "$target_user" "$vm")"
+
+   if [ "${#pids[@]}" -eq 0 ]; then
+      kill -TERM "${pids[@]}" > /dev/null
+      kill -TERM "${pids[@]}" > /dev/null
+   fi
+
+   if [ -z "$BE_QUIET" ]; then
+      sleep 1
+
+      if get_machine_state "$target_user" "$vm"; then
+         [ -z "$BE_QUIET" ] && echo -n "killing harder... "
+         # Recompute PID list (some threads may have been launched in the
+         # meantime).
+         IFS=" " read -r -a pids <<< "$(get_vm_all_pids_by_name "$target_user" "$vm")"
+
+         if [ "${#pids[@]}" -eq 0 ]; then
+            kill -KILL "${pids[@]}" > /dev/null
+            kill -CONT "${pids[@]}" > /dev/null
+         fi
+
+         sleep 1
+
+         if get_machine_state "$target_user" "$vm"; then
+            [ -z "$BE_QUIET" ] && echo "failed!"
+            echo 1>&2 "Failed to crash virtual machine '$vm'"
+            return 1
+         fi
+      fi
+
+      [ -z "$BE_QUIET" ] && echo "done."
+   fi
+
+   # Virtual machine filesystem is removed only if it has been successfully crashed
+   [ -n "$REMOVE_FS" ] && [ -n "${vm_info[disk]}" ] && remove_fs "${vm_info[disk]}"
+   
+   return 0
+}
+
+
+###############################################################################
+# Use uml_mconsole to crash a machine. It is assumed that vm_info will be
+# populated for the mconsole directory.
+# NOTE: we can remove the reliance on vm_info by building the dir path here.
+# Usage:
+#   mconsole_halt
+# Globals:
+#   r- BE_QUIET
+#   r- NETKIT_HOME
+#   r- vm_info
+# Arguments:
+#   None
+# Returns:
+#   Returns zero on success, non-zero if there was an issue with killing the
+#   machine.
+# Example:
+#   None
+###############################################################################
+mconsole_halt() {
+   "$NETKIT_HOME/bin/uml_mconsole" "${vm_info[mconsole]}" halt > /dev/null &
+   uml_mconsole_pid=$!
+
+   # Check whether the mconsole process is hanging forever
+   i=0
+   while [ $i -le 5 ]; do
+      [ ! -e "/proc/$uml_mconsole_pid" ] && return 0
+      [ $i -lt 5 ] && sleep 1
+      i=$((i + 1))
+   done
+
+   [ -z "$BE_QUIET" ] && echo "hangup detected... "
+   kill "$uml_mconsole_pid"
+
+   return 1
+}
+
+
+###############################################################################
+# Use mconsole_halt to crash a machine and, if BE_QUIET is empty, upon failure
+# twice, resort to kill_by_signaling. It is assumed that vm_info will be
+# populated.
+# Usage:
+#   kill_by_mconsole MACHINE
+# Globals:
+#   r- BE_QUIET
+#   r- REMOVE_FS
+#   r- target_user
+#   r- vm_info
+# Arguments:
+#   None
+# Returns:
+#   Returns zero on success, non-zero if there was an issue with killing the
+#   machine.
+# Example:
+#   None
+###############################################################################
+kill_by_mconsole() {
+   vm=$1
+
+   [ -z "$BE_QUIET" ] && echo -n "Crashing... "
+
+   mconsole_halt
+
+   # When the above command exits, an attempt via the mconsole has been
+   # performed. Regardless of whether the virtual machine has actually halted,
+   # the above command ensures that the uml_mconsole process has ended.
+   if [ -z "$BE_QUIET" ]; then
+      # Make a second attempt if machine is still running
+      if get_machine_state "$target_user" "$vm"; then
+         echo -n "retrying... "
+         sleep 1
+
+         if ! mconsole_halt; then
+            # uml_mconsole is hanging forever
+            
+            # The two lines below are necessary in order to retrieve the
+            # virtual machine PIDs, which are required by kill_by_signaling.
+            # We chose not to retrieve them immediately because this requires
+            # time and is only necessary if mconsole does not work.
+            kill_by_signaling "$vm"
+            return $?
+         elif get_machine_state "$target_user" "$vm"; then
+            # Attempt to kill virtual machine processes
+            kill_by_signaling "$vm"
+            return $?
+         else
+            echo "done."
+         fi
+      else
+         echo "done."
+      fi
+   fi
+
+   # kill_by_signaling will handle filesystem removal, hence it exits early
+   [ -n "$REMOVE_FS" ] && [ -n "${vm_info[disk]}" ] && remove_fs "${vm_info[disk]}"
+
+   return 0
+}
+
+
+SCRIPTNAME=$(basename "$0")
+
+if [ -z "$NETKIT_HOME" ]; then
+   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
+   exit 1
+fi
+
+# shellcheck source=./script_utils
+. "$NETKIT_HOME/bin/script_utils"
+
+# Write to the vcommands log
+log_write "$0 $*"
+
+
+target_user=$USER_ID
+
+
 # Get command line options
 LONG_OPTS="force,help,kill,quiet,remove-fs,root,test,user:,version"
 SHORT_OPTS="kqru:"
@@ -138,8 +306,6 @@ if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longopt
    # getopt will output the errorneous command-line argument
    usage 1
 fi
-
-target_user=$USER_ID
 
 # (Safely) set positional parameters to those reordered by getopt
 eval set -- "$GETOPT_OPTS"
@@ -212,126 +378,6 @@ if [ -n "$TEST_MODE" ] && [ -n "$BE_QUIET" ]; then
    echo 1>&2 "$SCRIPTNAME: Option --test cannot be used when working in quiet mode"
    usage 1
 fi
-
-
-# This function kills a virtual machine by simply signaling the corresponding
-# processes. It is assumed that vm_info has been populated.
-kill_by_signaling() {
-   vm=$1
-
-   [ -z "$BE_QUIET" ] && echo -n "Killing... "
-
-   # Signalling processes twice ensures they stop even if they need to be
-   # killed in a certain order
-   IFS=" " read -r -a pids <<< "$(get_vm_all_pids_by_name "$target_user" "$vm")"
-
-   if [ "${#pids[@]}" -eq 0 ]; then
-      kill -TERM "${pids[@]}" > /dev/null
-      kill -TERM "${pids[@]}" > /dev/null
-   fi
-
-   if [ -z "$BE_QUIET" ]; then
-      sleep 1
-
-      if get_machine_state "$target_user" "$vm"; then
-         [ -z "$BE_QUIET" ] && echo -n "killing harder... "
-         # Recompute PID list (some threads may have been launched in the
-         # meantime).
-         IFS=" " read -r -a pids <<< "$(get_vm_all_pids_by_name "$target_user" "$vm")"
-
-         if [ "${#pids[@]}" -eq 0 ]; then
-            kill -KILL "${pids[@]}" > /dev/null
-            kill -CONT "${pids[@]}" > /dev/null
-         fi
-
-         sleep 1
-
-         if get_machine_state "$target_user" "$vm"; then
-            [ -z "$BE_QUIET" ] && echo "failed!"
-            echo 1>&2 "Failed to crash virtual machine '$vm'"
-            return 1
-         fi
-      fi
-
-      [ -z "$BE_QUIET" ] && echo "done."
-   fi
-
-   # Virtual machine filesystem is removed only if it has been successfully crashed
-   [ -n "$REMOVE_FS" ] && [ -n "${vm_info[disk]}" ] && remove_fs "${vm_info[disk]}"
-   
-   return 0
-}
-
-
-
-# This function uses a virtual machine management console to immediately crash
-# it. The function also takes care of handling the case in which uml_console
-# freezes. In such a situations, it kills the uml_mconsole process and returns
-# a non-zero value. Please note that the function only fails when uml_mconsole
-# hangs, regardless of whether the virtual machine has been actually crashed
-# or not. Here it is assumed that vm_info has been populated.
-mconsole_halt() {
-   "$NETKIT_HOME/bin/uml_mconsole" "${vm_info[mconsole]}" halt > /dev/null &
-   uml_mconsole_pid=$!
-
-   # Check whether the mconsole process is hanging forever
-   i=0
-   while [ $i -le 5 ]; do
-      [ ! -e "/proc/$uml_mconsole_pid" ] && return 0
-      [ $i -lt 5 ] && sleep 1
-      i=$((i + 1))
-   done
-
-   [ -z "$BE_QUIET" ] && echo "hangup detected... "
-   kill "$uml_mconsole_pid"
-
-   return 1
-}
-
-
-
-# This function kills a virtual machine by using their management console
-# (mconsole) socket. Upon failure, it reverts to killing the virtual machine
-# processes. It assumes that vm_info has been populated.
-kill_by_mconsole() {
-   vm=$1
-
-   [ -z "$BE_QUIET" ] && echo -n "Crashing... "
-
-   mconsole_halt
-
-   # When the above command exits, an attempt via the mconsole has been
-   # performed. Regardless of whether the virtual machine has actually halted,
-   # the above command ensures that the uml_mconsole process has ended.
-   if [ -z "$BE_QUIET" ]; then
-      # Make a second attempt if machine is still running
-      if get_machine_state "$target_user" "$vm"; then
-         echo -n "retrying... "
-         sleep 1
-
-         if ! mconsole_halt; then
-            # uml_mconsole is hanging forever
-            
-            # The two lines below are necessary in order to retrieve the
-            # virtual machine PIDs, which are required by kill_by_signaling.
-            # We chose not to retrieve them immediately because this requires
-            # time and is only necessary if mconsole does not work.
-            kill_by_signaling "$vm"
-            return $?
-         elif get_machine_state "$target_user" "$vm"; then
-            # Attempt to kill virtual machine processes
-            kill_by_signaling "$vm"
-            return $?
-         else
-            echo "done."
-         fi
-      else
-         echo "done."
-      fi
-   fi
-
-   [ -n "$REMOVE_FS" ] && [ -n "${vm_info[disk]}" ] && remove_fs "${vm_info[disk]}"
-}
 
 
 for vm in "${vm_ids[@]}"; do
diff --git a/core/bin/vlist b/core/bin/vlist
--- a/core/bin/vlist
+++ b/core/bin/vlist
@@ -175,91 +175,6 @@ print_vm_summary() {
 }
 
 
-SCRIPTNAME=$(basename "$0")
-
-if [ -z "$NETKIT_HOME" ]; then
-   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
-   exit 1
-fi
-
-# shellcheck source=./lcommon
-. "$NETKIT_HOME/bin/lcommon"
-# shellcheck source=./script_utils
-. "$NETKIT_HOME/bin/script_utils"
-
-# Write to the vcommands log
-log_write "$0 $*"
-
-
-# Get command line options
-LONG_OPTS="help,no-header,user:,version"
-SHORT_OPTS="nu:"
-
-if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
-   # getopt will output the errorneous command-line argument
-   usage 1
-fi
-
-# USER_ID is set in script_utils
-target_user=$USER_ID
-
-# (Safely) set positional parameters to those reordered by getopt
-eval set -- "$GETOPT_OPTS"
-
-while true; do
-   case $1 in
-      --help)
-         usage 0
-         ;;
-      -n|--no-header)
-         no_header=true
-         ;;
-      -u|--user)
-         target_user=$2
-         [ "$target_user" = "-" ] && unset target_user
-         shift
-         ;;
-      --version)
-         show_version
-         exit 0
-         ;;
-      --)
-         shift
-         break
-         ;;
-      *)
-         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
-         usage 1
-         ;;
-   esac
-
-   shift
-done
-
-# Non-option arguments are machine names
-vm_ids=( "$@" )
-
-for host in "${vm_ids[@]}"; do
-   if string_contains " " "$host"; then
-      echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
-      exit 1
-   fi
-done
-
-
-# Check whether -u - is being used together with a virtual machine ID
-if [ -z "$target_user" ] && [ "${#vm_ids[@]}" -ne 0 ]; then
-   echo 1>&2 "$SCRIPTNAME: When giving VM names, a specific user ID must be provided"
-   usage 1
-fi
-
-
-# Display summary of virtual machines
-if [ "${#vm_ids[@]}" -eq 0 ]; then
-   print_vm_summary "$no_header" "$target_user"
-fi
-
-
 ###############################################################################
 # Print complete information about a machine.
 # Usage:
@@ -343,6 +258,91 @@ print_vm_info_by_name() {
    echo "   Other arguments:   ${vm_info[other]:-"-"}"
    echo "   Console socket:    ${vm_info[mconsole]}"
 }
+
+
+SCRIPTNAME=$(basename "$0")
+
+if [ -z "$NETKIT_HOME" ]; then
+   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
+   exit 1
+fi
+
+# shellcheck source=./lcommon
+. "$NETKIT_HOME/bin/lcommon"
+# shellcheck source=./script_utils
+. "$NETKIT_HOME/bin/script_utils"
+
+# Write to the vcommands log
+log_write "$0 $*"
+
+
+target_user=$USER_ID
+
+
+# Get command line options
+LONG_OPTS="help,no-header,user:,version"
+SHORT_OPTS="nu:"
+
+if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
+   # getopt will output the errorneous command-line argument
+   usage 1
+fi
+
+# (Safely) set positional parameters to those reordered by getopt
+eval set -- "$GETOPT_OPTS"
+
+while true; do
+   case $1 in
+      --help)
+         usage 0
+         ;;
+      -n|--no-header)
+         no_header=true
+         ;;
+      -u|--user)
+         target_user=$2
+         [ "$target_user" = "-" ] && unset target_user
+         shift
+         ;;
+      --version)
+         show_version
+         exit 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
+         usage 1
+         ;;
+   esac
+
+   shift
+done
+
+# Non-option arguments are machine names
+vm_ids=( "$@" )
+
+for host in "${vm_ids[@]}"; do
+   if string_contains " " "$host"; then
+      echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
+      exit 1
+   fi
+done
+
+
+# Check whether -u - is being used together with a virtual machine ID
+if [ -z "$target_user" ] && [ "${#vm_ids[@]}" -ne 0 ]; then
+   echo 1>&2 "$SCRIPTNAME: When giving VM names, a specific user ID must be provided"
+   usage 1
+fi
+
+
+# Display summary of virtual machines
+if [ "${#vm_ids[@]}" -eq 0 ]; then
+   print_vm_summary "$no_header" "$target_user"
+fi
 
 
 # Get verbose information for specific virtual machines
diff --git a/core/bin/vstart b/core/bin/vstart
--- a/core/bin/vstart
+++ b/core/bin/vstart
@@ -21,19 +21,6 @@
 # This is the Netkit vstart script, which is used to start virtual machines with
 # given parameters.
 
-SCRIPTNAME=$(basename "$0")
-
-if [ -z "$NETKIT_HOME" ]; then
-   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
-   exit 1
-fi
-
-# shellcheck source=./script_utils
-. "$NETKIT_HOME/bin/script_utils"
-
-# Write to the vcommands log
-log_write "$0 $*"
-
 
 ###############################################################################
 # Write vstart's usage line to standard output.
@@ -204,6 +191,217 @@ END_OF_HELP
 
    exit "$status"
 }
+
+
+###############################################################################
+# Warn if file is located on a filesystem that does not support sparse files.
+# Usage:
+#   check_filesystem FILE
+# Globals:
+#   r- SCRIPTNAME
+# Arguments:
+#   $1 - file on target filesystem
+# Returns:
+#   None
+# Example:
+#   None
+###############################################################################
+check_filesystem() {
+   file=$1
+
+   fs_type=$(stat -f "$file" | grep -w Type)
+   fs_type=${fs_type#*Type: }
+
+   if [[ "$fs_type" =~ ^(ext[2-4]|ntfs|ntfs-3g|fuse|reiser|jfs|xfs)$ ]]; then
+      echo 1>&2 "$SCRIPTNAME: Filesystem '$fs_type' does not seem to support sparse files, this may result in performance loss and disk space consumption"
+   fi
+}
+
+
+###############################################################################
+# Append network interface specifications to the kernel invocation command.
+# Usage:
+#   setup_interfaces [INTERFACE]...
+# Globals:
+#   r- BE_QUIET
+#   -w HUBLIST
+#   r- HUB_SOCKET_DIR
+#   r- HUB_SOCKET_EXTENSION
+#   r- HUB_SOCKET_PREFIX
+#   r- KERNELCMD
+#   r- SCRIPTNAME
+#   r- USER_ID
+# Arguments:
+#  ... - list of interfaces
+# Returns:
+#   None. Will exit with usage 1 on invalid specification.
+# Example:
+#   None
+###############################################################################
+setup_interfaces() {
+   local device hub_name hub_socket tap_address
+   local guest_address enabled_default_route used_devices
+   
+   first_iteration=true
+   while [ $# -gt 0 ]; do
+      device=${1%%=*}
+      hub_specification=${1#*=}
+
+      # Check if interface has already been configured
+      if [[ " $used_devices " == *" $device "* ]]; then
+         echo 1>&2 "$SCRIPTNAME: $device: Duplicate interface"
+         usage 1
+      fi
+
+      # Remember that this network interface has been configured
+      used_devices="$used_devices $device"
+
+      # Check if tap interface (regular hubs cannot be named with commas)
+      if [[ "$hub_specification" == tap,* ]]; then
+         # Format: tap,tap_address,guest_address
+         IFS=, read -r hub_name tap_address guest_address <<< "$hub_specification"
+
+         if ! is_inet_addr "$tap_address"; then
+            echo 1>&2 "$SCRIPTNAME: $tap_address: Invalid tap address"
+            usage 1
+         fi
+
+         if ! is_inet_addr "$guest_address"; then
+            echo 1>&2 "$SCRIPTNAME: $guest_address: Invalid guest address"
+            usage 1
+         fi
+      else
+         # This is a normal (i.e., not 'tap') collision domain
+         unset tap_address guest_address
+         hub_name=$hub_specification
+      fi
+      
+      hub_socket="$HUB_SOCKET_DIR/${HUB_SOCKET_PREFIX}_${USER_ID}_$hub_name$HUB_SOCKET_EXTENSION"
+
+      KERNELCMD="$KERNELCMD $device=daemon,,,$hub_socket"
+      
+      if [ -n "$tap_address" ]; then
+         HUBLIST+=( "$hub_name,$tap_address" )
+
+         KERNELCMD="$KERNELCMD autoconf_$device=$guest_address"
+
+         # TODO: KERNELCMD is an array now
+         # Ensure the default route is specified only once
+         if [ -z "$enabled_default_route" ]; then
+            KERNELCMD="$KERNELCMD def_route=$tap_address"
+            enabled_default_route=1
+         fi
+      else
+         HUBLIST+=( "$hub_name" )
+      fi
+
+      if $first_iteration; then
+         first_iteration=false
+      elif [ -z "$BE_QUIET" ]; then
+         echo -n "               "
+      fi
+
+      [ -z "$BE_QUIET" ] && echo "$device @ $hub_name ($hub_socket)"
+
+      shift
+   done
+}
+
+
+###############################################################################
+# Invoke uml_mconsole to "wake up" port-helper in the event that it hangs.
+# Usage:
+#   wakeup_porthelper
+# Globals:
+#   r- NETKIT_HOME
+#   r- VM_NAME
+# Arguments:
+#   None
+# Returns:
+#   None
+# Example:
+#   None
+###############################################################################
+wakeup_porthelper() {
+   sleep 5
+   "$NETKIT_HOME/bin/uml_mconsole" "$VM_NAME" help > /dev/null 2>&1 &
+}
+
+
+###############################################################################
+# Delete .disk file as soon as it is created by the UML instance.
+# Usage:
+#   remove_fs_command
+# Globals:
+#   r- VM_FS
+# Arguments:
+#   None
+# Returns:
+#   None
+# Example:
+#   remove_fs_command &
+###############################################################################
+remove_fs_command() {
+   while [ ! -f "$VM_FS" ]; do
+      sleep 1
+   done
+   
+   rm -f "$VM_FS" 
+}
+
+
+###############################################################################
+# Run relevant kernel invocation setup functions and then invoke the UML kernel
+# instance. Upon return, clean up redundant network hubs.
+# Usage:
+#   run_kernel_command
+# Globals:
+#   r- CON0_PORTHELPER
+#   r- HUBLIST
+#   r- JUST_PRINT
+#   r- KERNELCMD
+#   r- REMOVE_FS
+# Arguments:
+#   None
+# Returns:
+#   None
+# Example:
+#   None
+###############################################################################
+run_kernel_command() {
+   # If doing a dry run, we want to skip all four commands here.
+   if [ -n "$JUST_PRINT" ]; then
+      run_command "$JUST_PRINT" "${KERNELCMD[*]}" "${KERNELCMD[@]}"
+      return
+   fi
+
+   # Invocation of uml_mconsole is needed in order to "wake up" port-helper if
+   # it ever hangs when booting the virtual machine.
+   [ "$CON0_PORTHELPER" = "yes" ] && wakeup_porthelper
+   
+   # Remove .disk file, if requested
+   if [ -n "$REMOVE_FS" ]; then
+      remove_fs_command &
+   fi
+
+   run_command "$JUST_PRINT" "${KERNELCMD[*]}" "${KERNELCMD[@]}"
+
+   clean_hubs "${HUBLIST[@]}"
+}
+
+
+SCRIPTNAME=$(basename "$0")
+
+if [ -z "$NETKIT_HOME" ]; then
+   echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not set"
+   exit 1
+fi
+
+# shellcheck source=./script_utils
+. "$NETKIT_HOME/bin/script_utils"
+
+# Write to the vcommands log
+log_write "$0 $*"
 
 
 # Get command line options
@@ -386,7 +584,7 @@ while true; do
    shift
 done
 
-
+# Parse virtual machine name
 if [ $# -eq 0 ]; then
    echo 1>&2 "$SCRIPTNAME: Missing machine name"
    usage 1
@@ -395,13 +593,13 @@ elif [ $# -gt 1 ]; then
    usage 1
 fi
 
-# Parse virtual machine name
 VM_NAME=$1
+shift
+
 if string_contains " " "$VM_NAME"; then
    echo 1>&2 "$SCRIPTNAME: Hostname cannot contain whitespace"
    exit 1
 fi
-shift
 
 
 # Check whether user is trying to attach more than one console to stdin/stdout
@@ -447,124 +645,7 @@ if [ "$VM_CON0" = "tmux" ] && [ "$TMUX_OPEN_TERMS" = "yes" ] || [ "$VM_CON0" = "
 fi
 
 
-########################## Build kernel command line ##########################
-
-
-###############################################################################
-# Warn if file is located on a filesystem that does not support sparse files.
-# Usage:
-#   check_filesystem FILE
-# Globals:
-#   r- SCRIPTNAME
-# Arguments:
-#   $1 - file on target filesystem
-# Returns:
-#   None
-# Example:
-#   None
-###############################################################################
-check_filesystem() {
-   file=$1
-
-   fs_type=$(stat -f "$file" | grep -w Type)
-   fs_type=${fs_type#*Type: }
-
-   if [[ "$fs_type" =~ ^(ext[2-4]|ntfs|ntfs-3g|fuse|reiser|jfs|xfs)$ ]]; then
-      echo 1>&2 "$SCRIPTNAME: Filesystem '$fs_type' does not seem to support sparse files, this may result in performance loss and disk space consumption"
-   fi
-}
-
-
-###############################################################################
-# Append network interface specifications to the kernel invocation command.
-# Usage:
-#   setup_interfaces [INTERFACE]...
-# Globals:
-#   r- BE_QUIET
-#   -w HUBLIST
-#   r- HUB_SOCKET_DIR
-#   r- HUB_SOCKET_EXTENSION
-#   r- HUB_SOCKET_PREFIX
-#   r- KERNELCMD
-#   r- SCRIPTNAME
-#   r- USER_ID
-# Arguments:
-#  ... - list of interfaces
-# Returns:
-#   None. Will exit with usage 1 on invalid specification.
-# Example:
-#   None
-###############################################################################
-setup_interfaces() {
-   local device hub_name hub_socket tap_address
-   local guest_address enabled_default_route used_devices
-   
-   first_iteration=true
-   while [ $# -gt 0 ]; do
-      device=${1%%=*}
-      hub_specification=${1#*=}
-
-      # Check if interface has already been configured
-      if [[ " $used_devices " == *" $device "* ]]; then
-         echo 1>&2 "$SCRIPTNAME: $device: Duplicate interface"
-         usage 1
-      fi
-
-      # Remember that this network interface has been configured
-      used_devices="$used_devices $device"
-
-      # Check if tap interface (regular hubs cannot be named with commas)
-      if [[ "$hub_specification" == tap,* ]]; then
-         # Format: tap,tap_address,guest_address
-         IFS=, read -r hub_name tap_address guest_address <<< "$hub_specification"
-
-         if ! is_inet_addr "$tap_address"; then
-            echo 1>&2 "$SCRIPTNAME: $tap_address: Invalid tap address"
-            usage 1
-         fi
-
-         if ! is_inet_addr "$guest_address"; then
-            echo 1>&2 "$SCRIPTNAME: $guest_address: Invalid guest address"
-            usage 1
-         fi
-      else
-         # This is a normal (i.e., not 'tap') collision domain
-         unset tap_address guest_address
-         hub_name=$hub_specification
-      fi
-      
-      hub_socket="$HUB_SOCKET_DIR/${HUB_SOCKET_PREFIX}_${USER_ID}_$hub_name$HUB_SOCKET_EXTENSION"
-
-      KERNELCMD="$KERNELCMD $device=daemon,,,$hub_socket"
-      
-      if [ -n "$tap_address" ]; then
-         HUBLIST+=( "$hub_name,$tap_address" )
-
-         KERNELCMD="$KERNELCMD autoconf_$device=$guest_address"
-
-         # TODO: KERNELCMD is an array now
-         # Ensure the default route is specified only once
-         if [ -z "$enabled_default_route" ]; then
-            KERNELCMD="$KERNELCMD def_route=$tap_address"
-            enabled_default_route=1
-         fi
-      else
-         HUBLIST+=( "$hub_name" )
-      fi
-
-      if $first_iteration; then
-         first_iteration=false
-      elif [ -z "$BE_QUIET" ]; then
-         echo -n "               "
-      fi
-
-      [ -z "$BE_QUIET" ] && echo "$device @ $hub_name ($hub_socket)"
-
-      shift
-   done
-}
-
-
+# Start building the kernel command line
 KERNELCMD=( "$VM_KERNEL" )
 
 
@@ -592,17 +673,17 @@ if [ -d "$KERNEL_MODULES_DIRECTORY" ]; then
 fi
 
 
-##### Set virtual machine name
+# Set virtual machine name
 KERNELCMD+=( "name=$VM_NAME" "title=$VM_NAME" "umid=$VM_NAME" )
 
 
-##### Set memory amount
+# Set memory amount
 [ -z "$BE_QUIET" ] && echo "   Memory:     $VM_MEMORY MB"
 VM_MEMORY=$((VM_MEMORY + VM_MEMORY_SKEW))
 KERNELCMD+=( "mem=${VM_MEMORY}M" )
 
 
-##### Filesystem settings
+# Filesystem settings
 [ -z "$BE_QUIET" ] && echo "   Model fs:   $VM_MODEL_FS"
 
 if [ -n "$USE_MODEL_FS" ]; then
@@ -623,46 +704,47 @@ else
    [ -z "$BE_QUIET" ] && [ ! -f "$VM_FS" ] && echo " (new)" || echo
 fi
 
-# Append a boot option that specifies the root filesystem
+
+# Append a boot option that specifies the root filesystem.
+# NOTE: The following root= options should also be valid: /dev/ubda1 and
+# /dev/ubd/disc0/part1.
 KERNELCMD+=( "root=98:0" )
 
-# The following root= options should also be valid
-# KERNELCMD="$KERNELCMD root=/dev/ubd/disc0/part1"
-# KERNELCMD="$KERNELCMD root=/dev/ubda1"
 
-
-##### Setup mconsole directory
+# Setup mconsole directory
 KERNELCMD+=( "uml_dir=$MCONSOLE_DIR" )
 
 
-##### Setup network interfaces
+# Setup network interfaces
 if [ -n "$ETH_INTERFACES" ]; then
    [ -z "$BE_QUIET" ] && echo -n "   Interfaces: "
+   # TODO: Fix SC2086
    setup_interfaces $ETH_INTERFACES
 fi
 
-##### Set HOSTHOME
+
+# Set host home directory path
 if [ -z "$NO_HOSTHOME" ]; then
    [ -z "$BE_QUIET" ] && echo "   Hostfs at:  $HOME"
    KERNELCMD+=( "hosthome=$HOME" )
 fi
 
 
-##### Check whether virtual machine already exists
+# Check whether the virtual machine already exists
 if [ -z "$JUST_PRINT" ] && get_machine_state "$USER_ID" "$VM_NAME"; then
    echo 1>&2 "$SCRIPTNAME: Virtual machine '$VM_NAME' is already running. Please halt it before starting a new one or use a different virtual machine name"
    exit 1
 fi
 
 
-##### Check whether filesystem is already in use
+# Check whether filesystem is already in use
 if [ -z "$JUST_PRINT" ] && file_in_use "$VM_FS"; then
    echo 1>&2 "$SCRIPTNAME: Filesystem '$VM_FS' is already in use. Please use a different filesystem or virtual machine name"
    exit 1
 fi
 
 
-##### Append exec, hostlab and hostwd parameters, if any
+# Append exec, hostlab and hostwd parameters, if any
 if [ -n "$VM_EXEC" ]; then
    [ -z "$BE_QUIET" ] && echo "   Boot cmd:   '$VM_EXEC'"
    KERNELCMD+=( "exec=$VM_EXEC" )
@@ -743,88 +825,6 @@ fi
 
 # Actually start network hubs
 run_hubs "${HUBLIST[@]}"
-
-
-###############################################################################
-# Invoke uml_mconsole to "wake up" port-helper in the event that it hangs.
-# Usage:
-#   wakeup_porthelper
-# Globals:
-#   r- NETKIT_HOME
-#   r- VM_NAME
-# Arguments:
-#   None
-# Returns:
-#   None
-# Example:
-#   None
-###############################################################################
-wakeup_porthelper() {
-   sleep 5
-   "$NETKIT_HOME/bin/uml_mconsole" "$VM_NAME" help > /dev/null 2>&1 &
-}
-
-
-###############################################################################
-# Delete .disk file as soon as it is created by the UML instance.
-# Usage:
-#   remove_fs_command
-# Globals:
-#   r- VM_FS
-# Arguments:
-#   None
-# Returns:
-#   None
-# Example:
-#   remove_fs_command &
-###############################################################################
-remove_fs_command() {
-   while [ ! -f "$VM_FS" ]; do
-      sleep 1
-   done
-   
-   rm -f "$VM_FS" 
-}
-
-
-###############################################################################
-# Run relevant kernel invocation setup functions and then invoke the UML kernel
-# instance. Upon return, clean up redundant network hubs.
-# Usage:
-#   run_kernel_command
-# Globals:
-#   r- CON0_PORTHELPER
-#   r- HUBLIST
-#   r- JUST_PRINT
-#   r- KERNELCMD
-#   r- REMOVE_FS
-# Arguments:
-#   None
-# Returns:
-#   None
-# Example:
-#   None
-###############################################################################
-run_kernel_command() {
-   # If doing a dry run, we want to skip all four commands here.
-   if [ -n "$JUST_PRINT" ]; then
-      run_command "$JUST_PRINT" "${KERNELCMD[*]}" "${KERNELCMD[@]}"
-      return
-   fi
-
-   # Invocation of uml_mconsole is needed in order to "wake up" port-helper if
-   # it ever hangs when booting the virtual machine.
-   [ "$CON0_PORTHELPER" = "yes" ] && wakeup_porthelper
-   
-   # Remove .disk file, if requested
-   if [ -n "$REMOVE_FS" ]; then
-      remove_fs_command &
-   fi
-
-   run_command "$JUST_PRINT" "${KERNELCMD[*]}" "${KERNELCMD[@]}"
-
-   clean_hubs "${HUBLIST[@]}"
-}
 
 
 # Completely hide primary console, if requested to
