reformat all warning/error messages

diff --git a/core/bin/lstart b/core/bin/lstart
--- a/core/bin/lstart
+++ b/core/bin/lstart
@@ -205,6 +205,8 @@ single_lab_vhost_start() {
    local line_number
    local configuration opt value
 
+   local lab_conf="$lab_dir/lab.conf"
+
    # Specify host lab directory, and place filesystem inside it
    local vstart_args=(
       "--hostlab" "$lab_dir"
@@ -213,7 +215,7 @@ single_lab_vhost_start() {
    )
 
    # Generate vstart argument list
-   if [ -e "$lab_dir/lab.conf" ]; then
+   if [ -e "$lab_conf" ]; then
       while IFS= read -r configuration; do
          line_number=${configuration%%:*}
 
@@ -246,12 +248,12 @@ single_lab_vhost_start() {
          if [ -n "${value+x}" ]; then
             # Check for trailing whitespace
             if [[ "$value" =~ ^.*[^[:graph:]]$ ]]; then
-               warn "$lab_dir/lab.conf: Line $line_number: Whitespace detected at end of value, this may have unintended consequences"
+               warn "$lab_conf:$line_number" "whitespace at end of line, this may have unintended consequences"
             fi
 
             vstart_args+=( "$value" )
          fi
-      done < <(grep --line-number -- "^$vhost\[.*\]" "$lab_dir/lab.conf")
+      done < <(grep --line-number -- "^$vhost\[.*\]" "$lab_conf")
    fi
 
    # Remove .ready file, if existing
@@ -303,7 +305,7 @@ lab_start_parallel() {
    get_lab_vhosts "$lab_dir"
 
    if [ "${#lab_vhosts[@]}" -eq 0 ]; then
-      warn "There are no virtual machines to be started."
+      error "there are no virtual machines to be started"
       return
    fi
 
@@ -636,8 +638,8 @@ while true; do
                # No argument means MAX_SIMULTAENEOUS_VMS is used
                ;;
             *[!0-9]*)
-               warn "Argument to option '-p' must be a positive integer or 0"
-               usage 1
+               error "argument to option '-p' must be a positive integer or 0"
+               exit 1
                ;;
             *)
                MAX_SIMULTANEOUS_VMS=$parallelisation
@@ -667,8 +669,8 @@ while true; do
       -w|--wait)
          case $2 in
             ""|*[!0-9]*)
-               warn "Argument to option '-w' must be a positive integer or 0"
-               usage 1
+               error "argument to option '-w' must be a positive integer or 0"
+               exit 1
                ;;
             *)
                GRACE_TIME=$2
@@ -681,7 +683,7 @@ while true; do
          break
          ;;
       *)
-         warn "Unknown error parsing command line arguments"
+         error "unknown error parsing command line argument '$1'"
          usage 1
          ;;
    esac
@@ -699,14 +701,14 @@ validate_hostnames "${lab_vhosts[@]}"
 
 # Check that the lab directory exists
 if [ ! -d "$lab_dir" ]; then
-   warn "$lab_dir: No such directory"
+   error "$lab_dir: no such directory"
    exit 1
 fi
 
 
 # Check whether parallel startup and -f are being used together
 if [ -f "$lab_dir/lab.dep" ] && [ -n "$fast_mode" ] && [ -z "$sequential_mode" ]; then
-   warn "Fast mode is ignored when using parallel startup"
+   warn "fast mode is ignored when using parallel startup"
 fi
 
 
@@ -734,7 +736,7 @@ fi
 
 
 if [ ! -f "$lab_dir/lab.conf" ] && [ ! -f "$lab_dir/lab.dep" ] && [ -z "$force_lab" ]; then
-   warn "This does not appear to be a lab directory. Use option '-F' to ignore this error"
+   error "this does not appear to be a lab directory; use option '-F' to ignore this error"
    exit 1
 fi
 
diff --git a/core/bin/vconf b/core/bin/vconf
--- a/core/bin/vconf
+++ b/core/bin/vconf
@@ -271,8 +271,8 @@ while true; do
          if [ "$target_user" = "-" ]; then
             unset target_user
          elif ! id -- "$target_user" > /dev/null 2>&1; then
-            warn "$target_user: User does not exist"
-            usage 1
+            error "user '$target_user' does not exist"
+            exit 1
          fi
          ;;
       -v|--verbose)
@@ -287,7 +287,7 @@ while true; do
          break
          ;;
       *)
-         warn "Unknown error parsing command line arguments"
+         error "unknown error parsing command line argument '$1'"
          usage 1
          ;;
    esac
@@ -297,10 +297,10 @@ done
 
 # Parse virtual machine name
 if [ $# -eq 0 ]; then
-   warn "Missing machine name"
+   error "missing machine name"
    usage 1
 elif [ $# -gt 1 ]; then
-   warn "Can only specify one machine"
+   error "can only specify one machine"
    usage 1
 fi
 
@@ -309,7 +309,7 @@ validate_hostnames "$vhost"
 
 
 if ! get_vhost_info_by_name "$target_user" "$vhost"; then
-   warn "no virtual machine named '$vhost' exists${target_user:+" for user $target_user"}."
+   error "no virtual machine named '$vhost' exists${target_user:+" for user '$target_user'"}"
    exit 1
 fi
 
diff --git a/core/bin/vcrash b/core/bin/vcrash
--- a/core/bin/vcrash
+++ b/core/bin/vcrash
@@ -314,8 +314,8 @@ while true; do
          if [ "$target_user" = "-" ]; then
             unset target_user
          elif ! id -- "$target_user" > /dev/null 2>&1; then
-            warn "$target_user: User does not exist"
-            usage 1
+            error "user '$target_user' does not exist"
+            exit 1
          fi
          ;;
       -v|--verbose)
@@ -330,7 +330,7 @@ while true; do
          break
          ;;
       *)
-         warn "Unknown error parsing command line arguments"
+         error "unknown error parsing command line argument '$1'"
          usage 1
          ;;
    esac
@@ -340,7 +340,7 @@ done
 
 # Check whether virtual machine name is missing
 if [ $# -eq 0 ]; then
-   warn "Missing machine name"
+   error "missing machine name"
    usage 1
 fi
 
diff --git a/core/bin/vdump b/core/bin/vdump
--- a/core/bin/vdump
+++ b/core/bin/vdump
@@ -111,7 +111,7 @@ while true; do
          break
          ;;
       *)
-         warn "Unknown error parsing command line arguments"
+         error "unknown error parsing command line argument '$1'"
          usage 1
          ;;
    esac
@@ -120,10 +120,10 @@ while true; do
 done
 
 if [ $# -eq 0 ]; then
-   warn "Missing collision domain name"
+   error "missing collision domain name"
    usage 1
 elif [ $# -gt 1 ]; then
-   warn "Can only specify one collision domain"
+   error "can only specify one collision domain"
    usage 1
 fi
 
@@ -138,13 +138,13 @@ if [ -e "$reg_socket" ]; then
 elif [ -e "$tap_socket" ]; then
    socket=$tap_socket
 else
-   warn "$hub_name: Cannot find hub socket for the collision domain"
-   usage 1
+   error "cannot find socket file for the '$hub_name' collision domain"
+   exit 1
 fi
 
 if [ ! -S "$socket" ]; then
-   warn "$socket: File is not a socket"
-   usage 1
+   error "$socket: file is not a socket"
+   exit 1
 fi
 
 
diff --git a/core/bin/vhalt b/core/bin/vhalt
--- a/core/bin/vhalt
+++ b/core/bin/vhalt
@@ -127,8 +127,8 @@ while true; do
          if [ "$target_user" = "-" ]; then
             unset target_user
          elif ! id -- "$target_user" > /dev/null 2>&1; then
-            warn "$target_user: User does not exist"
-            usage 1
+            error "user '$target_user' does not exist"
+            exit 1
          fi
          ;;
       --version)
@@ -140,7 +140,7 @@ while true; do
          break
          ;;
       *)
-         warn "Unknown error parsing command line arguments"
+         error "unknown error parsing command line argument '$1'"
          usage 1
          ;;
    esac
@@ -150,7 +150,7 @@ done
 
 # Check whether virtual machine name is missing
 if [ $# -eq 0 ]; then
-   warn "Missing machine name"
+   error "missing machine name"
    usage 1
 fi
 
@@ -162,14 +162,14 @@ validate_hostnames "${vhosts[@]}"
 # Virtual machine filesystem cannot be removed in quick mode because the
 # machine may write files during shutdown.
 if [ -n "$rm_fs" ] && [ -n "$quick_mode" ]; then
-   warn "Filesystem cannot be removed in quick mode"
+   error "filesystem cannot be removed in quick mode"
    exit 1
 fi
 
 
 for vhost in "${vhosts[@]}"; do
    if ! get_vhost_info_by_name "$target_user" "$vhost"; then
-      warn "no virtual machine named '$vhost' exists${target_user:+" for user $target_user"}."
+      error "no virtual machine named '$vhost' exists${target_user:+" for user '$target_user'"}"
       exit 1
    fi
 
@@ -196,11 +196,11 @@ for vhost in "${vhosts[@]}"; do
          echo -n "."
       done
 
-      echo
+      echo ""
 
       # If machine is still up
       if get_machine_state "$target_user" "$vhost"; then
-         warn "could not shut down '$vhost'."
+         warn "could not shut down '$vhost'"
       else
          # Remove filesystem (.disk file)
          [ -n "$rm_fs" ] && [ -n "${vhost_info[disk]}" ] && rm --verbose -- "${vhost_info[disk]}"
diff --git a/core/bin/vlist b/core/bin/vlist
--- a/core/bin/vlist
+++ b/core/bin/vlist
@@ -326,8 +326,8 @@ while true; do
          if [ "$target_user" = "-" ]; then
             unset target_user
          elif ! id -- "$target_user" > /dev/null 2>&1; then
-            warn "$target_user: User does not exist"
-            usage 1
+            error "user '$target_user' does not exist"
+            exit 1
          fi
          ;;
       --version)
@@ -339,7 +339,7 @@ while true; do
          break
          ;;
       *)
-         warn "Unknown error parsing command line arguments"
+         error "unknown error parsing command line argument '$1'"
          usage 1
          ;;
    esac
@@ -354,7 +354,7 @@ validate_hostnames "${vhosts[@]}"
 
 # Check whether -u - is being used together with a virtual machine ID
 if [ -z "$target_user" ] && [ "${#vhosts[@]}" -ne 0 ]; then
-   warn "When giving VM names, a specific user ID must be provided"
+   error "when specifying machine names, a user ID must be provided with '--user'"
    usage 1
 fi
 
@@ -369,6 +369,6 @@ for vhost in "${vhosts[@]}"; do
    if get_vhost_info_by_name "$target_user" "$vhost"; then
       print_vhost_info_by_name
    else
-      warn "no virtual machine named '$vhost' exists for $target_user"
+      warn "no virtual machine named '$vhost' exists for '$target_user'"
    fi
 done
diff --git a/core/bin/vstart b/core/bin/vstart
--- a/core/bin/vstart
+++ b/core/bin/vstart
@@ -217,8 +217,8 @@ validate_ubd_arg() {
 
    for file in "${files[@]}"; do
       if str_contains "$file" "," ":"; then
-         warn "$file: Invalid character in filesystem path"
-         usage 1
+         error "invalid character in disk file or model filesystem path - '$file'"
+         exit 1
       fi
    done
 }
@@ -243,7 +243,7 @@ check_fs() {
    fs_type=$(stat --file-system --format "%T" -- "$file")
 
    if [[ ! "$fs_type" =~ ^($supportive_fs)$ ]]; then
-      warn "Filesystem '$fs_type' may not support sparse files, this could result in performance loss and disk space consumption"
+      warn "filesystem '$fs_type' may not support sparse files, this could result in performance loss and disk space consumption"
    fi
 }
 
@@ -398,7 +398,7 @@ while true; do
                [ "$opt" = "--con0" ] && VM_CON0=$console || VM_CON1=$console
                ;;
             *)
-               warn "$console: Unrecognized console"
+               error "'$console' is an invalid console type"
                usage 1
                ;;
          esac
@@ -447,8 +447,8 @@ while true; do
          VM_MEMORY=$2
 
          if [ "$VM_MEMORY" -lt "$MIN_MEM" ] || [ "$VM_MEMORY" -gt "$MAX_MEM" ]; then
-            warn "Memory out of permitted range (min: $MIN_MEM MB; max: $MAX_MEM MB)"
-            usage 1
+            error "'$VM_MEMORY' is outside the permitted range (min: $MIN_MEM MB; max: $MAX_MEM MB) for machine memory"
+            exit 1
          fi
 
          shift
@@ -498,7 +498,7 @@ while true; do
          shift
 
          if [[ ! "$TERM_TYPE" =~ ^(konsole|gnome|xterm|alacritty|kitty|kitty-tab|wsl|wt)$ ]]; then
-            warn "$TERM_TYPE: Unsupported terminal emulator"
+            error "'$TERM_TYPE' is an invalid terminal emulator"
             usage 1
          fi
          ;;
@@ -507,7 +507,7 @@ while true; do
          break
          ;;
       *)
-         warn "Unknown error parsing command line arguments"
+         error "unknown error parsing command line argument '$1'"
          usage 1
          ;;
    esac
@@ -517,10 +517,10 @@ done
 
 # Parse virtual machine name
 if [ $# -eq 0 ]; then
-   warn "Missing machine name"
+   error "missing machine name"
    usage 1
 elif [ $# -gt 1 ]; then
-   warn "Can only specify one machine"
+   error "can only specify one machine"
    usage 1
 fi
 
@@ -530,7 +530,7 @@ validate_hostnames "$vhost"
 
 # Check whether user is trying to attach more than one console to stdin/stdout
 if [ "$VM_CON0" = "this" ] && [ "$VM_CON1" = "this" ]; then
-   warn "Only one console can be attached to the current terminal"
+   error "only one console can be attached to the current terminal"
    usage 1
 fi
 
@@ -538,14 +538,14 @@ if [ -n "$no_cow" ]; then
    # Check whether a COW filesystem has been explictly provided when using the
    # '-W|--no-cow' option.
    if [ -n "$fs" ]; then
-      warn "Cannot provide a filesystem name with --no-cow"
+      error "cannot specify a filesystem name with '--no-cow'"
       usage 1
    fi
 
    # Check whether the user asked to hide the virtual machine filesystem while
    # using the '-W|--no-cow' option
    if [ -n "$rm_fs" ]; then
-      warn "Cannot hide the filesystem when using --no-cow"
+      error "cannot hide the filesystem when using '--no-cow'"
       usage 1
    fi
 fi
@@ -564,7 +564,7 @@ if [ "$VM_CON0" = "tmux" ] && [ "$TMUX_OPEN_TERMS" = "yes" ] || [ "$VM_CON0" = "
    esac
 
    if ! command -v -- "$term_executable" > /dev/null 2>&1; then
-      warn "$term_executable: Terminal emulator not found"
+      error "terminal emulator '$term_executable' could not found"
       exit 1
    fi
 fi
@@ -737,8 +737,8 @@ trap "rm --force -- '$out_file'" EXIT
          dst_mnt=${mnt_specification#*,}
 
          if str_contains "$src_mnt$dst_mnt" ","; then
-            warn "$mnt_specification: Invalid character in mount specification"
-            usage 1
+            error "invalid character in mount specification '$mnt_specification'"
+            exit 1
          fi
 
          echo "   Mount:      $src_mnt @ $dst_mnt"
@@ -787,20 +787,20 @@ rm --force -- "$out_file"
 if [ -z "$just_print" ]; then
    # Check whether the virtual machine already exists
    if get_machine_state "$USER_ID" "$vhost"; then
-      warn "Virtual machine '$vhost' is already running"
+      error "virtual machine '$vhost' is already running"
       exit 1
    fi
 
    # Check whether filesystem is already in use
    if file_in_use "$fs"; then
-      warn "Filesystem '$fs' is already in use; specify a different filesystem"
+      error "filesystem '$fs' is already in use; specify a different filesystem"
       exit 1
    fi
 
    if [ "$VM_CON0" = "tmux" ]; then
       # Check if tmux session already exists
       if tmux -L netkit has-session -t "$vhost" > /dev/null 2>&1; then
-         warn "tmux session already exists for machine '$vhost'; kill with 'vconnect -k'"
+         error "tmux session already exists for machine '$vhost'; kill with 'vconnect --kill'"
          exit 1
       fi
    fi
