length-check collision domain name

diff --git a/core/bin/script_utils b/core/bin/script_utils
--- a/core/bin/script_utils
+++ b/core/bin/script_utils
@@ -1098,6 +1098,36 @@ validate_netkit_conf_variables() {
 
 
 ###############################################################################
+# Calculate the maximum length of a collision domain name before it ends up
+# generating a uml_switch socket filepath longer than UNIX_PATH_MAX.
+# Usage:
+#   validate_netkit_conf_variables
+# Globals:
+#   r- HUB_SOCKET_DIR
+#   r- HUB_SOCKET_PREFIX
+#   r- HUB_SOCKET_EXTENSION
+# Arguments:
+#   None
+# Returns:
+#   None. Function exits with non-zero code if the length is below 1.
+# Example:
+#   None
+###############################################################################
+get_max_collision_domain_name_len() {
+   # shellcheck disable=SC2155
+   local min_socket_path=$(get_hub_socket "1" "")
+   local max_collision_domain_name_len=$(( 107 - ${#min_socket_path} ))
+
+   if [ "$max_collision_domain_name_len" -lt 1 ]; then
+      echo 1>&2 "netkit.conf: uml_switch sockets must have a filepath shorter than 108 characters (UNIX_PATH_MAX)"
+      exit 1
+   fi
+
+   echo "$max_collision_domain_name_len"
+}
+
+
+###############################################################################
 # Create a directory with 777 permissions. If a file with the same path already
 # exists, an error is thrown.
 # Usage:
@@ -1120,36 +1150,6 @@ netkit_dir_check() {
 
 # Override all locale settings to avoid localisation errors
 export LC_ALL=C
-
-
-# Regular expression for matching an IPv4 address with range validation
-inet_regex="((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])"
-
-
-# Regular expression for a Debian-approved (and RFC-compliant) hostname
-# label. This expression can be substituted directly into most Linux utility
-# commands, such as egrep (grep -E).
-#
-# Debian standard for hostname 'labels' (hostname(7) man page):
-#   - May consist of A-Z, a-z, 0-9, and - (hyphen)
-#   - Cannot start or end with a - (hyphen)
-#   - Are case-insensitive
-#   - Can be 1 to 63 characters long
-# NOTE: must not allow the following characters:
-#         []          - for lab.conf parsing
-#         ,           - for LAB_MACHINES parsing
-#         ,:[:blank:] - for the ubd argument (.disk file is named after host)
-hostname_regex="([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,62}[a-zA-Z0-9])"
-
-# Invalid hostnames (tested irrespective of hostname_regex)
-invalid_hostnames=( "shared" "_test" )
-
-
-# Regular expression for matching a collision domain name. This choice is
-# arbitrary (though some characters MUST be avoided), but should allow for all
-# reasonable use-cases.
-# NOTE: must not allow commas, forward slashes, or whitespace.
-collision_domain_name_regex="([[:alnum:]_.-]+)"
 
 
 # Read Netkit configuration in order of file localisation (per system, per
@@ -1195,6 +1195,38 @@ collision_domain_name_regex="([[:alnum:]_.-]+)"
 
 # Check for invalid values in netkit.conf variables
 validate_netkit_conf_variables
+
+
+# Regular expression for matching an IPv4 address with range validation
+inet_regex="((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])"
+
+
+# Regular expression for a Debian-approved (and RFC-compliant) hostname
+# label. This expression can be substituted directly into most Linux utility
+# commands, such as egrep (grep -E).
+#
+# Debian standard for hostname 'labels' (hostname(7) man page):
+#   - May consist of A-Z, a-z, 0-9, and - (hyphen)
+#   - Cannot start or end with a - (hyphen)
+#   - Are case-insensitive
+#   - Can be 1 to 63 characters long
+# NOTE: must not allow the following characters:
+#         []          - for lab.conf parsing
+#         ,           - for LAB_MACHINES parsing
+#         ,:[:blank:] - for the ubd argument (.disk file is named after host)
+hostname_regex="([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]{0,62}[a-zA-Z0-9])"
+
+# Invalid hostnames (tested irrespective of hostname_regex)
+invalid_hostnames=( "shared" "_test" )
+
+
+# Regular expression for matching a collision domain name. This choice is
+# arbitrary (though some characters MUST be avoided), but should allow for all
+# reasonable use-cases.
+# NOTE: must not allow commas, forward slashes, or whitespace. It must be also
+# be shorter than the length of UNIX_PATH_MAX when combined with the other hub
+# socket filepath parts.
+collision_domain_name_regex="([[:alnum:]_.-]{1,$(get_max_collision_domain_name_len)})"
 
 
 # Set the global USER_ID variable
