refactor vconnect

diff --git a/core/bin/vconnect b/core/bin/vconnect
--- a/core/bin/vconnect
+++ b/core/bin/vconnect
@@ -10,39 +10,57 @@ fi
 # shellcheck source=./script_utils
 . "$NETKIT_HOME/bin/script_utils"
 
-export TMUX='' # allow nesting of tmux sessions
+# Allow nesting of tmux sessions
+export TMUX=''
 
-RETRY_COUNT=1
-RETRY_INTERVAL=5
-
-tmux_connect(){ # $1 = machine name
-    tmux -L netkit attach -t="$1"
+###############################################################################
+# Attach to a machine's tmux session in the current terminal.
+# Usage:
+#   tmux_connect MACHINE
+# Globals:
+#   None
+# Arguments:
+#   $1 - virtual machine name
+# Returns:
+#   None
+# Example:
+#   None
+###############################################################################
+tmux_connect() {
+   tmux -L netkit attach -t="$1"
 }
 
-open_terminal(){ # $1 = machine name
-    if [ -z ${TERM_TYPE+x} ]; then
-        echo "No terminal set in netkit.conf."
-        exit 1
-    fi
-    case "$TERM_TYPE" in
-        alacritty)          TERMCMD="alacritty -e";;
-        kitty)              TERMCMD="kitty";;
-        konsole)            TERMCMD="konsole --nofork -e";;
-        konsole-tab)        TERMCMD="$NETKIT_HOME/bin/konsole-tabs.sh -e";;
-        xterm)              TERMCMD="xterm -e";;
-        wsl)
-            powershell.exe -Command "start wsl -ArgumentList @('--', 'tmux', '-L', 'netkit', 'attach', '-t="$1"')"
-            exit
-            ;;
-        wt)
-            powershell.exe -Command "wt.exe -p netkit wsl.exe -- tmux -L netkit attach -t="$1""
-            exit
-            ;;
-        *)
-            echo "[vconnect]: terminal $TERM_TYPE not supported, defaulting to xterm."
-            TERMCMD="xterm -e";;
-    esac
-    nohup $TERMCMD tmux -L netkit attach -t="$1" &> /dev/null &
+###############################################################################
+# Open a new terminal window attached to a machine's tmux session.
+# Usage:
+#   open_terminal MACHINE
+# Globals:
+#   r- NETKIT_HOME
+#   r- TERM_TYPE
+# Arguments:
+#   $1 - virtual machine name
+# Returns:
+#   None
+# Example:
+#   None
+###############################################################################
+open_terminal() {
+   vm=$1
+
+   case "$TERM_TYPE" in
+      alacritty)     term_cmd=( "alacritty" "-e" );;
+      kitty)         term_cmd=( "kitty" );;
+      konsole)       term_cmd=( "konsole" "--nofork" "-e" );;
+      konsole-tab)   term_cmd=( "$NETKIT_HOME/bin/konsole-tabs.sh" "-e" );;
+      xterm)         term_cmd=( "xterm" "-e" );;
+      wsl)           term_cmd=( "cmd.exe" "/c" "start" "wsl.exe" );;
+      wt)            term_cmd=( "cmd.exe" "/c" "wt.exe" "-p" "netkit" "wsl.exe" );;
+      *)
+         echo "Terminal '$TERM_TYPE' not supported, defaulting to xterm."
+         term_cmd=( "xterm" "-e" );;
+   esac
+   
+   nohup "${term_cmd[@]}" tmux -L netkit attach -t "$vm" > /dev/null 2>&1 &
 }
 
 
@@ -105,104 +123,94 @@ Miscellaneous:
 $(help_option)
 $(version_option)
 
-The cleaning process involves temporary files generated for any of the virtual
-machines of the lab. If one or more MACHINEs are passed on the command line,
-then only those files generated for the matching virtual machines are deleted,
-as well as the 'readyfor.test' file. If any of the VM names are invalid (i.e.,
-it does not correspond to a virtual machine of the lab), it will simply be
-skipped.
-
 END_OF_HELP
 
    exit "$status"
 }
 
 
-# from https://medium.com/@Drew_Stokes/bash-argument-parsing-54f3b81a6a8f
+# Get command line options
+LONG_OPTS="interval:,list,machine:,retry-count,terminal"
+SHORT_OPTS="lm:n:r:t"
 
-while (( "$#" )); do
-  case "$1" in
-    --help)
-      usage 0
-      ;;
-    -l|--list)
-      LIST_ONLY="TRUE"
-      shift
-      ;;
-    -t|--terminal)
-      OPEN_TERM="TRUE"
-      shift
-      ;;
-    -r|--retry-count)
-      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
-        RETRY_COUNT=$2
-        shift 2
-      else
-        echo "Error: Argument for $1 is missing" >&2
-        usage 1
-      fi
-      ;;
-    -n|--interval)
-      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
-        RETRY_INTERVAL=$2
-        shift 2
-      else
-        echo "Error: Argument for $1 is missing" >&2
-        usage 1
-      fi
-      ;;
-    -m|--machine)
-      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
-        MACHINE_NAME=$2
-        shift 2
-      else
-        echo "Error: Argument for $1 is missing" >&2
-        usage 1
-      fi
-      ;;
-    --version)
-      showVersion
-      exit 0
-      ;;
-    *)
-      echo "Error: Unsupported flag $1" >&2
-      usage 1
-      ;;
-  esac
-done
-
-if [ "$LIST_ONLY" = "TRUE" ]; then
-  tmux -L netkit list-sessions 2> /dev/null || \
-      echo -e "\nNo tmux sessions running for Netkit machines.\n"
-  exit 0
+if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
+   # getopt will output the errorneous command-line argument
+   usage 1
 fi
 
-if [ -z ${MACHINE_NAME+x} ]; then
-    echo "Machine name not given."
-    usage 1
-fi
+RETRY_COUNT=1
+RETRY_INTERVAL=5
 
-ATTEMPTS=1
+# (Safely) set positional parameters to those reordered by getopt
+eval set -- "$GETOPT_OPTS"
 
-while [ $ATTEMPTS -le $RETRY_COUNT ]; do
-    tmux -L netkit has-session -t="$MACHINE_NAME" 2>/dev/null
-    if [ $? -ne 0 ]; then
-        ATMSG=""
-        [ $RETRY_COUNT -gt 1 ] && ATMSG="(Attempt $ATTEMPTS)"
-        echo "[vconnect]: tmux session does not exist for this machine. $ATMSG"
-        if [ $ATTEMPTS -eq $RETRY_COUNT ]; then
-            [ $RETRY_COUNT -gt 1 ] && echo "[vconnect]: too many attempts. exiting."
-            exit 1
-        fi
-        sleep "$RETRY_INTERVAL"
-    else
-        ATTEMPTS=$RETRY_COUNT
-    fi
-    ATTEMPTS=$((ATTEMPTS+1))
+while true; do
+   case "$1" in
+      --help)
+         usage 0
+         ;;
+      -l|--list)
+         LIST_ONLY=1
+         ;;
+      -m|--machine)
+         MACHINE_NAME=$2
+         shift
+         ;;
+      -n|--interval)
+         RETRY_INTERVAL=$2
+         shift
+         ;;
+      -r|--retry-count)
+         RETRY_COUNT=$2
+         shift
+         ;;
+      -t|--terminal)
+         OPEN_TERM=1
+         ;;
+      --version)
+         showVersion
+         exit 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
+         usage 1
+         ;;
+   esac
+
+   shift
 done
 
-if [ "$OPEN_TERM" = "TRUE" ]; then
-    open_terminal $MACHINE_NAME
+
+# Do not connect to the tmux session, just list available ones.
+if [ -n "$LIST_ONLY" ]; then
+   tmux -L netkit list-sessions
+   exit 0
+fi
+
+
+echo -n "Connecting to '$MACHINE_NAME'."
+
+# Test that the tmux session exists RETRY_COUNT number of times.
+ATTEMPTS=0
+while ! tmux -L netkit has-session -t="$MACHINE_NAME" 2> /dev/null; do
+   ATTEMPTS=$((ATTEMPTS + 1))
+
+   if [ "$ATTEMPTS" -eq "$RETRY_COUNT" ]; then
+      echo
+      echo 1>&2 "Could not connect to '$MACHINE_NAME'."
+      exit 1
+   fi
+
+   sleep "$RETRY_INTERVAL"
+   echo -n "."
+done
+
+if [ -n "$OPEN_TERM" ]; then
+   open_terminal "$MACHINE_NAME"
 else
-    tmux_connect $MACHINE_NAME
+   tmux_connect "$MACHINE_NAME"
 fi
