refactor vconf

diff --git a/core/bin/vconf b/core/bin/vconf
--- a/core/bin/vconf
+++ b/core/bin/vconf
@@ -139,249 +139,245 @@ END_OF_HELP
 
 
 # Get command line options
-INVALID_OPTION=0
-OPT_LIST="help,print,quiet,version,user:"
+LONG_OPTS="help,print,quiet,version,user:"
+SHORT_OPTS="pqu:"
+
 i=0
-while [ $i -lt $MAX_INTERFACES ]; do
-   OPT_LIST="${OPT_LIST},eth$i:"
-   i=$(($i + 1))
+while [ "$i" -lt "$MAX_INTERFACES" ]; do
+   LONG_OPTS="$LONG_OPTS,eth$i:"
+   i=$((i + 1))
 done
-CMDLINE_OPTIONS=$(getopt -ql "$OPT_LIST" -- "pqvu:" "$@")
-if [ $? -gt 0 ]; then
-   INVALID_OPTION=1
+
+if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
+   # getopt will output the errorneous command-line argument
+   usage 1
 fi
 
+# (Safely) set positional parameters to those reordered by getopt
+eval set -- "$GETOPT_OPTS"
 
-# Parse command line options
-parseCmdLine() {
-   local CURRENT_ARGUMENT
+while true; do
+   case "$1" in
+      --eth*)
+         OPT=$1
+         DOMAIN=$2
+         shift
+
+         if containsRegexp DOMAIN "_"; then
+            echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - underscores are not allowed"
+            usage 1
+         fi
+
+         if containsRegexp DOMAIN "," || containsRegexp DOMAIN "\\."; then
+            # If not a tap specification, but its name contains a comma
+            if [ "${DOMAIN#tap,}" = "$DOMAIN" ]; then
+               echo 1>&2 "$SCRIPTNAME: $DOMAIN: Invalid collision domain - commas and periods are only valid for tap interface specification"
+               usage 1
+            fi
+         fi
+
+         checkSpaces "$DOMAIN"
+         ETH_INTERFACES="$ETH_INTERFACES ${OPT#--}=$DOMAIN"
+         ;;
+      --help)
+         usage 0
+         ;;
+      -p|--print)
+         JUST_PRINT=1
+         ;;
+      -q|--quiet)
+         BE_QUIET=1
+         ;;
+      -u|--user)
+         USER="$2"
+         [ "$USER" = "-" ] && unset USER
+         shift
+         ;;
+      --version)
+         show_version
+         exit 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
+         usage 1
+         ;;
+   esac
+
+   shift
+done
+
+
+if [ $# -eq 0 ]; then
+   echo 1>&2 "$SCRIPTNAME: Missing machine name"
+   usage 1
+elif [ $# -gt 1 ]; then
+   echo 1>&2 "$SCRIPTNAME: Can only specify one machine"
+   usage 1
+fi
+
+# Parse virtual machine name
+VM_ID=$1
+checkSpaces "$VM_ID"
+shift
+
+
+###############################################################################
+# Append network interface specifications to the kernel invocation command.
+# Usage:
+#   setup_interfaces [INTERFACE]...
+# Globals:
+#   r- BE_QUIET
+#   -w HUBLIST
+#   r- HUB_SOCKET_DIR
+#   r- HUB_SOCKET_EXTENSION
+#   r- HUB_SOCKET_PREFIX
+#   r- MCONSOLE_CMD
+#   r- SCRIPTNAME
+#   r- USERID
+# Arguments:
+#  ... - list of interfaces
+# Returns:
+#   None. Will exit with usage 1 on invalid specification.
+# Example:
+#   None
+###############################################################################
+setup_interfaces() {
+   local device hub_name hub_socket tap_address
+   local guest_address used_devices
+   local first_iteration
+
+   first_iteration=true
    while [ $# -gt 0 ]; do
-      CURRENT_ARGUMENT="$1"
-      case "$CURRENT_ARGUMENT" in
-         --eth*)
-            ETH_INTERFACES="${ETH_INTERFACES} ${CURRENT_ARGUMENT#--}="
-            shift; CURRENT_ARGUMENT="$1"
-            if containsRegexp CURRENT_ARGUMENT "_"; then
-               echo 1>&2 "$SCRIPTNAME: Invalid collision domain: $CURRENT_ARGUMENT (underscoresare are not allowed)"
-               exit 1
-            fi
-            if containsRegexp CURRENT_ARGUMENT "," || containsRegexp CURRENT_ARGUMENT "\\."; then
-               if [ "${CURRENT_ARGUMENT#tap,}" = "$CURRENT_ARGUMENT" ]; then
-                  # This is not a special hub, but its name contains a comma
-                  echo 1>&2 "$SCRIPTNAME: Invalid collision domain: $CURRENT_ARGUMENT (commas and dots are only allowed for Internet connected collision domains)"
-                  exit 1
-               fi
-            fi
+      device=${1%%=*}
 
-            # If no collision domain name is provided, the interface will be
-            # detached from the virtual machine
-            checkSpaces "$CURRENT_ARGUMENT"
-            ETH_INTERFACES="${ETH_INTERFACES}${CURRENT_ARGUMENT}" ;;
+      # If hub_name is blank, the network interface will be removed.
+      hub_name=${1#*=}
 
-         --help)
-            usage 0;;
-
-         -q|--quiet)
-            BE_QUIET=1;;
-            
-         --print|-p)
-            JUST_PRINT=1;;
-            
-         --user|-u)
-            shift; CURRENT_ARGUMENT="$1"
-            if [ "x$CURRENT_ARGUMENT" = "x" ]; then
-               echo 1>&2 "$SCRIPTNAME: Expecting username"
-               exit 1
-            fi
-            checkSpaces "$CURRENT_ARGUMENT"
-            if [ "$CURRENT_ARGUMENT" = "-" ]; then
-               USER=""
-            else
-               USER=$CURRENT_ARGUMENT
-            fi;;
-         
-         --version)
-            show_version
-            exit 0;;
-            
-         --)
-            shift
-            break;;
-      esac
-      shift
-   done
-
-   # Parse virtual machine name   
-   while [ $# != 0 ]; do
-      if [ ! -z "$VM_ID" ]; then
-         echo 1>&2 "$SCRIPTNAME: Too many arguments: $*"
-         exit 1
+      # Check if interface has already been configured
+      if [[ " $used_devices " == *" $device "* ]]; then
+         echo 1>&2 "$SCRIPTNAME: $device: Duplicate interface"
+         usage 1
       fi
-      checkSpaces "$1"
-      VM_ID=$1
+
+      # Remember that this network interface has been configured
+      used_devices="$used_devices $device"
+
+      # Check if tap interface (regular hubs cannot be named with commas)
+      if [[ "$hub_name" == tap,* ]]; then
+         # Format: tap,tap_address,guest_address
+         IFS=, read -r hub_name tap_address guest_address <<< "$hub_name"
+
+         if ! is_inet_addr "$tap_address"; then
+            echo 1>&2 "$SCRIPTNAME: $tap_address: Invalid tap address"
+            usage 1
+         fi
+
+         if ! is_inet_addr "$guest_address"; then
+            echo 1>&2 "$SCRIPTNAME: $guest_address: Invalid guest address"
+            usage 1
+         fi
+      else
+         # This is a normal (i.e., not 'tap') collision domain
+         unset tap_address guest_address
+      fi
       
+      hub_socket="$HUB_SOCKET_DIR/${HUB_SOCKET_PREFIX}_${USERID}_$hub_name$HUB_SOCKET_EXTENSION"
+
+      if [ -n "$tap_address" ]; then
+         HUBLIST+=( "$hub_socket,$tap_address,$guest_address" )
+      elif [ -n "$hub_name" ]; then
+         HUBLIST+=( "$hub_socket" )
+      fi
+
+      if $first_iteration; then
+         first_iteration=false
+      elif [ -z "$BE_QUIET" ]; then
+         echo -n "               "
+      fi
+
+      if [ -n "$hub_name" ]; then
+         MCONSOLE_CMD+=( "$device=daemon,,,$hub_socket" )
+         [ -z "$BE_QUIET" ] && echo "$device @ $hub_name ($hub_socket)"
+      else
+         MCONSOLE_CMD+=( "$device" )
+         [ -z "$BE_QUIET" ] && echo "$device removed"
+      fi
+
       shift
    done
 }
-eval parseCmdLine $CMDLINE_OPTIONS
 
 
-# Check whether user gave some strange options
-if [ $INVALID_OPTION -eq 1 ]; then
-   echo 1>&2 "$SCRIPTNAME: Invalid option or missing option parameter"
+###############################################################################
+# Attach/remove network interfaces from running machines with mconsole.
+# Usage:
+#   invoke_mconsole MCONSOLE_CMD
+# Globals:
+#   r- NETKIT_HOME
+#   r- VM_ID
+# Arguments:
+#   $1 - list of mconsole commands
+# Returns:
+#   None
+# Example:
+#   None
+###############################################################################
+invoke_mconsole() {
+   local action action_desc arg device hub_specification mconsole_cmd
+
+   mconsole_cmd=( "$@" )
+
+   for arg in "${mconsole_cmd[@]}"; do
+      # Format is either:
+      #   To add an interface:
+      #     ethN=daemon,,,path/to/socket
+      #   To remove an interface:
+      #     ethN
+      device=${arg%%=*}
+      hub_specification=${arg#*=}
+
+      if [ -n "$hub_specification" ]; then
+         action="config"
+         action_desc="add"
+      else
+         action="remove"
+         action_desc="remove"
+      fi
+
+      # TODO: run_command
+      if ! "$NETKIT_HOME/bin/uml_mconsole" "$VM_ID" "$action" "$device" 2>&1; then
+         echo 2>&1 "Failed to $action_desc interface '$device'"
+      fi
+   done
+}
+
+
+############################# Configure interfaces ############################
+if ! get_machine_state "$USER" "$VM_ID"; then
+   echo -n 1>&2 "$SCRIPTNAME: no virtual machine named '$VM_ID' exists"
+   [ -n "$USER" ] && echo " for user $USER." || echo "."
    exit 1
 fi
 
-# Check whether virtual machine name is missing
-if [ -z "$VM_ID" ]; then
-   echo 1>&2 "$SCRIPTNAME: Virtual machine name/PID is missing"
-   exit 1
-fi
-
-
-# This function prepares network interfaces for use.
-setupInterfaces() {
-   local DEVICE HUB_NAME HUB_SOCKET FIRSTLINE IF_CMDLINE CHECK_TAP TAP_ADDRESS GUEST_ADDRESS
-   FIRSTLINE=1
-   while [ $# -gt 0 ]; do
-      # Using a double percent (%%) allows to tolerate situations in which
-      # virtual hub names include an equal sign (=)
-      DEVICE=${1%%=*}
-      # Using a single hash (#) allows to tolerate situations in which
-      # virtual hub names include an equal sign (=)
-      HUB_NAME=${1#*=}
-      if [ "${HUB_NAME}" = "tap" ]; then
-         echo 1>&2
-         echo 1>&2 "$SCRIPTNAME: Invalid tap collision domain specification: '$1'"
-         exit 1
-      fi
-      if containsRegexp HUB_NAME "tap,"; then
-         # This is an Internet connected (i.e., "tap") collision domain
-         CHECK_TAP=$(echo $HUB_NAME | awk -v FS="," \
-            '
-               {
-                  if (NF!=3 ||
-                      !match($2,"^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$") ||
-                      !match($3,"^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"))
-                     print 0
-                  else {
-                     print "HUB_NAME=tap"
-                     print "TAP_ADDRESS=" $2
-                     print "GUEST_ADDRESS=" $3
-                  }
-               }
-            ')
-         if [ "x$CHECK_TAP" = "x0" ]; then
-            echo 1>&2
-            echo 1>&2 "$SCRIPTNAME: Invalid tap collision domain specification: '$1'"
-            exit 1
-         else
-            eval "$CHECK_TAP"
-         fi
-      fi
-
-      HUB_SOCKET="${HUB_SOCKET_DIR}/${HUB_SOCKET_PREFIX}_${USERID}_${HUB_NAME}${HUB_SOCKET_EXTENSION}"
-      
-      if containsRegexp MCONSOLE_CMD "${DEVICE}=daemon,,,"; then
-         echo 1>&2 "$SCRIPTNAME: Duplicate interface: $DEVICE"
-         exit 1
-      fi
-      
-      if [ -z "$BE_QUIET" ]; then
-         if [ $FIRSTLINE != 1 ]; then
-            echo -n "               "
-         fi
-         if [ ! -z "$HUB_NAME" ]; then
-            echo "${DEVICE} @ ${HUB_NAME}\t(${HUB_SOCKET})"
-         else
-            echo "${DEVICE} removed"
-         fi
-      fi
-      
-      if [ -z "$HUB_NAME" ]; then
-         MCONSOLE_CMD="$MCONSOLE_CMD $DEVICE"
-      else
-         MCONSOLE_CMD="$MCONSOLE_CMD $DEVICE=daemon,,,$HUB_SOCKET"
-      fi
-      
-      if [ ! -z "$HUB_NAME" ]; then
-         if [ ! -z "$TAP_ADDRESS" ]; then
-            HUBLIST="$HUBLIST $HUB_SOCKET,$TAP_ADDRESS,$GUEST_ADDRESS"
-         else
-            HUBLIST="$HUBLIST $HUB_SOCKET"
-         fi
-      fi
-      FIRSTLINE=0
-      shift
-   done
-}
-
-
-# This function invokes mconsole in order to attach/remove interfaces from
-# running virtual machines.
-invokeMconsole() {
-   local ACTION EVAL_THIS INTERFACE
-   while [ $# -gt 0 ]; do
-      EVAL_THIS=$(echo $1 | awk -v FS="=" \
-         '{
-            if (NF==1) {
-               print "ACTION=\"remove " $0 "\""
-               print "ACTION_DESC=\"remove\""
-            }
-            else {
-               print "ACTION=\"config " $0 "\""
-               print "ACTION_DESC=\"add\""
-            }
-            print "INTERFACE=" $1
-         }')
-      eval "$EVAL_THIS"
-      run_command "$JUST_PRINT" "$NETKIT_HOME/bin/uml_mconsole $VMINFO_NAME $ACTION" \
-         "$NETKIT_HOME/bin/uml_mconsole $VMINFO_NAME $ACTION 2>&1 | \
-          awk '/^ERR/ {gsub(\"^ERR *\", \"\"); print \"Failed to '$ACTION_DESC' interface: \" \$0}' 2>&1"
-      shift
-   done
-}
-
-
-################## Actually configure interfaces ##################
-
-if echo $VM_ID | grep -qE "^[0-9]+$"; then
-   # This is a virtual machine PID
-   if ! getVMinfoByPID "$VM_ID"; then
-      echo 1>&2 "$SCRIPTNAME: no virtual machine having PID $VM_ID exists."
-      exit 1
-   fi
-else
-   # This is a virtual machine name
-   if ! getVMinfoByName "$USER" "$VM_ID"; then
-      echo -n 1>&2 "$SCRIPTNAME: no virtual machine named \"$VM_ID\" exists"
-      if [ ! -z "$USER" ]; then
-         echo " for user $USER."
-      else
-         echo "."
-      fi
-      exit 1
-   fi
-fi
-
-
+# TODO: Sort out VMINFO variables
 if [ -z "$BE_QUIET" ]; then
-   echo
-   echo "============= Configuring virtual machine \"$VMINFO_NAME\" (PID $VMINFO_PID) ============="
-   echo "   Virtual machine owner: $VMINFO_USER"
+   echo "============= Configuring virtual machine '$VM_ID' (PID $VMINFO_PID) ============="
+   echo "   Virtual machine owner: $USER"
 fi
 
 
 ##### Setup network interfaces
-if [ ! -z "$ETH_INTERFACES" ]; then
+if [ -n "$ETH_INTERFACES" ]; then
    [ -z "$BE_QUIET" ] && echo -n "   Interfaces: "
-   eval setupInterfaces $ETH_INTERFACES
+   setup_interfaces $ETH_INTERFACES
 fi
 
 ##### Start network hubs
-eval runHubs $HUBLIST
+runHubs "${HUBLIST[@]}"
 
 ##### Attach/remove network interfaces
-eval invokeMconsole "$MCONSOLE_CMD"
-
-[ -z "$BE_QUIET" ] && echo
+invoke_mconsole "${MCONSOLE_CMD[@]}"
