refactor vcrash

diff --git a/core/bin/vcrash b/core/bin/vcrash
--- a/core/bin/vcrash
+++ b/core/bin/vcrash
@@ -152,6 +152,8 @@ while true; do
       --kill|-k)
          DO_KILL=1
          ;;
+
+      # TODO: Remove --quiet. Have --verbose and --quick (independent).
       -q|--quick|--quiet)
          BE_QUIET=1
          ;;
@@ -184,116 +186,77 @@ while true; do
    shift
 done
 
+# Check whether virtual machine name is missing
+if [ $# -eq 0 ]; then
+   echo 1>&2 "$SCRIPTNAME: Missing machine name"
+   usage 1
+fi
 
-while [ $# -gt 0 ]; do
-   checkSpaces "$1"
-   VM_IDS="$VM_IDS $1"
-   shift
+# Non-option arguments are machine names
+vm_ids=( "$@" )
+
+for host in "${vm_ids[@]}"; do
+   checkSpaces "$host"
 done
 
 
-# Check whether virtual machine name is missing
-if [ -z "$VM_IDS" ]; then
-   echo 1>&2 "$SCRIPTNAME: Virtual machine name/PID is missing"
-   exit 1
-fi
-
-
 # Test mode is senseless if working in quiet mode
-if [ ! -z "$TEST_MODE" -a ! -z "$BE_QUIET" ]; then
+if [ -n "$TEST_MODE" ] && [ -n "$BE_QUIET" ]; then
    echo 1>&2 "$SCRIPTNAME: Option --test cannot be used when working in quiet mode"
-   exit 1
+   usage 1
 fi
-
-
-
-# This function removes a virtual machine filesystem
-removeFs() {
-   [ ! -f "$1" ] && return;      # Filesystem does not exist
-   if [ -z "$BE_QUIET" ]; then
-      echo -n "Removing filesystem \"$1\"... "
-      rm -f "$1" > /dev/null 2>&1 && echo "done". || echo "failed!"
-   else
-      rm -f "$1" > /dev/null 2>&1
-   fi
-}
-
-
-
-# This function checks whether there is a specific running virtual machine,
-# based on either its PID or its name. Variables VMINFO_MCONSOLE and VM_PROCESSES
-# are populated with corresponding information upon success, or left empty on
-# failure. If FASTFIND is set, then VM_PROCESSES is never populated (this
-# slightly improves execution time for this function).
-findVM() {
-   VMINFO_MCONSOLE=""
-   VM_PROCESSES=""
-   if echo $1 | grep -qE "^[0-9]+$"; then
-      # This is a virtual machine PID
-      if ! getVMinfoByPID "$1"; then
-         echo 1>&2 "$SCRIPTNAME: no virtual machine having PID $1 exists."
-         continue
-      fi
-      [ -z "$FASTFIND" ] && VM_PROCESSES=$(getVMPIDsByPID "$1")
-   else
-      # This is a virtual machine name
-      if ! getVMinfoByName "$USER" "$1"; then
-         echo -n 1>&2 "$SCRIPTNAME: no virtual machine named \"$1\" exists"
-         if [ ! -z "$USER" ]; then
-            echo " for user $USER."
-         else
-            echo "."
-         fi
-         continue
-      fi
-      [ -z "$FASTFIND" ] && VM_PROCESSES=$(getVMPIDsByName "$USER" "$1")
-   fi
-}
-
 
 
 # This function kills a virtual machine by simply signaling the corresponding
 # processes. It is assumed that VMINFO variables have been populated by a
 # preceding call to either getVMinfoByName or getVMinfoByPID.
-killBySignaling() {
-   local RETURN_VALUE
-   RETURN_VALUE=1
+kill_by_signaling() {
+   vm=$1
+
    [ -z "$BE_QUIET" ] && echo -n "Killing... "
-   # Signalling processes twice ensures they stop even
-   # if they need to be killed in a certain order
-   kill -TERM $VM_PROCESSES > /dev/null 2>&1
-   kill -TERM $VM_PROCESSES > /dev/null 2>&1
+
+   # Signalling processes twice ensures they stop even if they need to be
+   # killed in a certain order
+   IFS=" " read -r -a pids <<< "$(get_vm_all_pids_by_name "$USER" "$vm")"
+
+   if [ "${#pids[@]}" -eq 0 ]; then
+      kill -TERM "${pids[@]}" > /dev/null
+      kill -TERM "${pids[@]}" > /dev/null
+   fi
+
    if [ -z "$BE_QUIET" ]; then
       sleep 1
+
       # Do not use getVMinfoByPID here: this may result in missing some
       # process which may have started in the meantime (that process would of
       # course have a different PID).
-      if getVMinfoByName "$USER" "$VMINFO_NAME"; then
+      if get_machine_state "$USER" "$vm"; then
          [ -z "$BE_QUIET" ] && echo -n "killing harder... "
-         # Recompute process list (some thread may have been launched in the
+         # Recompute PID list (some threads may have been launched in the
          # meantime).
-         unset FASTFIND
-         findVM $VMINFO_NAME
-         
-         kill -KILL $VM_PROCESSES > /dev/null 2>&1
-         kill -CONT $VM_PROCESSES > /dev/null 2>&1
-         sleep 1
-         if getVMinfoByName "$USER" "$VMINFO_NAME"; then
-            if [ -z "$BE_QUIET" ]; then
-               echo "failed!"
-            fi
-            echo 1>&2 "Failed to crash virtual machine \"$VMINFO_NAME\"."
-         else
-            [ -z "$BE_QUIET" ] && echo "done."
-            RETURN_VALUE=0
+         IFS=" " read -r -a pids <<< "$(get_vm_all_pids_by_name "$USER" "$vm")"
+
+         if [ "${#pids[@]}" -eq 0 ]; then
+            kill -KILL "${pids[@]}" > /dev/null
+            kill -CONT "${pids[@]}" > /dev/null
          fi
-      else
-         [ -z "$BE_QUIET" ] && echo "done."
-         RETURN_VALUE=0
+
+         sleep 1
+
+         if get_machine_state "$USER" "$vm"; then
+            [ -z "$BE_QUIET" ] && echo "failed!"
+            echo 1>&2 "Failed to crash virtual machine '$vm'"
+            return 1
+         fi
       fi
+
+      [ -z "$BE_QUIET" ] && echo "done."
    fi
+
    # Virtual machine filesystem is removed only if it has been successfully crashed
-   [ $RETURN_VALUE = 0 -a ! -z "$REMOVE_FS" -a "$VMINFO_FS" != "$VMINFO_SHAREDFS" ] && removeFs "$VMINFO_FS"
+   [ -n "$REMOVE_FS" ] && [ "$VMINFO_FS" != "$VMINFO_SHAREDFS" ] && remove_fs "$VMINFO_FS"
+   
+   return 0
 }
 
 
@@ -305,18 +268,23 @@ killBySignaling() {
 # hangs, regardless of whether the virtual machine has been actually crashed
 # or not. Here it is assumed that VMINFO variables have been populated
 # by a previous call to either getVMinfoByName or getVMinfoByPID.
-vmconsoleHalt() {
-   $NETKIT_HOME/bin/uml_mconsole "$VMINFO_MCONSOLE" halt > /dev/null 2>&1 &
-   MCONSOLE_PID=$!
+mconsole_halt() {
+   mconsole_socket=$1
+
+   "$NETKIT_HOME/bin/uml_mconsole" "$mconsole_socket" halt > /dev/null &
+   uml_mconsole_pid=$!
+
    # Check whether the mconsole process is hanging forever
    i=0
    while [ $i -le 5 ]; do
-      [ ! -e /proc/$MCONSOLE_PID ] && return 0
+      [ ! -e "/proc/$uml_mconsole_pid" ] && return 0
       [ $i -lt 5 ] && sleep 1
-      i=$(($i + 1))
+      i=$((i + 1))
    done
+
    [ -z "$BE_QUIET" ] && echo "hangup detected... "
-   kill $MCONSOLE_PID
+   kill "$uml_mconsole_pid"
+
    return 1
 }
 
@@ -326,36 +294,38 @@ vmconsoleHalt() {
 # (mconsole) socket. Upon failure, it reverts to killing the virtual machine
 # processes. It assumes that VMINFO variables have been populated by a
 # previous call to either getVMinfoByName or getVMinfoByPID.
-killByMconsole() {
+kill_by_mconsole() {
+   vm=$1
+
    [ -z "$BE_QUIET" ] && echo -n "Crashing... "
-   vmconsoleHalt
+
+   if mconsole_socket=$(get_vm_mconsole "$vm"); then
+      mconsole_halt "$mconsole_socket"
+   else
+      return 1
+   fi
+
    # When the above command exits, an attempt via the mconsole has been
    # performed. Regardless of whether the virtual machine has actually halted,
    # the above command ensures that the uml_mconsole process has ended.
    if [ -z "$BE_QUIET" ]; then
-      # A second attempt is performed only if we're not in quiet mode
-      if getVMinfoByPID "$VMINFO_PID"; then
+      # Make a second attempt if machine is still running
+      if get_machine_state "$USER" "$vm"; then
          echo -n "retrying... "
          sleep 1
-         if ! vmconsoleHalt; then
+
+         if ! mconsole_halt "$mconsole_socket"; then
             # uml_mconsole is hanging forever
             
             # The two lines below are necessary in order to retrieve the
-            # virtual machine PIDs, which are required by killBySignaling.
+            # virtual machine PIDs, which are required by kill_by_signaling.
             # We chose not to retrieve them immediately because this requires
             # time and is only necessary if mconsole does not work.
-            unset FASTFIND
-            findVM $VM
-            killBySignaling $VMINFO_PID
+            kill_by_signaling "$vm"
             return $?
-         elif getVMinfoByPID "$VMINFO_PID"; then
+         elif get_machine_state "$USER" "$vm"; then
             # Attempt to kill virtual machine processes
-            
-            # See the comment above for the 'if' statement. Notice that, since
-            # we are inside an 'elif' branch, findVM is never invoked twice.
-            unset FASTFIND
-            findVM $VM
-            killBySignaling $VMINFO_PID
+            kill_by_signaling "$vm"
             return $?
          else
             echo "done."
@@ -364,74 +334,45 @@ killByMconsole() {
          echo "done."
       fi
    fi
-   [ ! -z "$REMOVE_FS" -a "$VMINFO_FS" != "$VMINFO_SHAREDFS" ] && removeFs "$VMINFO_FS"
+
+   [ -n "$REMOVE_FS" ] && [ "$VMINFO_FS" != "$VMINFO_SHAREDFS" ] && remove_fs "$VMINFO_FS"
 }
 
 
+for vm in "${vm_ids[@]}"; do
+   # Check whether the current machine exists
+   if get_machine_state "$USER" "$vm" ; then
+      if [ -z "$BE_QUIET" ]; then
+         echo "============= Crashing virtual machine '$vm' (PID $(get_vm_pid_by_name "$USER" "$VM")) ========="
+         echo "Virtual machine owner: $USER"
+         echo "Virtual machine mconsole socket: $(get_vm_mconsole "$vm")"
+         echo "Virtual machine PIDs: $(get_vm_all_pids_by_name "$USER" "$vm")"
+      fi
+   
+      [ -n "$TEST_MODE" ] && continue
 
-# This function prints some information about a virtual machine. It assumes
-printConciseVMinfo() {
-   if [ -z "$BE_QUIET" ]; then
-      echo
-      echo "============= Crashing virtual machine \"$VMINFO_NAME\" (PID $VMINFO_PID) ========="
-      echo "Virtual machine owner: $VMINFO_USER"
-      echo "Virtual machine mconsole socket: $VMINFO_MCONSOLE"
-      [ ! -z "$VM_PROCESSES" ] && echo "Virtual machine PIDs: " $VM_PROCESSES
+      if [ -n "$DO_KILL" ]; then
+         # Crash virtual machines by simply killing their processes
+         kill_by_signaling "$vm"
+      else
+         # Crash virtual machines via uml_mconsole
+         kill_by_mconsole "$vm"
+      fi
+
+      # Kill tmux Sessions
+      [ -z "$BE_QUIET" ] && echo "Checking for '$vm' tmux session"
+
+      if tmux -L netkit has-session -t="$vm" 2>/dev/null; then
+         [ -z "$BE_QUIET" ] && echo "Killing tmux session '$vm'"
+         tmux -L netkit kill-session -t="$vm"
+      fi
+
+      [ -z "$BE_QUIET" ] && echo "Checking for '$vm-dead' tmux session"
+
+      if tmux -L netkit has-session -t="$vm-dead" 2>/dev/null; then
+         [ -z "$BE_QUIET" ] && echo "Killing tmux session '$vm-dead'"
+         tmux -L netkit kill-session -t="$vm-dead"
+      fi
    fi
-}
 
-
-if [ -z "$DO_KILL" ]; then
-   # Use mconsole sockects to crash virtual machine kernels
-   for VM in $VM_IDS; do
-      # Check whether the current machine exists
-      FASTFIND=1
-      findVM $VM
-      
-      if [ ! -z "$VMINFO_MCONSOLE" ]; then
-         # The machine exists
-         printConciseVMinfo
-         if [ -z "$TEST_MODE" ]; then
-            killByMconsole
-         fi
-      fi
-   done
-else
-   # Crash virtual machines by simply killing their processes
-   for VM in $VM_IDS; do
-      # Check whether the current machine exists
-      unset FASTFIND
-      findVM $VM      
-      if [ ! -z "$VM_PROCESSES" ]; then
-         printConciseVMinfo
-         if [ -z "$TEST_MODE" ]; then
-            killBySignaling
-         fi
-      fi
-
-   done
-fi
-
-# Kill Tmux Sessions
-for VM in $VM_IDS; do
-  if echo $1 | grep -qE "^[0-9]+$"; then
-    [ -z "$BE_QUIET" ] && echo "Cannot check tmux session using pid.
-    You may want to manually kill any tmux session for the machine you are trying
-    to crash (including MACHINE-dead sessions)"
-  else
-    [ -z "$BE_QUIET" ] && echo "Checking for $VM tmux session"
-    tmux -L netkit has-session -t="$VM" 2>/dev/null
-    if [ $? -eq 0 ]; then
-       [ -z "$BE_QUIET" ] && echo "Killing tmux session $VM"
-       tmux -L netkit kill-session -t="$VM"
-       exit 1
-    fi
-    [ -z "$BE_QUIET" ] && echo "Checking for ${VM}-dead tmux session"
-    tmux -L netkit has-session -t="${VM}-dead" 2>/dev/null
-    if [ $? -eq 0 ]; then
-       [ -z "$BE_QUIET" ] && echo "Killing tmux session ${VM}-dead"
-       tmux -L netkit kill-session -t="${VM}-dead"
-       exit 1
-    fi
-  fi
 done
