standardise option parsing

diff --git a/core/bin/vdump b/core/bin/vdump
--- a/core/bin/vdump
+++ b/core/bin/vdump
@@ -90,88 +90,64 @@ END_OF_HELP
 
 
 # Get command line options
-INVALID_OPTION=0
-OPT_LIST="help,version"
-CMDLINE_OPTIONS=$(getopt -ql "$OPT_LIST" -- "nu:" "$@")
-if [ $? -gt 0 ]; then
-   INVALID_OPTION=1
+LONG_OPTS="help,version"
+SHORT_OPTS=""
+
+if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
+   # getopt will output the errorneous command-line argument
+   usage 1
 fi
 
-parseCmdLine() {
-   while [ $# -gt 0 ]; do
-      CURRENT_ARGUMENT="$1"
-      case "$CURRENT_ARGUMENT" in
-      
-         --help)
-            usage 0;;
-         
-         --version)
-            showVersion
-            exit 0;;
-            
-         --)
-            shift
-            break;;
+# (Safely) set positional parameters to those reordered by getopt
+eval set -- "$GETOPT_OPTS"
 
-      esac
-      shift
-   done
+while true; do
+   case "$1" in
+      --help)
+         usage 0
+         ;;
+      --version)
+         showVersion
+         exit 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
+         usage 1
+         ;;
+   esac
 
-   if [ $# -ge 2 ]; then
-      echo 1>&2 "$SCRIPTNAME: only one domain."
-      exit 1
-   fi
+   shift
+done
 
-   if [ $# -eq 0 ]; then
-      echo 1>&2 "$SCRIPTNAME: missing domain."
-      exit 1
-   fi
-
-   checkSpaces "$1"
-
-   HUB_NAME=$1   
-}
-eval parseCmdLine $CMDLINE_OPTIONS
-
-
-# Check whether user gave some strange options
-if [ $INVALID_OPTION -eq 1 ]; then
-   echo 1>&2 "$SCRIPTNAME: Invalid option or missing option parameter"
+if [ $# -eq 0 ]; then
+   echo 1>&2 "$SCRIPTNAME: Missing collision domain name"
+   exit 1
+elif [ $# -gt 1 ]; then
+   echo 1>&2 "$SCRIPTNAME: Can only specify one collision domain"
    exit 1
 fi
+
+hub_name=$1
+checkSpaces "$hub_name"
+
 
 # check if file exist and if a pipe file
-HUB_SOCKET="${HUB_SOCKET_DIR}/${HUB_SOCKET_PREFIX}_${USERID}_${HUB_NAME}${HUB_SOCKET_EXTENSION}"
+hub_socket="${HUB_SOCKET_DIR}/${HUB_SOCKET_PREFIX}_${USERID}_${hub_name}${HUB_SOCKET_EXTENSION}"
 
-if [ ! -e ${HUB_SOCKET} ]; then
-   echo 1>&2 "$HUB_SOCKET not found"
-   echo 1>&2 "Domain $HUB_NAME exist ?"
-   exit 1
+if [ ! -e "$hub_socket" ]; then
+   echo 1>&2 "$SCRIPTNAME: $hub_socket: No such file or directory. Does the '$hub_name' domain exist?"
+   usage 1
+elif [ ! -S "$hub_socket" ]; then
+   echo 1>&2 "$SCRIPTNAME: $hub_socket: File is not a socket"
+   usage 1
 fi
 
-if [ ! -S ${HUB_SOCKET} ]; then
-   echo 1>&2 "$HUB_SOCKET is not a socket"
-   exit 1
-fi
-
-run_command() {
-   if [ -z "$2" ]; then
-      SHOW_COMMAND="$3"
-   else
-      SHOW_COMMAND="$2"
-   fi
-   if [ "x$1" = "x1" ]; then
-      [ -z "$BE_QUIET" ] && echo 1>&2 "Not running ==> $SHOW_COMMAND"
-      # Report that everything went ok
-      return 0
-   else
-      [ -z "$BE_QUIET" ] && echo 1>&2 "Running ==> $SHOW_COMMAND"
-      eval $3
-      return
-   fi
-}
 JUST_PRINT=0;
-DUMP_COMMAND="uml_dump $HUB_NAME"
-COMPLETE_COMMAND="uml_dump $HUB_SOCKET"
+DUMP_COMMAND="uml_dump $hub_name"
+COMPLETE_COMMAND="uml_dump $hub_socket"
 
 run_command "$JUST_PRINT" "$DUMP_COMMAND" "$COMPLETE_COMMAND"
