refactor vhalt and fix shutdown procedure (TEMP)

diff --git a/core/bin/vhalt b/core/bin/vhalt
--- a/core/bin/vhalt
+++ b/core/bin/vhalt
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 #     Copyright 2002-2009 Maurizio Patrignani, Maurizio Pizzonia, Fabio Ricci,
 #     Massimo Rimondini - Computer Networks Research Group, Roma Tre University.
@@ -25,13 +25,11 @@ SCRIPTNAME=$(basename "$0")
 
 if [ -z "$NETKIT_HOME" ]; then
    echo 1>&2 "$SCRIPTNAME: The NETKIT_HOME environment variable is not properly set;"
-   echo 1>&2 "please set it as described in the Netkit documentation and try"
-   echo 1>&2 "again."
+   echo 1>&2 "please set it as described in the Netkit documentation and try again."
    exit 1
 fi
 
-CMDLINE="$0 $*"
-
+# shellcheck source=./script_utils
 . "$NETKIT_HOME/bin/script_utils"
 
 # Write to the vcommands log
@@ -41,11 +39,11 @@ logWrite "$0 $*"
 # This function is used to print the vhalt usage
 help() {
    echo
-   echo "Usage: $SCRIPTNAME [options] MACHINE-ID..."
+   echo "Usage: $SCRIPTNAME [OPTION]... MACHINE..."
    cat << END_OF_HELP
-This script can be used to gracefully shutdown running virtual machines.
-MACHINE-ID is either the name or the PID of a virtual machine. Available options
-are:
+Gracefully shutdown running MACHINE(s).
+
+Available options are:
 
   -h, --help          Show this help.
   -q, --quick
@@ -59,168 +57,164 @@ are:
   -u, --user=USERNAME Halt virtual machine(s) owned by user USERNAME. By using
                       the special user name '-' any virtual machine can be
                       halted, regardless of its owner (administrative privileges
-                      are required). If MACHINE-ID is a virtual machine name,
-                      and the option --user=- is being used, then only the
-                      virtual machine reported by 'vlist --user=- MACHINE-ID' is
-                      halted.                      
-      --version       Print version information and exit.
-                   
+                      are required).
+      --version       Print version information and exit.             
 END_OF_HELP
 }
 
 
-# Get command line options
-INVALID_OPTION=0
-OPT_LIST="help,quick,quiet,user:,version,remove-fs"
-CMDLINE_OPTIONS=$(getopt -ql "$OPT_LIST" -- "hqru:" "$@")
-if [ $? -gt 0 ]; then
-   INVALID_OPTION=1
-fi
-
-
-
-USER=$USERID
-
-
-# Parse command line options
-parseCmdLine() {
-   while [ $# -gt 0 ]; do
-      CURRENT_ARGUMENT="$1"
-      case "$CURRENT_ARGUMENT" in
-      
-         --help|-h)
-            help
-            exit;;
-            
-         --user|-u)
-            shift; CURRENT_ARGUMENT="$1"
-            if [ "x$CURRENT_ARGUMENT" = "x" ]; then
-               warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-                       "Expecting username."
-               exit 1
-            fi
-            checkSpaces "$CURRENT_ARGUMENT"
-            if [ "$CURRENT_ARGUMENT" = "-" ]; then
-               USER=""
-            else
-               USER=$CURRENT_ARGUMENT
-            fi;;
-            
-         --quick|--quiet|-q)
-            BE_QUIET=1;;
-            
-         --remove-fs|-r)
-            REMOVE_FS=1;;
-            
-         --version)
-            showVersion
-            exit 0;;
-            
-         --)
-            shift
-            break;;
-      esac
-      shift
-   done
-   
-   while [ $# -gt 0 ]; do
-      checkSpaces "$1"
-      VM_IDS="$VM_IDS $1"
-         
-      shift
-   done
+# Output vhalt's usage to stderr
+# Usage: usage
+usage() {
+   echo 1>&2 "Usage: $SCRIPTNAME [OPTION]... MACHINE..."
+   echo 1>&2 "Try '$SCRIPTNAME --help' for more information."
 }
-eval parseCmdLine $CMDLINE_OPTIONS
 
 
-# Check whether user gave some strange options
-if [ $INVALID_OPTION -eq 1 ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Invalid option or missing option parameter."
+# USERID is set in script_utils
+USER="$USERID"
+
+
+# Get command line options
+LONG_OPTS="help,quick,quiet,remove-fs,user:,version"
+SHORT_OPTS="hqru:"
+
+if ! GETOPT_OPTS=$(getopt --name "$SCRIPTNAME" --options "$SHORT_OPTS" --longoptions "$LONG_OPTS" -- "$@"); then
+   # getopt will output the errorneous command-line argument
+   usage
    exit 1
 fi
+
+# (Safely) set positional parameters to those reordered by getopt
+eval set -- "$GETOPT_OPTS"
+
+while true; do
+   case "$1" in
+      -h|--help)
+         help
+         exit 0
+         ;;
+
+      # TODO: Remove --quiet. Have --verbose and --quick (independent).
+      -q|--quick|--quiet)
+         BE_QUIET=1
+         ;;
+      --remove-fs|-r)
+         REMOVE_FS=1
+         ;;
+      -u|--user)
+         USER="$2"
+         [ "$USER" = "-" ] && unset USER
+         shift
+         ;;
+      --version)
+         showVersion
+         exit 0
+         ;;
+      --)
+         shift
+         break
+         ;;
+      *)
+         echo 1>&2 "$SCRIPTNAME: Unknown error parsing command line arguments"
+         usage
+         exit 1
+         ;;
+   esac
+
+   shift
+done
+
+# Non-option arguments are machine names
+vm_hostnames=( "$@" )
+
+for host in "${vm_hostnames[@]}"; do
+   checkSpaces "$host"
+done
 
 
 # Check whether virtual machine name is missing
-if [ -z "$VM_IDS" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Virtual machine name/PID is missing."
+if [ "${#vm_hostnames[@]}" -eq 0 ]; then
+   echo 1>&2 "$SCRIPTNAME: Missing virtual machine name"
    exit 1
 fi
 
 
-# Virtual machine filesystem cannot be removed if in quiet mode, because the
+# Virtual machine filesystem cannot be removed in quiet mode because the
 # machine may write files during shutdown
-if [ ! -z "$REMOVE_FS" -a ! -z "$BE_QUIET" ]; then
-   warning "$SCRIPTNAME" "$CMDLINE" "$0" "Filesystem cannot be removed if working in quiet mode."
+if [ -n "$REMOVE_FS" ] && [ -n "$BE_QUIET" ]; then
+   echo 1>&2 "$SCRIPTNAME: Filesystem cannot be removed in quiet mode"
    exit 1
 fi
-
-
-
 
 
 # This function removes a virtual machine filesystem
-removeFs() {
-   [ ! -f "$1" ] && return;      # Filesystem does not exist
-   # We assume we are not in quiet mode (filesystems are not removed if in quiet mode)
-   echo -n "Removing filesystem \"$1\"... "
-   rm -f "$1" > /dev/null 2>&1 && echo "done". || echo "failed!"
+remove_fs() {
+   rm --verbose "$1"
 }
 
 
-for VM in $VM_IDS; do
-   if echo $VM | grep -qE "^[0-9]+$"; then
-      # This is a virtual machine PID
-      if ! getVMinfoByPID "$VM"; then
-         echo 1>&2 "$SCRIPTNAME: no virtual machine having PID $VM exists."
+for vm in "${vm_hostnames[@]}"; do
+   if ! get_vm_info "$USER" "$vm"; then
+      echo -n 1>&2 "$SCRIPTNAME: no virtual machine named '$vm' exists"
+      [ -n "$USER" ] && echo " for user $USER." || echo "."
+      exit 1
+   fi
+
+   [ -z "$BE_QUIET" ] && echo -e -n "Halting '$VMINFO_NAME' (PID $VMINFO_PID) owned by \
+   $VMINFO_USER [                    ]\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
+
+   # Old method uses CTRL-ALT-DEL. This yields the error
+   #   harddog_open - run_helper failed, errno = -2
+   # and subsequently reboots (as opposed to powering off.)
+   #"$NETKIT_HOME/bin/uml_mconsole" "$vm" cad > /dev/null
+
+   # TODO: Try to use the old method - it uses /sbin/shutdown and is safer and
+   # quicker.
+   # New method uses the Magic SysRq key in the REISUO combination (R is not
+   # included because there is no X server).
+   # This method is not perfect; the timings required are rough estimates. The
+   # system will return "OK" to uml_mconsole upon a valid command being sent,
+   # NOT when the command has completed. e and i cannot be expected to finish
+   # in the time given by the delay. s, u, and o are almost instant.
+
+   # e: send a SIGTERM to all processes, except for init
+   "$NETKIT_HOME/bin/uml_mconsole" "$vm" sysrq e > /dev/null
+   sleep 2
+
+   # i: send a SIGKILL to all processes, except for init
+   "$NETKIT_HOME/bin/uml_mconsole" "$vm" sysrq i > /dev/null
+   sleep 2
+
+   # s: attempt to sync all mounted filesystems
+   "$NETKIT_HOME/bin/uml_mconsole" "$vm" sysrq s > /dev/null
+   sleep 0.2
+
+   # u: attempt to remount all mounted filesystems read-only
+   "$NETKIT_HOME/bin/uml_mconsole" "$vm" sysrq u > /dev/null
+   sleep 0.2
+
+   # o: shut the system off (if configured and supported)
+   "$NETKIT_HOME/bin/uml_mconsole" "$vm" sysrq o > /dev/null
+
+   if [ -z "$BE_QUIET" ]; then
+      ATTEMPTS=1
+      while get_vm_info "$USER" "$vm"; do
+         sleep 1
+         echo -n "."
+
+         [ $ATTEMPTS -eq 20 ] && break
+         ATTEMPTS=$((ATTEMPTS + 1))
+      done
+
+      echo
+
+      # If machine is still up
+      if get_vm_info "$USER" "$vm"; then
+         echo 1>&2 "$SCRIPTNAME: could not shut down '$vm'."
       else
-         [ -z "$BE_QUIET" ] && echo -n "Halting virtual machine \"$VMINFO_NAME\" (PID $VMINFO_PID) owned by $VMINFO_USER [                    ]\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
-         $NETKIT_HOME/bin/uml_mconsole "$VMINFO_MCONSOLE" cad > /dev/null 2>&1
-         if [ -z "$BE_QUIET" ]; then
-            ATTEMPTS=1;
-            while getVMinfoByPID "$VM"; do
-               sleep 2
-               echo -n "."
-               if [ $ATTEMPTS -eq 20 ]; then
-                  break
-               fi
-               ATTEMPTS=$(($ATTEMPTS+1))
-            done
-            echo
-            if getVMinfoByPID "$VM"; then
-               echo 1>&2 "$SCRIPTNAME: could not shut down virtual machine having PID $VM."
-            else
-               [ ! -z "$REMOVE_FS" -a "$VMINFO_FS" != "$VMINFO_SHAREDFS" ] && removeFs "$VMINFO_FS"
-            fi
-         fi
-      fi
-   else
-      # This is a virtual machine name
-      if ! getVMinfoByName "$USER" "$VM"; then
-         echo -n 1>&2 "$SCRIPTNAME: no virtual machine named \"$VM\" exists"
-         if [ ! -z "$USER" ]; then
-            echo " for user $USER."
-         else
-            echo "."
-         fi
-      else
-         [ -z "$BE_QUIET" ] && echo -n "Halting virtual machine \"$VMINFO_NAME\" (PID $VMINFO_PID) owned by $VMINFO_USER [                    ]\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
-         $NETKIT_HOME/bin/uml_mconsole "$VMINFO_MCONSOLE" cad > /dev/null 2>&1
-         if [ -z "$BE_QUIET" ]; then
-            ATTEMPTS=1
-            while getVMinfoByName "$USER" "$VM"; do
-               sleep 2
-               echo -n "."
-               if [ $ATTEMPTS -eq 20 ]; then
-                  break
-               fi
-               ATTEMPTS=$(($ATTEMPTS+1))
-            done
-            echo
-            if getVMinfoByName "$USER" "$VM"; then
-               echo 1>&2 "$SCRIPTNAME: could not shut down virtual machine \"$VM\"."
-            else
-               [ ! -z "$REMOVE_FS" -a "$VMINFO_FS" != "$VMINFO_SHAREDFS" ] && removeFs "$VMINFO_FS"
-            fi
+         if [ -n "$REMOVE_FS" ] && [ "$VMINFO_FS" != "$VMINFO_SHAREDFS" ]; then
+            remove_fs "$VMINFO_FS"
          fi
       fi
    fi
