refactor vlist

diff --git a/core/bin/vlist b/core/bin/vlist
--- a/core/bin/vlist
+++ b/core/bin/vlist
@@ -40,11 +40,12 @@ log_write "$0 $*"
 
 # This function is used to print the vlist usage
 help() {
-   echo
-   echo "Usage: $SCRIPTNAME [OPTION]... MACHINE..."
+   echo "Usage: $SCRIPTNAME [OPTION]... [MACHINE]..."
    cat << END_OF_HELP
-This script can be used to produce a list of running virtual machines. You can
-use the following options to select the output contents:
+List running Netkit virtual machines and get detailed information about
+MACHINE(s).
+
+You can use the following options to select the output contents:
 
   -h, --help          Show this help.
   -n, --no-header     Suppress header line and summary information in the
@@ -55,11 +56,9 @@ use the following options to select the output contents:
                       current user are shown.
       --version       Print version information and exit.
 
-By passing one or more MACHINE-IDs it is possible to get detailed information
-about specific running virtual machines. MACHINE-ID is either a virtual machine 
-name or its PID. If a virtual machine name is passed as argument, and the option
---user=- is being used, then information about the first machine with a matching
-name in the output of 'vlist --user=-' are reported.
+By specifying one or more MACHINEs it is possible to get detailed information.
+If --user=- is also being used, information about the first MACHINE with a
+matching name in the output of 'vlist --user=-' is reported.
 END_OF_HELP
 }
 
@@ -67,7 +66,7 @@ END_OF_HELP
 # Output vlist's usage to stderr
 # Usage: usage
 usage() {
-   echo 1>&2 "Usage: $SCRIPTNAME [OPTION]... MACHINE..."
+   echo 1>&2 "Usage: $SCRIPTNAME [OPTION]... [MACHINE]..."
    echo 1>&2 "Try '$SCRIPTNAME --help' for more information."
 }
 
@@ -96,7 +95,7 @@ while true; do
          exit 0
          ;;
       --no-header|-n)
-         NO_HEADER=1
+         no_header=true
          ;;
       --user|-u)
          USER="$2"
@@ -122,60 +121,171 @@ while true; do
 done
 
 # Non-option arguments are machine names
-VHOSTLIST=( "$@" )
+vm_ids=( "$@" )
 
-for host in "${VHOSTLIST[@]}"; do
+for host in "${vm_ids[@]}"; do
    checkSpaces "$host"
 done
 
 
 # Check whether -u - is being used together with a virtual machine ID
-if [ -z "$USER" ] && [ -n "$VM_IDS" ]; then
+if [ -z "$USER" ] && [ "${#vm_ids[@]}" -ne 0 ]; then
    echo 1>&2 "$SCRIPTNAME: When giving VM names, a specific user ID must be provided"
    exit 1
 fi
 
 
-# Actually display list of virtual machines
-if [ -z "$VM_IDS" ]; then
-   showVMList "$NO_HEADER" "$USER"
+# Display summary of virtual machines
+if [ "${#vm_ids[@]}" -eq 0 ]; then
+   print_vm_summary "$no_header" "$USER"
 fi
 
-[ -n "$USER" ] && pgrep_euid="--euid"
 
-# Iterate over the PIDs of running Netkit instances
-for pid in $(pgrep "$pgrep_euid" "$USER" --full "^$NETKIT_HOME/kernel/netkit-kernel"); do
-   # The process hierarchy looks like this:
-   #
-   #    PID  PGID  Process
-   #     ?    ?     vstart
-   #                    \
-   #     x    x           - netkit-kernel
-   #                           |
-   #     a    x                +--- netkit-kernel
-   #     b    x                +--- netkit-kernel
-   #     c    x                +--- netkit-kernel
-   #     ...  ...              +--- ...
-   #
-   #    (PID = process ID, PGID = process group ID)
-   #
-   # The main (parent) netkit-kernel process is the group leader of the
-   # netkit-kernel child processes, because its PID == PGID.
-   # The children are all part of this group.
-   #
-   # For vlist we only care about the parent kernel process, so we skip over
-   # PIDs that are not group leaders.
+###############################################################################
+# Summarise all running machines for a specific user.
+# Usage:
+#   print_vm_summary NO_HEADER USER
+# Globals:
+#   r- NETKIT_HOME
+#   r- HUB_SOCKET_PREFIX
+#   r- HUB_SOCKET_EXTENSION
+# Arguments:
+#   $1 - do not display column headers; pass an empty string to show them
+#   $2 - user; pass an empty string for all users
+# Returns:
+#   None
+# Example:
+#   None
+###############################################################################
+print_vm_summary() {
+   no_header=$1
+   user=$2
 
-   # Get the process group ID (PGID)
-   pgid=$(ps --no-headers --format pgid --pid "$pid")
+   [ -n "$user" ] && pgrep_euid="--euid"
 
-   # Ignore if not a process leader
-   [ "$pgid" -ne "$pid" ] && continue
+   # Column spacing:
+   #   USER    20
+   #   VHOST   20
+   #   PID      5
+   #   SIZE     9
+   # A single space is added between each column, too (3 between SIZE and
+   # INTERFACES).
+   [ -z "$no_header" ] && echo "USER                 VHOST                  PID      SIZE   INTERFACES"
+
+   # Iterate over the PIDs of running Netkit instances.
+   # The process hierarchy (relevance of the PGID) is documented in
+   # scripts_utils.
+   machine_count=0
+   for pid in $(pgrep ${pgrep_euid:+"$pgrep_euid"} ${user:+"$user"} --full "^$NETKIT_HOME/kernel/netkit-kernel"); do
+      # Get the process group ID (PGID)
+      pgid=$(ps --no-headers --format pgid --pid "$pid")
+
+      # Ignore if not a process leader
+      [ "$pgid" -ne "$pid" ] && continue
+
+      machine_count=$((machine_count + 1))
+
+      # Effective user ID of the process (full username if not too long)
+      owner=$(ps --no-headers --format euser --pid "$pid")
+
+      # Total virtual memory usage of the process.
+      # Logically this should be the sum of every process in the group (PGID),
+      # however in practice just taking the value of the parent process is
+      # enough. The value should equate to roughly the size of the machine's
+      # memory.
+      memory_usage=$(ps --no-headers --format vsize --pid "$pid")
+      total_memory_usage=$((total_memory_usage + memory_usage))
+
+      # Full command used to invoke the process.
+      # Why not parse the output of ps? Whitespace in the program name or
+      # arguments is impossible to deal with. /proc/$pid/cmdline stores argv
+      # with null-byte field separators, which is the only character that
+      # cannot be present in a Linux filepath. This will still break if a
+      # newline is present in the command, but if a user is doing that then
+      # they are just asking for an error somewhere down the line to be honest.
+      full_command=$(xargs -0 printf "%s\n" < "/proc/$pid/cmdline")
+
+      first_iteration=true
+      while IFS="" read -r argument; do
+         # As per the manual, UML options are key=value pairs.
+         # ${argument#*=} removes the key= prefix from argument (the single #
+         # permits usage of further equals signs in the argument).
+         # We skip the first argument (the program name)
+         if $first_iteration; then
+            first_iteration=false
+         elif [[ "$argument" =~ ^umid=.*$ ]]; then
+            umid=${argument#*=}
+         elif [[ "$argument" =~ ^eth[0-9]+=.*$ ]]; then
+            key=${argument%%=*}
+            value=${argument#*=}
+
+            # Interface number
+            n=${key#eth}
+
+            # UML socket filepath (assuming transport mode is daemon)
+            uml_socket=${value#daemon,,,*}
+
+            # Array of UML sockets indexed by the interface number
+            uml_sockets[$n]=$uml_socket
+            continue
+         fi
+      done <<< "$full_command"
+
+      # No column will be truncated on a value that is too long
+      printf "%-20s %-20s %5d %9d   " "$owner" "$umid" "$pid" "$memory_usage"
+
+      first_iteration=true
+      for i in "${!uml_sockets[@]}"; do
+         filepath=${uml_sockets[$i]}
+         filename=$(basename "$filepath")
+
+         collision_domain_and_ext=${filename#"$HUB_SOCKET_PREFIX"_*_}
+         collision_domain=${collision_domain_and_ext%"$HUB_SOCKET_EXTENSION"}
+
+         # Comma-separate subsequent interfaces
+         if $first_iteration; then
+            first_iteration=false
+         else
+            echo -n ", "
+         fi
+
+         echo -n "eth$i @ $collision_domain"
+      done
+
+      echo
+   done
+
+   echo
+   printf "Total virtual machines: %9d\n" "$machine_count"
+   printf "Total consumed memory:  %9d KB\n" "$total_memory_usage"
+}
+
+
+###############################################################################
+# Print complete information about a machine.
+# Usage:
+#   print_vm_info PID
+# Globals:
+#   r- NETKIT_HOME
+#   r- VM_MEMORY_SKEW
+# Arguments:
+#   $1 - process ID (PID) of the machine
+# Returns:
+#   Prints machine details to stdout. Returns 0 on success, non-zero on
+#   failure.
+# Example:
+#   None
+###############################################################################
+print_vm_info() {
+   pid=$1
 
    # Effective user ID of the process (full username if not too long)
    owner=$(ps --no-headers --format euser --pid "$pid")
 
-   # Total virtual memory usage of the process
+   # Total virtual memory usage of the process.
+   # Logically this should be the sum of every process in the group (PGID),
+   # however in practice just taking the value of the parent process is enough.
+   # The value should equate to roughly the size of the machine's memory.
    memory_usage=$(ps --no-headers --format vsize --pid "$pid")
 
    # Full command used to invoke the process.
@@ -189,7 +299,6 @@ for pid in $(pgrep "$pgrep_euid" "$USER" --full "^$NETKIT_HOME/kernel/netkit-ker
    full_command=$(xargs -0 printf "%s\n" < "/proc/$pid/cmdline")
 
    first_iteration=true
-
    while IFS="" read -r argument; do
       if $first_iteration; then
          program=$argument
@@ -200,137 +309,140 @@ for pid in $(pgrep "$pgrep_euid" "$USER" --full "^$NETKIT_HOME/kernel/netkit-ker
       # As per the manual, UML options are key=value pairs.
       # ${argument#*=} removes the key= prefix from argument (the single #
       # permits usage of further equals signs in the argument).
-      case "$argument" in
-         umid=*)     umid="${argument#*=}";;
-         mem=*)      mem="${argument#*=}";; # TODO: adjust by skew
-         uml_dir=*)  uml_dir="${argument#*=}";;
-         udb0=*)
-            value="${argument#*=}"
 
-            # udb0=disk,fs
-            disk="${value%%,*}"
-            fs="${value#*,}"
+      # Edge-cases that can only be matched with regular expressions (or with
+      # extglob enabled, which cannot be done.)
+      if [[ "$argument" =~ ^eth[0-9]+=.*$ ]]; then
+         key=${argument%%=*}
+         value=${argument#*=}
+
+         # Interface number
+         n=${key#eth}
+
+         # UML socket filepath (assuming transport mode is daemon)
+         uml_socket=${value#daemon,,,*}
+
+         # Array of UML sockets indexed by the interface number
+         uml_sockets[$n]=$uml_socket
+         continue
+      fi
+
+      # Most of the command-line options can be matched with basic pattern
+      # matching:
+      case "$argument" in
+         umid=*)     umid=${argument#*=};;
+
+         # Memory is NOT adjusted by the skew here
+         mem=*)      mem=${argument#*=};;
+         udb0=*)
+            value=${argument#*=}
+
+            # The udb0 value is disk,fs or fs
+            disk=${value%%,*}
+            fs=${value#*,}
+
+            # The parameter expansions result in equal values if a single,
+            # shared filesystem is used.
+            [ "$disk" = "$fs" ] && unset disk
             ;;
          con0=* )
-            value="${argument#*=}"
+            value=${argument#*=}
             case "$value" in
-               xterm)      con0="$value";;
+               xterm)      con0=$value;;
                fd:0,fd:1)  con0="this";;
-               pty)        con0="$value";;
-               port:*)     con0="$value";;
+               pty)        con0=$value;;
+               port:*)     con0=$value;;
                null)       con0="none";;
             esac
             ;;
          con1=*)
-            value="${argument#*=}"
+            value=${argument#*=}
             case "$value" in
-               xterm)      con1="$value";;
+               xterm)      con1=$value;;
                fd:0,fd:1)  con1="this";;
-               pty)        con1="$value";;
-               port:*)     con1="$value";;
+               pty)        con1=$value;;
+               port:*)     con1=$value;;
                null)       con1="none";;
             esac
             ;;
-         eth[0-9]+=*)
-            key="${argument%%=*}"
-            value="${argument#*=}"
-
-            n="${key#eth}"
-
-            # Array of collision domains indexed by the interface number
-            interfaces[$n]="$value"
-            ;;
-         exec=*)     exec="${argument#*=}";;
-         hostlab=*)  hostlab="${argument#*=}";;
-         hostwd=*)   hostwd="${argument#*=}";;
-         hosthome=*) hosthome="${argument#*=}";;
-         modules=*)  modules="${argument#*=}";;
+         exec=*)     boot_cmd=${argument#*=};;
+         hostlab=*)  hostlab=${argument#*=};;
+         hostwd=*)   hostwd=${argument#*=};;
+         hosthome=*) hosthome=${argument#*=};;
+         modules=*)  modules=${argument#*=};;
          *)          other="$other $argument"
       esac
    done <<< "$full_command"
 
-   
-done
+   # The UML console socket filepath
+   mconsole=$MCONSOLE_DIR/$umid/mconsole
 
-
-# This function prints complete information about a virtual machine
-printVMinfo() {
-   echo
-   echo "============= Information for virtual machine \"$VMINFO_NAME\" ============="
+   # Output the machine details in a structured format
+   echo "============= Information for virtual machine '$umid' ============="
    echo " --- Accounting information ---"
-   echo "   PID:        $VMINFO_PID"
-   echo "   Owner:      $VMINFO_USER"
-   echo "   Used mem:   $VMINFO_SIZE KB"
+   echo "   PID:               $pid"
+   echo "   Owner:             $owner"
+   echo "   Used mem:          $memory_usage KB"
    echo " --- Emulation parameters ---"
-   echo "   Kernel:     $VMINFO_KERNEL"
-   [ ! -z "$VMINFO_KERNEL_MODULES" ] && echo "   Modules:    $VMINFO_KERNEL_MODULES"
-   echo "   Memory:     ${VMINFO_MEM} MB"
-   echo "   Model fs:   $VMINFO_SHAREDFS"
-   echo -n "   Filesystem: "
-   if [ "$VMINFO_FS" = "$VMINFO_SHAREDFS" ]; then
-      echo "using model fs (no COW)"
-   else
-      echo "$VMINFO_FS"
-   fi
-   
-   if [ ! -z "$VMINFO_ETH_INTERFACES" ]; then
-      echo -n "   Interfaces: "
-      echo "$VMINFO_ETH_INTERFACES" | awk -v RS=" +" -v FS="=" \
-         '{
-            if ($0 == "") {
-               getline
-               NR--
-            }
-            if (NR>1) printf "               "
-            device = $1
-            match ($2, "^[^_]+_[^_]+_[^_\\.]+\\..*")
-            gsub("\n","",$2)
-            hub_param_count = split(substr($2,RSTART,RLENGTH), hub_parameters, "[_.]")
-            collision_domain = hub_parameters[hub_param_count-1]
-            print device " @ " collision_domain "  (" $2 ")"
-         }'
-   fi
-   [ ! -z "$VMINFO_HOSTHOME" ] && echo "   Hostfs at:  $VMINFO_HOSTHOME"
-   [ ! -z "$VMINFO_EXEC" ] && echo "   Boot cmd:   $VMINFO_EXEC"
-   [ ! -z "$VMINFO_HOSTLAB" ] && echo "   Hostlab at: $VMINFO_HOSTLAB"
-   [ ! -z "$VMINFO_HOSTWD" ] && echo "   Host WD at: $VMINFO_HOSTWD"
-   echo -n "   Console 1:  "
-   case "$VMINFO_CON0" in
-      NONE)    echo "disabled";;
-      XTERM)   echo "terminal emulator";;
-      THIS)    echo "stdin/stdout";;
-      PTY)     echo "pty";;
-      PORT:*)  echo "port ${VMINFO_CON0#PORT:}"
+   echo "   Kernel:            $program"
+   echo "   Modules:           ${modules:-"-"}"
+   echo "   Memory:            $((mem - VM_MEMORY_SKEW)) MB (+$VM_MEMORY_SKEW MB skew)"
+   echo "   Model fs:          $fs"
+   echo "   Filesystem:        ${disk:-"-"}"
+
+   echo -n "   Interfaces:        "
+
+   first_iteration=true
+   for i in "${!uml_sockets[@]}"; do
+      filepath=${uml_sockets[$i]}
+      filename=$(basename "$filepath")
+
+      collision_domain_and_ext=${filename#"$HUB_SOCKET_PREFIX"_*_}
+      collision_domain=${collision_domain_and_ext%"$HUB_SOCKET_EXTENSION"}
+
+      # Indent subsequent lines
+      if $first_iteration; then
+         first_iteration=false
+      else
+         echo -n "                      "
+      fi
+
+      echo "eth$i @ $collision_domain ($filepath)"
+   done
+
+   echo "   Hostlab:           ${hostlab:-"-"}"
+   echo "   Hosthome:          ${hosthome:-"-"}"
+   echo "   Working directory: ${hostwd:-"-"}"
+   echo "   Boot command:      ${boot_cmd:-"-"}"
+
+   echo -n "   Console 1:         "
+   case "$con0" in
+      none)    echo "disabled";;
+      xterm)   echo "terminal emulator";;
+      this)    echo "stdin/stdout";;
+      pty)     echo "pty";;
+      port:*)  echo "port ${con0#"port:"}"
    esac
-   echo -n "   Console 2:  "
-   case "$VMINFO_CON1" in
-      NONE)    echo "disabled";;
-      XTERM)   echo "terminal emulator";;
-      THIS)    echo "stdin/stdout";;
-      PTY)     echo "pty";;
-      PORT:*)  echo "port ${VMINFO_CON1#PORT:}"
+
+   echo -n "   Console 2:         "
+   case "$con1" in
+      none)    echo "disabled";;
+      xterm)   echo "terminal emulator";;
+      this)    echo "stdin/stdout";;
+      pty)     echo "pty";;
+      port:*)  echo "port ${con1#"port:"}"
    esac
-   [ ! -z "$VMINFO_APPENDED" ] && echo "   Other args: $VMINFO_APPENDED"
-   echo "   Mconsole:   $VMINFO_MCONSOLE"
-   echo
+
+   echo "   Other arguments:   ${other:-"-"}"
+   echo "   Console socket:    $mconsole"
 }
 
 
-# Get information for specific virtual machines
-for VM in $VM_IDS; do
-   if echo $VM | grep -qE "^[0-9]+$"; then
-      # This is a virtual machine PID
-      if ! getVMinfoByPID "$VM"; then
-         echo 1>&2 "$SCRIPTNAME: no virtual machine having PID $VM exists."
-      else
-         printVMinfo
-      fi
+# Get verbose information for specific virtual machines
+for vm in "${vm_ids[@]}"; do
+   if pid=$(get_vm_pid_by_name "$USER" "$vm"); then
+      print_vm_info "$pid"
    else
-      # This is a virtual machine name
-      if ! getVMinfoByName "$USER" "$VM"; then
-         echo 1>&2 "$SCRIPTNAME: no virtual machine named \"$VM\" exists for user $USER."
-      else
-         printVMinfo
-      fi
+      echo 1>&2 "$SCRIPTNAME: no virtual machine named '$vm' exists for $USER"
    fi
 done
