allow --help/--version to be ran without a subcmd

diff --git a/core/bin/vpackage b/core/bin/vpackage
--- a/core/bin/vpackage
+++ b/core/bin/vpackage
@@ -159,17 +159,6 @@ filesystem=$VM_MODEL_FS
 mount_point=$VPACKAGE_MOUNT_POINT
 
 
-# We don't want the vpackage subcommand to be reordered by getopt, so we
-# swallow it here.
-if [ "$#" -lt 1 ]; then
-   echo 1>&2 "$SCRIPTNAME: Missing subcommand"
-   usage 1
-fi
-
-cmd=$1
-shift
-
-
 # Get command line options
 long_opts="assume-yes,filesystem:,help,only-upgrade,pass:,print,version,yes"
 short_opts="d:o:py"
@@ -230,15 +219,18 @@ while true; do
    shift
 done
    
-# Non-option arguments are package names
-packages=( "$@" )
+# The first non-option argument is the subcommand, the rest are package names
+if [ "$#" -lt 1 ]; then
+   echo 1>&2 "$SCRIPTNAME: Missing subcommand"
+   usage 1
+fi
 
-
-apt_get_cmd=( "sudo" "apt-get" "$cmd" "--option" "Dir=$mount_point" "${passthrough_opts[@]}" )
+subcommand=$1
+packages=( "${@:2}" )
 
 
 # Warn for dangerous options
-if [ "$cmd" = "dist-upgrade" ]; then
+if [ "$subcommand" = "dist-upgrade" ]; then
    while true; do
       read -rp "Warning: dist-upgrade has the potential to delete packages that may be critical to the operation of Netkit. Continue [y/N]? " response
       case $response in
@@ -255,10 +247,12 @@ if [ "$cmd" = "dist-upgrade" ]; then
 fi
 
 
+apt_get_cmd=( "sudo" "apt-get" "$subcommand" "--option" "Dir=$mount_point" "${passthrough_opts[@]}" )
+
 # The following apt-get commands are not supported for reasons relating to
 # complexity or lack of necessity for most users: dselect-upgrade, source,
 # build-dep, check, autoclean|auto-clean, changelog, and indextargets.
-case $cmd in
+case $subcommand in
    list)
       # List currently installed packages
       mount_fs "$filesystem" "$mount_point"
@@ -273,7 +267,7 @@ case $cmd in
       "${apt_get_cmd[@]}" "${packages[@]}"
       ;;
    *)
-      echo 1>&2 "$SCRIPTNAME: Invalid subcommand '$cmd'"
+      echo 1>&2 "$SCRIPTNAME: Invalid subcommand '$subcommand'"
       usage 1
       ;;
 esac
