reorder and comment kernel_cmd construction

diff --git a/core/bin/vstart b/core/bin/vstart
--- a/core/bin/vstart
+++ b/core/bin/vstart
@@ -479,6 +479,7 @@ while true; do
          foreground=1
          ;;
       -f|--filesystem)
+         # Filepath is validated with validate_ubd_argument later
          filesystem=$(readlink --canonicalize-missing "$2")
          shift
          ;;
@@ -507,6 +508,7 @@ while true; do
          shift
          ;;
       -m|--model-fs)
+         # Filepath is validated with validate_ubd_argument later
          VM_MODEL_FS=$(readlink --canonicalize-missing "$2")
          shift
          ;;
@@ -579,17 +581,20 @@ if [ "$VM_CON0" = "this" ] && [ "$VM_CON1" = "this" ]; then
    usage 1
 fi
 
-# Check whether a COW filesystem has been explictly provided when using the --no-cow option
-if [ -n "$no_cow" ] && [ -n "$filesystem" ]; then
-   echo 1>&2 "$SCRIPTNAME: Cannot provide a filesystem name with --no-cow"
-   usage 1
-fi   
+if [ -n "$no_cow" ]; then
+   # Check whether a COW filesystem has been explictly provided when using the --no-cow option
+   if [ -n "$filesystem" ]; then
+      echo 1>&2 "$SCRIPTNAME: Cannot provide a filesystem name with --no-cow"
+      usage 1
+   fi   
 
-# Check whether the user asked to hide the virtual machine filesystem while using the --no-cow option
-if [ -n "$remove_fs" ] && [ -n "$no_cow" ]; then
-   echo 1>&2 "$SCRIPTNAME: Cannot hide the filesystem when using --no-cow"
-   usage 1
+   # Check whether the user asked to hide the virtual machine filesystem while using the --no-cow option
+   if [ -n "$remove_fs" ]; then
+      echo 1>&2 "$SCRIPTNAME: Cannot hide the filesystem when using --no-cow"
+      usage 1
+   fi
 fi
+
 
 # Check whether the requested terminal emulator application exists
 if [ "$VM_CON0" = "tmux" ] && [ "$TMUX_OPEN_TERMS" = "yes" ] || [ "$VM_CON0" = "xterm" ] || [ "$VM_CON1" = "xterm" ]; then
@@ -610,38 +615,45 @@ if [ "$VM_CON0" = "tmux" ] && [ "$TMUX_OPEN_TERMS" = "yes" ] || [ "$VM_CON0" = "
 fi
 
 
-# Start building the kernel command line
-kernel_cmd=( "$VM_KERNEL" )
+###############################################################################
+# The following code constructs the command to invoke the UML kernel instance
+###############################################################################
 
 
-echo "============= Starting virtual machine '$vhost' ============="
-echo "   Kernel:     $VM_KERNEL"
-
-
-# Setup kernel modules directory
-kernel_modules_dir="$(dirname "$VM_KERNEL")/modules"
-
-if [ -d "$kernel_modules_dir" ]; then
-   echo "   Modules:    $kernel_modules_dir"
-   kernel_cmd+=( "modules=$kernel_modules_dir" )
+### BLOCKING SCRIPT ###########################################################
+# The blocking script is a wrapper that forces gnome and tmux to block when
+# invoked.
+if [ "$VM_CON0" = "xterm" ]; then
+   kernel_cmd=( "$NETKIT_HOME/bin/block-wrapper" "$TERM_TYPE" "$vhost" )
+elif [ "$VM_CON0" = "tmux" ]; then
+   kernel_cmd=( "$NETKIT_HOME/bin/block-wrapper" "tmux" "$vhost" )
 fi
 
 
-# Set virtual machine name
-kernel_cmd+=( "name=$vhost" "title=$vhost" "umid=$vhost" )
+echo "============= Starting virtual machine '$vhost' ============="
+
+### KERNEL BINARY #############################################################
+echo "   Kernel:      $VM_KERNEL"
+kernel_cmd+=( "$VM_KERNEL" )
 
 
-# Set memory amount
-echo "   Memory:     $VM_MEMORY MB"
+### UML ID ####################################################################
+# This is used to assign a unique ID to the instance and to name the PID file
+# and mconsole socket.
+kernel_cmd+=( "umid=$vhost" )
+
+
+### MEMORY ####################################################################
+echo "   Memory:      $VM_MEMORY MB"
 ((VM_MEMORY += VM_MEMORY_SKEW))
 kernel_cmd+=( "mem=${VM_MEMORY}M" )
 
 
-# Filesystem settings
+### FILESYSTEM(S) #############################################################
 echo "   Model fs:   $VM_MODEL_FS"
 
 if [ -n "$no_cow" ]; then
-   echo "   Filesystem: using model fs (no COW)"
+   echo "   Filesystem:  using model fs (no COW)"
    validate_ubd_argument "$VM_MODEL_FS"
    check_filesystem "$VM_MODEL_FS"
 
@@ -652,7 +664,7 @@ if [ -n "$no_cow" ]; then
 else
    : "${filesystem:="$PWD/$vhost.disk"}"
 
-   echo -n "   Filesystem: $filesystem"
+   echo -n "   Filesystem:  $filesystem"
    validate_ubd_argument "$VM_MODEL_FS" "$filesystem"
    check_filesystem "$filesystem"
 
@@ -665,62 +677,22 @@ else
 fi
 
 
-# Append a boot option that specifies the root filesystem.
+### ROOT FILESYSTEM ###########################################################
 # NOTE: The following root= options should also be valid: /dev/ubda1 and
 # /dev/ubd/disc0/part1.
 kernel_cmd+=( "root=98:0" )
 
 
-# Setup mconsole directory
+### MCONSOLE DIRECTORY ########################################################
 kernel_cmd+=( "uml_dir=$MCONSOLE_DIR" )
 
 
-# Setup network interfaces
-if [ "${#interface_specifications[@]}" -gt 0 ]; then
-   echo -n "   Interfaces: "
-   setup_interfaces "${interface_specifications[@]}"
-fi
+### NETWORK INTERFACES ########################################################
+echo -n "   Interfaces:  "
+setup_interfaces "${interface_specifications[@]}"
 
 
-# Set host home directory path
-if [ -z "$no_hosthome" ]; then
-   echo "   Hostfs at:  $HOME"
-   kernel_cmd+=( "hosthome=$HOME" )
-fi
-
-
-# Check whether the virtual machine already exists
-if [ -z "$JUST_PRINT" ] && get_machine_state "$USER_ID" "$vhost"; then
-   echo 1>&2 "$SCRIPTNAME: Virtual machine '$vhost' is already running. Please halt it before starting a new one or use a different virtual machine name"
-   exit 1
-fi
-
-
-# Check whether filesystem is already in use
-if [ -z "$JUST_PRINT" ] && file_in_use "$filesystem"; then
-   echo 1>&2 "$SCRIPTNAME: Filesystem '$filesystem' is already in use. Please use a different filesystem or virtual machine name"
-   exit 1
-fi
-
-
-# Append exec, hostlab and hostwd parameters, if any
-if [ -n "$exec_cmd" ]; then
-   echo "   Boot cmd:   '$exec_cmd'"
-   kernel_cmd+=( "exec=$exec_cmd" )
-fi
-
-if [ -n "$hostlab_dir" ]; then
-   echo "   Hostlab at: $hostlab_dir"
-   kernel_cmd+=( "hostlab=$hostlab_dir" )
-fi
-
-if [ -n "$host_working_dir" ]; then
-   echo "   Host WD at: $host_working_dir"
-   kernel_cmd+=( "hostwd=$host_working_dir" )
-fi
-
-
-# Set verbosity parameter (kernel is 'verbose' by default)
+### BOOT SEQUENCE VERBOSITY ###################################################
 if [ -n "$debug" ]; then
    kernel_cmd=( "gdb --args" "${kernel_cmd[@]}" )
 elif [ -z "$verbose" ]; then
@@ -728,7 +700,7 @@ elif [ -z "$verbose" ]; then
 fi
 
 
-# Attach terminals
+### CONSOLES ##################################################################
 case $VM_CON0 in
    none)    kernel_cmd+=( "con0=null" );;
    xterm)   kernel_cmd+=( "con0=xterm" );;
@@ -746,11 +718,8 @@ case $VM_CON1 in
 esac
 
 
-# Disable SELinux
-kernel_cmd+=( "SELINUX_INIT=0" )
-
-
-# Setup a proper terminal emulator
+### CREATE "PROPER" TERMINAL EMULATOR #########################################
+# Argument format is <terminal emulator>,<title switch>,<exec switch>
 case $TERM_TYPE in
    gnome)         kernel_cmd+=( "xterm=gnome-terminal,-t,-x" );;
    konsole)       kernel_cmd+=( "xterm=konsole,-T,-e" );;
@@ -758,7 +727,56 @@ case $TERM_TYPE in
 esac
 
 
-# Append any other user provided parameters
+# The following options are ignored by the UML kernel (they are not valid
+# command-line options), but used by the Netkit start-up scripts when reading
+# /proc/cmdline.
+
+### KERNEL MODULES ####################################### (non-UML option) ###
+kernel_modules_dir="$(dirname "$VM_KERNEL")/modules"
+
+if [ -d "$kernel_modules_dir" ]; then
+   echo "   Modules:     $kernel_modules_dir"
+   kernel_cmd+=( "modules=$kernel_modules_dir" )
+fi
+
+
+### MACHINE NAME ######################################### (non-UML option) ###
+kernel_cmd+=( "name=$vhost" "title=$vhost" )
+
+
+### HOSTHOME DIRECTORY ################################### (non-UML option) ###
+if [ -z "$no_hosthome" ]; then
+   echo "   Hosthome at: $HOME"
+   kernel_cmd+=( "hosthome=$HOME" )
+fi
+
+
+### HOSTLAB DIRECTORY #################################### (non-UML option) ###
+if [ -n "$hostlab_dir" ]; then
+   echo "   Hostlab at:  $hostlab_dir"
+   kernel_cmd+=( "hostlab=$hostlab_dir" )
+fi
+
+
+### HOST WORKING DIRECTORY ############################### (non-UML option) ###
+if [ -n "$host_working_dir" ]; then
+   echo "   Host WD at:  $host_working_dir"
+   kernel_cmd+=( "hostwd=$host_working_dir" )
+fi
+
+
+### BOOT COMMAND ######################################### (non-UML option) ###
+if [ -n "$exec_cmd" ]; then
+   echo "   Boot cmd:    '$exec_cmd'"
+   kernel_cmd+=( "exec=$exec_cmd" )
+fi
+
+
+### DISABLE SELINUX ###################################### (non-UML option) ###
+kernel_cmd+=( "SELINUX_INIT=0" )
+
+
+### OTHER ARGUMENTS ###########################################################
 if [ ${#kernel_cmd_append[@]} -gt 0 ]; then
    echo "   Other args: ${kernel_cmd_append[*]}"
    kernel_cmd+=( "${kernel_cmd_append[@]}" )
@@ -768,15 +786,27 @@ fi
 echo
 
 
-# Add our blocking script to the execution order
-if [ "$VM_CON0" = "xterm" ]; then
-   kernel_cmd=( "$NETKIT_HOME/bin/block-wrapper" "$TERM_TYPE" "$vhost" "${kernel_cmd[@]}" )
-elif [ "$VM_CON0" = "tmux" ]; then
-   kernel_cmd=( "$NETKIT_HOME/bin/block-wrapper" "tmux" "$vhost" "${kernel_cmd[@]}" )
+###############################################################################
+# The following code invokes the UML kernel and any virtual network hubs
+###############################################################################
+
+
+if [ -z "$JUST_PRINT" ]; then
+   # Check whether the virtual machine already exists
+   if get_machine_state "$USER_ID" "$vhost"; then
+      echo 1>&2 "$SCRIPTNAME: Virtual machine '$vhost' is already running; halt it or use a different hostname"
+      exit 1
+   fi
+
+   # Check whether filesystem is already in use
+   if file_in_use "$filesystem"; then
+      echo 1>&2 "$SCRIPTNAME: Filesystem '$filesystem' is already in use; specify a different filesystem"
+      exit 1
+   fi
 fi
 
 
-# Actually start network hubs
+# Start network hubs
 run_hubs "${HUB_LIST[@]}"
 
 
