refactor vstart

diff --git a/core/bin/vstart b/core/bin/vstart
--- a/core/bin/vstart
+++ b/core/bin/vstart
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 #     Copyright 2002-2009 Maurizio Patrignani, Maurizio Pizzonia, Fabio Ricci,
 #     Massimo Rimondini - Computer Networks Research Group, Roma Tre University.
@@ -407,19 +407,18 @@ fi
 
 # Check whether the requested terminal emulator application exists
 if [ "$VM_CON0" = "tmux" ] && [ "$TMUX_OPEN_TERMS" = "yes" ] || [ "$VM_CON0" = "xterm" ] || [ "$VM_CON1" = "xterm" ]; then
-   # Look for terminal application
-   TERMINAL_APPLICATION=${TERM_TYPE:-xterm}
-   [ $TERMINAL_APPLICATION = "konsole-tab" ] && TERMINAL_APPLICATION=konsole
-   [ $TERMINAL_APPLICATION = "gnome" ] && TERMINAL_APPLICATION=gnome-terminal
-   [ $TERMINAL_APPLICATION = "alacritty" ] && TERMINAL_APPLICATION=alacritty
-   [ $TERMINAL_APPLICATION = "kitty" ] && TERMINAL_APPLICATION=kitty
-   [ $TERMINAL_APPLICATION = "wsl" ] && TERMINAL_APPLICATION="wsl.exe"
-   [ $TERMINAL_APPLICATION = "wt" ] && TERMINAL_APPLICATION="wt.exe"
-   # Checks that we're on wsl by looking for the wsl executable which is
-   # exposed as a local command on wsl 2 systems.
-   if ! which $TERMINAL_APPLICATION > /dev/null 2>&1; then
-      warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-               "Terminal emulator \"$TERMINAL_APPLICATION\" appears not to be available. Please install it or use --xterm."
+   # Some xterm option arguments are not their relevant executable's name. We
+   # hence map these edge cases here.
+   case "$TERM_TYPE" in
+      gnome)         TERM_EXE="gnome-terminal";;
+      konsole-tab)   TERM_EXE="konsole";;
+      wsl)           TERM_EXE="wsl.exe";;
+      wt)            TERM_EXE="wt.exe";;
+      *)             TERM_EXE=$TERM_TYPE;;
+   esac
+
+   if ! command -v "$TERM_EXE" > /dev/null 2>&1; then
+      echo 1>&2 "$SCRIPTNAME: $TERM_EXE: Terminal emulator not found"
       exit 1
    fi
 fi
@@ -508,35 +507,37 @@ setupInterfaces() {
 
 ################## Building kernel command line ##################
 
-: ${VM_FS:="${PWD}/${VM_NAME}.disk"}
+: "${VM_FS:="$PWD/$VM_NAME.disk"}"
 KERNELCMD="$VM_KERNEL"
 
 check_filesystem() {
-   FS_TYPE=$(stat -f $2 | grep -w Type)
+   FS=$1
+
+   FS_TYPE=$(stat -f "$FS" | grep -w Type)
    FS_TYPE=${FS_TYPE#*Type: }
-   if echo $FS_TYPE | grep -vqE "(ext[2,3,4])|(ntfs)|(ntfs-3g)|(fuse)|(reiser)|(jfs)|(xfs)"; then
-      warning "$SCRIPTNAME" "$CMDLINE" "$1" "Filesystem $FS_TYPE does not seems to support sparse file $2. This may result in dramatic performance loss and disk space consumption."
+
+   if echo "$FS_TYPE" | grep -vqE "(ext[2,3,4])|(ntfs)|(ntfs-3g)|(fuse)|(reiser)|(jfs)|(xfs)"; then
+      echo 1>&2 "$SCRIPTNAME: Filesystem '$FS_TYPE' does not seem to support sparse files, this may result in performance loss and disk space consumption"
    fi
 }
 
-# Check if model fs or cow fs are on a filesystem supporting sparse file
+# Check if model fs or cow fs are on a filesystem supporting sparse files
 if [ -z "$USE_MODEL_FS" ]; then
-   check_filesystem $0 $VM_MODEL_FS
+   check_filesystem "$VM_MODEL_FS"
 else
-   check_filesystem $0 $VM_FS
+   check_filesystem "$VM_FS"
 fi
 
 if [ -z "$BE_QUIET" ]; then
-   echo
-   echo
-   echo "============= Starting virtual machine \"$VM_NAME\" ============="
+   echo "============= Starting virtual machine '$VM_NAME' ============="
    echo "   Kernel:     $VM_KERNEL"
 fi
 
 
 ##### Setup kernel modules directory
-eval KERNEL_MODULES_DIRECTORY=$(dirname $VM_KERNEL)/modules
-if [ -d $KERNEL_MODULES_DIRECTORY ]; then
+KERNEL_MODULES_DIRECTORY=$(dirname "$VM_KERNEL")/modules
+
+if [ -d "$KERNEL_MODULES_DIRECTORY" ]; then
    [ -z "$BE_QUIET" ] && echo "   Modules:    $KERNEL_MODULES_DIRECTORY"
    KERNELCMD="$KERNELCMD modules=$KERNEL_MODULES_DIRECTORY"
 fi
@@ -547,33 +548,35 @@ KERNELCMD="$KERNELCMD name=$VM_NAME title=$VM_NAME umid=$VM_NAME"
 
 
 ##### Set memory amount
-[ -z "$BE_QUIET" ] && echo "   Memory:     ${VM_MEMORY} MB"
-VM_MEMORY=$(($VM_MEMORY + $VM_MEMORY_SKEW))
+[ -z "$BE_QUIET" ] && echo "   Memory:     $VM_MEMORY MB"
+VM_MEMORY=$((VM_MEMORY + VM_MEMORY_SKEW))
 KERNELCMD="$KERNELCMD mem=${VM_MEMORY}M"
 
 
 ##### Filesystem settings
 [ -z "$BE_QUIET" ] && echo "   Model fs:   $VM_MODEL_FS"
-if [ ! -z "$USE_MODEL_FS" ]; then
+
+if [ -n "$USE_MODEL_FS" ]; then
+   [ -z "$BE_QUIET" ] && echo "   Filesystem: using model fs (no COW)"
+
    # Use model fs as virtual machine filesystem (do not use COW)
    KERNELCMD="$KERNELCMD ubd0=$VM_MODEL_FS"
+
    VM_FS="$VM_MODEL_FS"
-   [ -z "$BE_QUIET" ] && echo "   Filesystem: using model fs (no COW)"
 else
    [ -z "$BE_QUIET" ] && echo -n "   Filesystem: $VM_FS"
-   # Explicitly declaring the model fs name is redundant after the COW
-   # file has been created. Nevertheless, this is needed in order to later
-   # get information about the virtual machine (i.e., by using vlist)
+
+   # Explicitly declaring the model fs name is redundant after the COW file has
+   # been created. Nevertheless, this is needed in order to later get
+   # information about the virtual machine (i.e., by using vlist).
    KERNELCMD="$KERNELCMD ubd0=${VM_FS},${VM_MODEL_FS}"
-   if [ ! -f "$VM_FS" ]; then
-      [ -z "$BE_QUIET" ] && echo " (new)"
-   else
-      [ -z "$BE_QUIET" ] && echo
-   fi
+
+   [ -z "$BE_QUIET" ] && [ ! -f "$VM_FS" ] && echo " (new)" || echo
 fi
 
 # Append a boot option that specifies the root filesystem
 KERNELCMD="$KERNELCMD root=98:0"
+
 # The following root= options should also be valid
 # KERNELCMD="$KERNELCMD root=/dev/ubd/disc0/part1"
 # KERNELCMD="$KERNELCMD root=/dev/ubda1"
@@ -584,79 +587,76 @@ KERNELCMD="$KERNELCMD uml_dir=$MCONSOLE_DIR"
 
 
 ##### Setup network interfaces
-if [ ! -z "$ETH_INTERFACES" ]; then
+if [ -n "$ETH_INTERFACES" ]; then
    [ -z "$BE_QUIET" ] && echo -n "   Interfaces: "
    eval setupInterfaces $ETH_INTERFACES
 fi
 
 ##### Set HOSTHOME
 if [ -z "$NO_HOSTHOME" ]; then
-   KERNELCMD="$KERNELCMD hosthome=${HOME}"
    [ -z "$BE_QUIET" ] && echo "   Hostfs at:  $HOME"
+   KERNELCMD="$KERNELCMD hosthome=${HOME}"
 fi
 
 
 ##### Check whether virtual machine already exists
-if [ -z "$JUST_PRINT" ] && getVMinfoByName "$USERID" "$VM_NAME"; then
-   echo 1>&2 "${SCRIPTNAME}: Virtual machine \"$VM_NAME\" is already running. Please"
-   echo 1>&2 "halt it before starting a new one or use a different virtual machine name."
+if [ -z "$JUST_PRINT" ] && get_machine_state "$USERID" "$VM_NAME"; then
+   echo 1>&2 "${SCRIPTNAME}: Virtual machine '$VM_NAME' is already running. Please halt it before starting a new one or use a different virtual machine name"
    exit 1
 fi
 
 
 ##### Check whether filesystem is already in use
-if [ -z "$JUST_PRINT" -a -e "$VM_FS" ]; then
-   if someOneUses "$VM_FS"; then
-      echo 1>&2 "${SCRIPTNAME}: Filesystem $VM_FS is already in use. Please use a"
-      echo 1>&2 "different filesystem or virtual machine name."
-      exit 1
-   fi
+if [ -z "$JUST_PRINT" ] && file_in_use "$VM_FS"; then
+   echo 1>&2 "${SCRIPTNAME}: Filesystem '$VM_FS' is already in use. Please use a different filesystem or virtual machine name"
+   exit 1
 fi
 
 
 ##### Append exec, hostlab and hostwd parameters, if any
-if [ ! -z "$VM_EXEC" ]; then
-   [ -z "$BE_QUIET" ] && echo "   Boot cmd:   \"$VM_EXEC\""
+if [ -n "$VM_EXEC" ]; then
+   [ -z "$BE_QUIET" ] && echo "   Boot cmd:   '$VM_EXEC'"
    KERNELCMD="$KERNELCMD exec=\"$VM_EXEC\""
 fi
-if [ ! -z "$VM_HOSTLAB" ]; then
+
+if [ -n "$VM_HOSTLAB" ]; then
    [ -z "$BE_QUIET" ] && echo "   Hostlab at: $VM_HOSTLAB"
    KERNELCMD="$KERNELCMD hostlab=$VM_HOSTLAB"
 fi
-if [ ! -z "$VM_HOSTWD" ]; then
+
+if [ -n "$VM_HOSTWD" ]; then
    [ -z "$BE_QUIET" ] && echo "   Host WD at: $VM_HOSTWD"
    KERNELCMD="$KERNELCMD hostwd=$VM_HOSTWD"
 fi
 
 
-##### Set verbosity parameter
-if [ ! -z "$DEBUG" ]; then
+##### Set verbosity parameter (is 'verbose' by default)
+if [ -n "$DEBUG" ]; then
    KERNELCMD="gdb --args $KERNELCMD"
-elif [ ! -z "$VERBOSE" ]; then
-   KERNELCMD="$KERNELCMD"
-else
+elif [ -z "$VERBOSE" ]; then
    KERNELCMD="$KERNELCMD quiet"
 fi
 
 ##### Bypass port helper, if required (only allowed for the primary terminal)
-if [ $VM_CON0 = "xterm" -a "$CON0_PORTHELPER" != "yes" ]; then
-      VM_CON0="this_noporthelper"
+if [ $VM_CON0 = "xterm" ] && [ "$CON0_PORTHELPER" != "yes" ]; then
+   VM_CON0="this_noporthelper"
 fi
 
 ##### Attach terminals
 case $VM_CON0 in
-   none)    KERNELCMD="$KERNELCMD con0=null";;
-   xterm)   KERNELCMD="$KERNELCMD con0=xterm";;
+   none)                      KERNELCMD="$KERNELCMD con0=null";;
+   xterm)                     KERNELCMD="$KERNELCMD con0=xterm";;
    this|this_noporthelper)    KERNELCMD="$KERNELCMD con0=fd:0,fd:1";;
-   pty)     KERNELCMD="$KERNELCMD con0=pty";;
-   port:*)  KERNELCMD="$KERNELCMD con0=${VM_CON0}";;
+   pty)                       KERNELCMD="$KERNELCMD con0=pty";;
+   port:*)                    KERNELCMD="$KERNELCMD con0=$VM_CON0";;
 esac
+
 case $VM_CON1 in
    none)    KERNELCMD="$KERNELCMD con1=null";;
    xterm)   KERNELCMD="$KERNELCMD con1=xterm";;
    this)    KERNELCMD="$KERNELCMD con1=fd:0,fd:1";;
    pty)     KERNELCMD="$KERNELCMD con1=pty";;
-   port:*)  KERNELCMD="$KERNELCMD con1=${VM_CON1}";;
+   port:*)  KERNELCMD="$KERNELCMD con1=$VM_CON1";;
 esac
 
 
@@ -665,40 +665,34 @@ esac
 KERNELCMD="$KERNELCMD SELINUX_INIT=0"
 
 
-##### Setup a proper terminal emulator, if asked to
-if [ ! -z "$TERM_TYPE" ]; then
-   case "$TERM_TYPE" in
-      konsole)
-         KERNELCMD="$KERNELCMD xterm=konsole,-T,-e";;
-      konsole-tab)
-         KERNELCMD="$KERNELCMD xterm=$NETKIT_HOME/bin/konsole-tabs.sh,-T,-e";;
-      gnome)
-         KERNELCMD="$KERNELCMD xterm=gnome-terminal,-t,-x";;
-      xterm) ;;
-   esac
-fi
+##### Setup a proper terminal emulator
+case $TERM_TYPE in
+   gnome)         KERNELCMD="$KERNELCMD xterm=gnome-terminal,-t,-x";;
+   konsole)       KERNELCMD="$KERNELCMD xterm=konsole,-T,-e";;
+   konsole-tab)   KERNELCMD="$KERNELCMD xterm=$NETKIT_HOME/bin/konsole-tabs.sh,-T,-e";;
+esac
 
 ##### Append any other user provided parameters
-if [ ! -z "$KERNEL_APPEND" ]; then
+if [ -n "$KERNEL_APPEND" ]; then
+   [ -z "$BE_QUIET" ] && echo "   Other args: $KERNEL_APPEND"
    KERNELCMD="$KERNELCMD $KERNEL_APPEND"
-   [ -z "$BE_QUIET" ] && echo "   Other args:$KERNEL_APPEND"
 fi
 
 [ -z "$BE_QUIET" ] && echo
 
 # Add our blocking script to the execution order
-if [ "$VM_CON0" = "xterm" -o "$VM_CON0" = "this_noporthelper" ]; then
+if [ "$VM_CON0" = "xterm" ] || [ "$VM_CON0" = "this_noporthelper" ]; then
     KERNELCMD="$NETKIT_HOME/bin/block-wrapper $TERM_TYPE $VM_NAME $KERNELCMD"
 fi
 
 # Set up tmux
 if [ "$VM_CON0" = "tmux" ]; then
-   if ! which tmux > /dev/null 2>&1; then
-      warning "$SCRIPTNAME" "$CMDLINE" "$0" \
-               "tmux appears not to be installed. Exiting."
+   if ! command -v "tmux" > /dev/null 2>&1; then
+      echo 1>&2 "$SCRIPTNAME: tmux could not be found"
       exit 1
    fi
-    KERNELCMD="$NETKIT_HOME/bin/block-wrapper tmux $VM_NAME $KERNELCMD"
+   
+   KERNELCMD="$NETKIT_HOME/bin/block-wrapper tmux $VM_NAME $KERNELCMD"
 fi
 
 ##### Actually start network hubs
@@ -707,30 +701,30 @@ eval runHubs $HUBLIST
 ##### Prepare the cleanHubs function for execution after a virtual machine stops
 export cleanHubs
 
-#### Actually start virtual machine
-if [ -z "$RUN_IN_FOREGROUND" -a "$VM_CON0" != "this" -a "$VM_CON1" != "this" ]; then
+#### Start machine in background unless otherwise requested
+if [ -z "$RUN_IN_FOREGROUND" ] && [ "$VM_CON0" != "this" ] && [ "$VM_CON1" != "this" ]; then
    BACKGROUND="&"
 fi
 
 ### Invocation of uml_mconsole is needed in order to "wake up" port-helper if
 ### it ever hangs when booting the virtual machine.
-WAKEUP_PORTHELPER=""
 if [ "$CON0_PORTHELPER" = "yes" ]; then
    WAKEUP_PORTHELPER="{ sleep 5; $NETKIT_HOME/bin/uml_mconsole $VM_NAME help > /dev/null 2>&1; } &"
 fi
 
 ### Remove .disk file, if requested
-if [ ! -z "$REMOVE_FS" ]; then
+if [ -n "$REMOVE_FS" ]; then
    REMOVE_FS_COMMAND="{ while [ ! -f $VM_FS ]; do sleep 1; done; rm -f $VM_FS; } &"
 fi
 
 ### Completely hide primary console, if requested to
 if [ "$VM_CON0" = "none" ]; then
-   REDIRECT_CONSOLE=">/dev/null 2>&1"
+   REDIRECT_CONSOLE="> /dev/null 2>&1"
 fi
 
 run_command "$JUST_PRINT" "$KERNELCMD" "{ $WAKEUP_PORTHELPER $REMOVE_FS_COMMAND $KERNELCMD; cleanHubs $HUBLIST; } $REDIRECT_CONSOLE $BACKGROUND"
 
+# Connect to the tmux session if TMUX_OPEN_TERMS is set
 if [ "$TMUX_OPEN_TERMS" = "yes" ] && [ "$VM_CON0" = "tmux" ]; then
     vconnect -m "$VM_NAME" --terminal --interval 5 --retry-count 20 &> /dev/null &
 fi
